src/components/TableSkeleton/TableSkeleton.scss
src/components/TableSkeleton/TableSkeleton.tsx
src/containers/Storage/Storage.js
src/containers/Storage/Storage.scss
src/services/api.js
src/store/reducers/storage.js
src/utils/autofetcher.ts

Feature: Storage page
Current state:
- The table on the Storage page does not indicate its loading state, this is confusing for large tables with long loading times.
- Filter controls over the table are hidden while the table is loading, which does not make sense since they don’t depend on the table data
Suggested change:
- Always show the filter controls, and only put the table in loading state
- Replace Loader with Skeleton to improve visuals
- Avoid requests races by using `cuncurrentId` for requests for table data
This PR also fixes a bug found while fine-tuning the requests.
What was wrong:
In rare cases there could be ghost background requests.
The Storage page uses AutoFetcher to refresh table data in the background.
The issue occurs in case there are consequent calls of `.stop()` …

feat(Storage): Smoother loading state

---

src/components/NodesViewer/NodesViewer.scss
src/containers/Node/Node.scss
src/containers/Storage/Storage.js
src/containers/Storage/Storage.scss
src/containers/Tenant/Acl/Acl.scss
src/containers/Tenant/Diagnostics/Diagnostics.scss

Fixes introduced in this PR:
- sticky header in the ACL area of Tenant feature scrolled up after some threshold; now it is always stuck to the top side
- storage table content was visible next to the filters row for tables with horizontal scroll, after scrolling to the right; now it is not
- scrollbars on the Tenant page had messy behavior; made it more consistent
- added missing right padding on the Node storage page

Scroll-related layout fixes

---

src/containers/Storage/Pdisk/Pdisk.tsx
src/containers/Storage/Vdisk/Vdisk.js
src/containers/Storage/utils/constants.ts
src/containers/Storage/utils/index.ts

this introduces the red color for unavailable VDisk and PDisk
Disk color is determined by its status severity.
The severity (hence color) is determined by a number from 0 to 5:
0 — grey
5 — red
PDisk severity is calculated from a single field, `State`.
VDisk severity is calculated from 3 features:
- `VDiskState` — a semantic keyword
- `DiskSpace` — a color name
- `FrontQueues` — a color name
- since data has fields with color name, we can't modify the list of colors used in frontend: backend and frontend lists should match
- since the progressbar component uses a list of colors enumerated from 0 to 5, most likely we have to keep 0 as the least noticeable. We can't change the color assiciated with 0 from grey to red: grey can be required in some other use case
therefore I changed the color …

feat(Storage): red progress bars for unavailable disks

---

src/components/EntityStatus/EntityStatus.scss
src/containers/App/App.scss
src/containers/App/NodesTable.scss
src/utils/getNodesColumns.js

Leaves more space for node host fqdn, taking space for the icons only when they are visible

style(NodesTable): don't reserve space for icons next to node fqdn

---

src/containers/App/NodesTable.scss
src/containers/Tenants/Tenants.js
src/containers/Tenants/Tenants.scss

Followup on this PR: https://github.com/ydb-platform/ydb-embedded-ui/pull/42
Tenant icons follow the same visual logic as icons in NodesTable. Moreover, prop `additionalTenantsInfo` adds extra content to the tenant name cell. Previous structure and styles only allowed a single element of fixed size there. After the changes extra elements could be of any size.

refactor(Tenant): add tenant name wrapper

---

src/containers/Tenant/QueryEditor/SaveQuery/SaveQuery.js
src/containers/Tenant/QueryEditor/SaveQuery/SaveQuery.scss
src/containers/Tenant/QueryEditor/SavedQueries/SavedQueries.js

This introduces 4 updates:
1. Query deletion can now be confirmed by hitting Enter
2. Query saving can now be confirmed by hitting Enter
3. Query name field is now initially focused, allowing immediate typing
4. The warning for losing saved queries upon cookies deletion is now replaced with a note about how queries are saved in the save dialog
More about 4:
The reasons why it needs to be changed:
- the message is incorrect: queries are saved not in cookies, but in local storage
- the message under the question mark icon requires an extra action to be seen; the message in the save dialog does not

Improve Save Query UX

---

src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/utils/schemaActions.ts
src/store/reducers/tenant.js
src/store/state-url-mapping.js

there are two commits:
redux-location-state tends to overwrite changes made with HistoryAPI, if push to history is made simultaneously with modifying URL with redux-location-state. Better not to mix these two approaches.
In dev environment, 2nd level tabs on Diagnostics sometimes don't update after changing the current node in the schema. Investigated and fixed.

fIx Tenant tabs navigation

---

src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Tenant.tsx
src/containers/Tenant/utils/schema.ts
src/services/api.d.ts
src/types/api/schema.ts

`OlapTable` and `OlapStore` were at some point renamed to `ColumnTable` and `ColumnStore` respectively. This change was never supported in UI. This PR fixes it.
Also, the initial intent for this PR — this PR adds types coverage for the api call `json/describe`.

Up types coverage and fix ColumnTables displaying

---

package-lock.json
package.json
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/utils/schema.ts
src/containers/Tenant/utils/schemaActions.ts
src/types/api/schema.ts

Indexes now only display the Overview tab, and have no context actions in the schema
Indexes implementation tables only have the `Copy path` context action

Separate views for index nodes in schemas

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Tenant.tsx
src/containers/Tenant/utils/schema.ts

I removed the preview options from the context menu, but kept it on the toolbar. This removes the «Show Preview» button from the toolbar for index tables.

fix(Tenant): hide preview button for index tables

---

package-lock.json
package.json
src/containers/App/App.js

Starting from 2.3.0 release ydb-ui-components supports setting up language via `configure` function. This PR updates ydb-ui-components to 2.3.0 and supports that pattern.

refactor: use configure for ydb-ui-components

---

src/containers/Tenant/Diagnostics/DetailedOverview/DetailedOverview.scss
src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.js
src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.js
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.scss

This PR introduces two changes:
1. Trimming of a tenant name from the start
2. Adjustments of the overview section layout
A tenant name is always a path, therefore the meaningful part is at the end, and it is safe to omit its start to fit the whole name into one line.
Adjustments are to fine-tune alignment of content blocks in the overview.

fix(TenantOverview): display tenant name in single line

---

src/components/BasicNodeViewer/BasicNodeViewer.scss
src/components/BasicNodeViewer/BasicNodeViewer.tsx
src/components/BasicNodeViewer/index.ts
src/components/FullNodeViewer/FullNodeViewer.js
src/components/FullNodeViewer/FullNodeViewer.scss
src/containers/Node/Node.scss
src/containers/Node/Node.tsx
src/containers/Node/NodeOverview/NodeOverview.tsx
src/containers/Node/NodeStructure/NodeStructure.scss
src/containers/Node/NodeStructure/PDiskTitleBadge.tsx
src/containers/Node/NodeStructure/Pdisk.tsx
src/types/api/storage.ts
src/utils/pdisk.ts

This PR introduces 2 changes:
- change data on PDisks panels
- move node basic info from the overview tab to every tab above the tabs row
Data on the PDisks panels contained Node ID, which repeated, and was redundant. Moving the overview header above the tabs makes it possible to remove Node ID from the PDisks panel while keeping this info on the page.
PDisks now contain new info about its type (SSD, NVME, etc.), which is calculated from its Category. A new field is added to the expanded PDisk view, as well as to the collapsed panel. Some other info from the expanded view now also appears on the collapsed panel.

feat(Node): more informative pdisks panels

---

src/containers/Nodes/Nodes.js

Tooltip persisted after navigating inside a node. This PR fixes it.

fix(Nodes): hide tooltip on unmount

---

src/components/IndexInfoViewer/IndexInfoViewer.tsx
src/components/InfoViewer/index.ts
src/components/InfoViewer/utils.ts
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/Schema/SchemaInfoViewer/SchemaInfoViewer.js
src/types/api/schema.ts

This introduces a bug fix, a change in current behaviour, and a new feature.
Was located on tables overview tab.
Due to incorrect data merging some rows didn't display, now they do.
Tables overview lines order changed: now the first line is always PartCount, if it exists.
Now there is a separate view for Overview tab for table indexes.

feat(Tenant): table index overview

---

src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/Diagnostics/HotKeys/HotKeys.js
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/utils/schema.ts
src/containers/Tenant/utils/schemaActions.ts

This PR addresses two issues:
- fixes a bug that caused an incorrect behavior of ColumnTables in schema viewer
- ensures that similar issues will not happen in the future
What caused the bug: after adding new schema node types in ydb-ui-components I didn't update some of the cases where UI behavior was dependent on this type.
The fix is to include the new types in conditions where it matters.
The change to ensure future correctness:
Now in all places where UI behavior is dependent on either NavigationTree node type, or a PathType from data, a conditional statements are replaced with a verbose map that, via types constraints, must contain keys of all existing types. This ensures that, when a new entity is added, TS will error until this entity is mapped to the corresponding UI beavior.

fix(Tenant): ensure correct behavior for new schema node types

---

src/components/IndexInfoViewer/IndexInfoViewer.tsx
src/components/InfoViewer/InfoViewer.scss
src/components/InfoViewer/utils.ts
src/containers/Tenant/Diagnostics/DetailedOverview/DetailedOverview.tsx
src/containers/Tenant/Schema/SchemaInfoViewer/SchemaInfoViewer.js
src/containers/Tenant/Schema/SchemaInfoViewer/SchemaInfoViewer.scss
src/services/api.js
src/types/api/schema.ts
src/utils/index.js

This PR introduces 2 changes:
1. Reformat & group table information in overview for better readability (4th commit)
2. Display new info about table read-only replicas in a new section of overview (5th commit)
the first 3 commits are technical updates to support the 4th one

Add & cleanup data in tables overview

---

src/containers/Tenant/Schema/SchemaInfoViewer/SchemaInfoViewer.js
src/utils/index.js

Undefined values displayed as 0s, which caused Table Stats to display even when no data was provided. Changed formatters behavior to return an empty string for absent values.

fix(Overview): format undefined values to empty string, not 0

---

src/containers/Storage/StorageGroups/StorageGroups.tsx
src/containers/Storage/utils/index.ts
src/types/api/schema.ts
src/types/api/storage.ts

Fix for crashes caused by unexpected data in the Donors field.
Along with that, more correct types for some fields: uint32 via HTTP received as number, not string.

fix(Storage): expect arbitrary donors data

---

src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx

In SPA mode, when switching between adjacent databases in the same cluster, `currentSchamePath` from the previous database preserves, and tries to load. When it exists (e.g. when opening an ancestor path), everything is fine. When it does not exist, nothing is selected in the tree, and nothing is loaded.
This PR fixes this case and shows the root node when the cashed path does not exist in the tree — assuming every path in a tree starts with the root path.

fix(Tenant): load root if cahced path is not in tree

---

src/components/QueryResultTable/QueryResultTable.tsx
src/containers/Tenant/Preview/Preview.js
src/services/api.d.ts
src/store/reducers/executeQuery.js
src/store/reducers/preview.ts
src/types/api/query.ts
src/types/store/query.ts
src/utils/query.test.ts
src/utils/query.ts

This PR
- adds a better type coverage for possible response value format for `viewer/json/query`,
- fixes bugs in response parser
- covers the parser with unit-tests
Also this PR fixes a behavior, in which absent response after e.g. `INSERT` query displayed in the result area as an empty result.

fix: correct types & parsing for query api response

---

src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueries.js
src/containers/Tenant/Diagnostics/TopShards/TopShards.js
src/containers/Tenant/Schema/SchemaInfoViewer/SchemaInfoViewer.scss
src/store/reducers/executeTopQueries.js
src/store/reducers/olapStats.js
src/store/reducers/shardsWorkload.js

This PR addresses two issues:
1. Response format of `viewer/json/query`
2. Column tables info tab data fetching
1 — after adopting the `result` field in query response in PRs #168 and #170, this finishes the change, applying the proper response parser and making sure the API is called with the proper params
2 — while updating column tables info tab to work with the new query response format, I bumped into a bug with data refetching. Column tables require extra data for the Info tab, which is fetched from `viewer/json/query`. The bug is, in some cases (more often than not) the fetch wasn't initiated upon schema navigation. This PR fixes this, and the proper data always fetch for column tables.

fix: modern query format

---

src/containers/Tenant/QueryEditor/Issues/Issues.scss
src/containers/Tenant/QueryEditor/QueryEditor.js
src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.js
src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.scss
src/store/reducers/explainQuery.js
src/types/api/query.ts
src/types/store/query.ts
src/utils/prepareQueryExplain.ts
src/utils/query.test.ts
src/utils/query.ts

This PR introduces 3 changes:
1. in api call `viewer/json/query`, use modern response schema for explain actions
2. adjust explain components styles for a better fit: fixed spacings & dimensions
3. fix parsing of the v2 explain format which displayed incorrectly

fix: properly request & display queries explain

---

src/containers/UserSettings/UserSettings.tsx

In single cluster mode settings save in localStorage as strings, whereas multi-cluster mode keeps the initial value type. The initialization of the `invertedDisks` param expects a string. This change equalizes both cases.

fix(UserSettings): save invertedDisks as string

---

src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.js

The fullscreen button was available for empty explanation, which led to a bug
Steps to reproduce the bug before:
- run Explain for query `select 1`
- click the fullscreen button
- switch to either JSON or AST tab
ER: the content changes to JSON or AST respectively
AR: fullscreen opens, with either JSON or AST content, respectively
The reason is there is no content to display in fullscreen, but it toggles anyways, displaying nothing. Then it shows after content appears because of switching the explain mode

fix(QueryEditor): disable fullscreen button for empty result

---

src/containers/Tenant/QueryEditor/QueryResult/QueryResult.scss

This fixes this issue with paddings:

fix(QueryEditor): fix query stats spacings

---

.eslintrc
config-overrides.js
prepare-build.sh
src/.eslintrc

This fixes serving media for the embedded installations. The `Illustrations` component wasn't working because of incorrect paths.

fix: fix production assets paths

---

src/components/ShortyString/ShortyString.tsx
src/components/ShortyString/i18n/en.json
src/components/ShortyString/i18n/index.ts
src/components/ShortyString/i18n/ru.json

Don't trim errors if the toggle label is longer than the trimmed part

fix(QueryEditor): smarter error message trim

---

.eslintrc
package.json

Reverts ydb-platform/ydb-embedded-ui#189
While generally a good idea, enabling prettier rules without reformatting the code base according to these rules breaks the build.
We should probably enable this later on, but after applying the autofixer to all the files and carefully revising them.

Revert "fix: fix pre-commit prettier linting and add json linting"

---

src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/schema.js

This fixes the issue with selected tabs being reset to Info when navigating from the root to a table in schema tree.
The expected behaviour is, when the previous node and the next node share a tab, and it is selected, it remains selected.
The cause of the bug is the following.
A set of tabs to display is determined by the selected node type. During the change between nodes, the selected node data cleans up, which causes the tabs to render for a default node type, which is `directory`. This is the moment when the selected tab resets to the default Info. After the data for the selected node is loaded, the type becomes properly set, but the selected tab has already became Info.
This fixes the bug by changing where the tabs component selects the current node type from.
When expanding a schema …

fix(Tenant): prevent selected tab reset on tree navigation

---

src/containers/Tenant/Diagnostics/Diagnostics.scss
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/store/reducers/tenant.js

On page reload path type is undefined, so default values are set for tabs:
`const DIR_PAGES = [overview, topShards, describe];`
If there is not tab from search query in this list, the tab is set to `overview`, so it is impossible to get for example TopShard or Tablets tab right after page reload.
To fix it wasLoaded flag for tenant reducer is introduced, so the tab is set only after content is initially loaded. While the content is loading, tabs are hidden behind Loader.

fix(Diagnostics): fix tabs reset on page reload

---

src/components/NodesViewer/NodesViewer.js
src/containers/Nodes/Nodes.js
src/containers/Tenant/QueryEditor/SaveQuery/SaveQuery.js
src/containers/Tenants/Tenants.js

This fixes the incorrect props used for defining text inputs values.
The only component where it affected the UI is Tenants. The filtration function there has separate uses from the input, causing the filtration without updating the input value correspondingly.

fix: use correct prop for textinputs value

---

src/containers/App/App.scss
src/containers/Storage/StorageGroups/StorageGroups.scss
src/containers/Storage/StorageGroups/StorageGroups.tsx
src/containers/Storage/StorageNodes/StorageNodes.scss
src/containers/Storage/StorageNodes/StorageNodes.tsx
src/styles/mixins.scss

This PR is miscellaneous changes
- fixes tooltip layout for the Nodes section of Storage the same way it was fixed for the Groups section in #136 
- introduces a css variable for table row hover color, making maintenance easier
- does a bit of cleanup for Storage tooltips

fix(Storage): shrink tooltip active area on FQDN

---

src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/olapStats.js
src/store/reducers/schema.js
src/utils/hooks/useAutofetcher.ts

This fixes the bug with a flash of an empty state when navigating a tenant schema.
a few reasons for this bug:
1. `wasLoaded` didn't reset on active path change. Because of this loader didn't display, as it should for background updates — fixed by setting `wasLoaded` to false on active path change
2. because of too many requests for `viewer/json/describe`, some of them were being cancelled by newer ones. A request cancellation is treated as a request error, which sets `loading` to false. Fixed by ignoring errors caused by requests cancellation and not changing the store for them.
3. another consequence of too many parallel requests to `viewer/json/describe` is a more complex bug, which is still present. `Tenant` initiates 2 requests for its root and the selected node on active path …

fix(Tenant): show loader when fetching overview data

---

src/containers/Storage/Storage.js
src/store/reducers/storage.js

If open storage page and then switch storage type or other filters in controls, "no such groups / nodes" message will be displayed instead of skeletons. This happens due to `loading` property reset by cancelled fetch action.

fix(Storage): fix no such groups message instead of skeletons

---

src/components/QueryResultTable/QueryResultTable.tsx
src/containers/Tenant/Preview/Preview.scss
src/containers/Tenant/QueryEditor/QueryEditor.js
src/containers/Tenant/QueryEditor/QueryResult/QueryResult.scss

Currently table preview displays only one row. 
This might be due to the default table property is set to `"uniform"`, [so the size of the table is calculated beforehand to fit the viewport](https://github.com/caseywebdev/react-list#type-one-of-simple-variable-or-uniform-defaults-to-simple). Here it probably takes the size of the container and displays only the minimal number of items (1). So the default QueryResultTable `dynamicRenderType` was set to `"variable"` as it was in [QueryEditor](https://github.com/ydb-platform/ydb-embedded-ui/blob/main/src/containers/Tenant/QueryEditor/QueryEditor.js).

fix(QueryResultTable): fix full screen table preview

---

src/store/reducers/schema.js
src/store/reducers/storage.js

It turned out, that there could be fetch failure with no errors, and it breaks on attempt to read isCancelled property of undefined error.

fix: add checks for fetch failure with no errors

---

src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/store/reducers/schema.js

This fixes a bug with the schema tree.
Expanding a node with a large amount of children caused a visual bug, when only a few first children displayed.
The reason is that children data was saved in the store using a separate dispatch for each child node. In case of hundreds of children this was causing performance issues.
This change alters this behaviour. Child nodes data is now collected and dispatched once in a batch.

perf(SchemaTree): batch preloaded data dispatch

---

package-lock.json
package.json
src/containers/Tenant/Diagnostics/Consumers/Consumers.tsx
src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.tsx
src/store/getUrlData.ts
src/store/index.js
src/store/reducers/describe.ts
src/store/reducers/header.ts
src/store/reducers/healthcheckInfo.ts
src/store/reducers/index.ts
src/store/reducers/preview.ts
src/store/reducers/saveQuery.ts
src/store/reducers/singleClusterMode.ts
src/types/api/error.ts
src/types/api/query.ts
src/types/store/describe.ts
src/types/store/healthcheck.ts
src/types/store/index.ts
src/types/window.d.ts
src/utils/hooks/index.ts
src/utils/hooks/useTypedSelector.ts

Update reselect to 4.1.6. 
Since new version changes lib typings a lot, corresponding selectors and reducers typing was added, as well as IRootState type and useTypedSelector hook.

refactor: update reselect to 4.1.6 and change selectors typings

---

src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/utils/schema.ts
src/types/api/schema.ts

App crashes on ColumnTable type selection in SchemaTree. The problem is in the functions `prepareOlapTableSchema` and `prepareOlapTableGeneral` that try to take the properties of undefined object or take properties that do not exist.
To fix it I set default value for incoming `tableData`, also I took typings for ColumnTable and ColumnStore from backend for more careful properties check.
There is still some issue with the loading reset for the unloaded data, although it is not as critical as the current issue.

fix: fix app crash on ColumnTable path type

---

src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.js

This PR fixes explain schema unchanged colours on theme change.
In paranoid scheme colours are calculated in JS. The problems is that when theme is changed from JS, new colours applies only after schema is rendered. To fix this, additional useEffect for schema rerender was added.

fix(QueryExplain): fix graph colours on theme change

---

src/components/InfoViewer/schemaInfo/CDCStreamInfo.tsx
src/containers/Tenant/Diagnostics/Consumers/Consumers.tsx
src/containers/Tenant/Diagnostics/Describe/Describe.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/utils/schema.ts
src/services/api.d.ts
src/store/reducers/describe.ts
src/store/reducers/schema.ts
src/types/store/describe.ts
src/types/store/schema.ts

In this PR data for `PersQueueGroup` and `CdcStreams` was merged in `Diagnostics` tabs (Overview, Consumers, Describe). Object of type PersQueueGroup is no longer visible.
To do so functionality for batched requests was added for `createApiRequest` method and  in `describe` and `schema` reducers. `Consumers` tab was enabled to fetch data by child path, while `Overview` and `Describe` tabs to fetch data for both parent and children.

feat: merge PQGroup and CDCStream

---

package-lock.json
package.json

The reason for an update - react-data-table of latest version can accept string as column width, so there is no error when used with TS

chore: @yandex-cloud/react-data-table -> 1.0.2

---

src/components/InfoViewer/InfoViewer.scss

Without the minimum width values in the overview section shrinked to a one-char column

fix(InfoViewer): min width for values

---

src/.eslintrc

I don't like this rule, because it makes one to write arguments and return types for functions when writing JSDoc comments. I think TS types are sufficient for that matter

chore: turn off valid-jsdoc eslint rule

---

src/containers/Storage/DiskStateProgressBar/DiskStateProgressBar.scss
src/containers/Storage/DiskStateProgressBar/DiskStateProgressBar.tsx
src/containers/Storage/DiskStateProgressBar/index.ts
src/containers/Storage/Pdisk/Pdisk.tsx
src/containers/Storage/Vdisk/Vdisk.js
src/containers/Storage/utils/constants.ts

Disk severity references were overcomplicated and unclear, this simplifies them.

refactor(DiskStateProgressBar): clarify severity references

---

src/services/api.d.ts
src/services/api.js
src/store/reducers/nodes.ts
src/store/reducers/storage.js
src/store/reducers/tenant.js
src/types/store/nodes.ts

Fix storage nodes API request for Storage Tab. Currently on newer versions `/viewer/json/nodes` returns both static and dynamic nodes, if there is no type flag. So on newer cluster versions (for example on Vla02) dynamic nodes are displayed in Storage, that is not correct. This PR fixes it and prevents any issues if any cluster version will be updated before PR #249 will be merged

fix(Storage): request only static nodes

---

src/containers/Tenant/Diagnostics/OverloadedShards/OverloadedShards.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx
src/store/reducers/shardsWorkload.ts

Now that all dates are displayed in the local timezone, we can output IntervalEnd for top queries and overloaded shards tables with no confusion

fix(TopQueries, OverloadedShards): display IntervalEnd

---

src/containers/Nodes/Nodes.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/DiagnosticsPages.ts

/compute endpoint now is able to return nodes for not DB entities in diagnostics. So Nodes tab is enabled for them

fix(Diagnostics): display nodes tab for not db entities

---

src/containers/Tenant/QueryEditor/QueryExplain/QueryExplain.js

`explain-ast` request is sent every time we open AST tab for explain response with lacking `ast`. But if we open AST and then run explain, which returns no `ast`, the tab will be empty and no additional request for `explain-ast` will be sent. This PR fixes it
Part of #361

fix(QueryExplain): request AST if it is empty

---

src/containers/Storage/StorageGroups/StorageGroups.tsx
src/containers/Storage/VDisk/VDisk.tsx
src/containers/Storage/VDiskPopup/VDiskPopup.tsx
src/containers/Storage/utils/types.ts
src/store/reducers/node.js
src/store/reducers/storage.js

Add StoragePool name to VDisk popup in Storage table in nodes mode (it was present in data, but was not displayed).
Add StoragePool name to VDisk popup in Node structure (it was not present in data).

fix: display storage pool in VDisks popups

---

src/containers/Tablet/Tablet.scss
src/containers/Tablet/TabletTable/TabletTable.tsx
src/store/reducers/nodesList.ts
src/store/reducers/tablet.ts
src/types/store/tablet.ts
src/utils/nodes.ts

Add FQDN column with copy button to history table on Tablet page. Make NodeId in the table a link

feat(Tablet): display node fqdn in table

---

src/services/api.ts

With `axios` options set as `null`, wrong headers are set, that causes an error: `{"error":"Invalid Content-Type"}`. Replace nulls with empty objects to fix it

fix(api): change nulls to empty objects

---

src/containers/Tenant/Diagnostics/Partitions/Headers/Headers.tsx
src/containers/Tenant/Diagnostics/Partitions/Partitions.scss
src/containers/Tenant/Diagnostics/Partitions/Partitions.tsx
src/containers/Tenant/Diagnostics/Partitions/PartitionsControls/PartitionsControls.tsx
src/containers/Tenant/Diagnostics/Partitions/i18n/en.json
src/containers/Tenant/Diagnostics/Partitions/i18n/ru.json
src/store/reducers/partitions/partitions.ts
src/store/reducers/partitions/types.ts

`Select` with ability to unselect by clicking on the selected option occurred to be not clear for the users. Added explicit "No consumer" option to `Select`

Fix partitions tab

---

src/components/TabletsStatistic/TabletsStatistic.tsx
src/containers/Tenants/Tenants.js

Breadcrumbs will be updated as part of navigation update. They will be following:
* Tablets page: Cluster / Tenant / Tablets
* Tablet page: Cluster / Tenant / Tablets / Tablet
The problem here is in the custom backend for every tenant. To have it on Tablets and Tablet page and to enable navigation to tenants via breadcrumbs I set tenant backend when going from tenants table to Tablets page.
For other scenarios we left backend as it was before.

fix(TabletsStatistic): use tenant backend

---

src/containers/Tenant/Diagnostics/DetailedOverview/DetailedOverview.scss
src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.scss
src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.tsx

Prevent scroll bar in the middle of Info tab

fix(DetailedOverview): prevent tenant info scroll on overflow

---

src/containers/Storage/StorageGroups/StorageGroups.tsx

`Degraded` - display `Degraded` (`Missing`) column
`Space` - display `Space` (`UsedSpaceFlag`) column
`All` - don't display `Degraded` and `Space` columns
In `All` mode sort by `poolName`

fix(Storage): update columns

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.js
src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx
src/store/reducers/executeQuery.ts
src/store/reducers/explainQuery.ts
src/store/reducers/settings/settings.ts
src/types/store/query.ts
src/utils/constants.ts
src/utils/query.ts

- Color last used query action (`Run` or `Explain`) 
- Run highlighted action with Ctrl / Cmd + Enter

fix(QueryEditor): color last used query action, run on command

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx

When `Loader` isn't wrapped with `div`, `SplitPane` cannot properly calculate panes sizes.
Issue occurred after #481, where all excessive `div` was deleted

fix(ObjectSummary): fix wrong tree alignment bug

---

src/containers/UserSettings/Setting.tsx
src/containers/UserSettings/i18n/en.json
src/containers/UserSettings/i18n/ru.json
src/containers/UserSettings/settings.ts
src/store/reducers/settings/settings.ts
src/utils/constants.ts
src/utils/i18n/i18n.ts
src/utils/settings.ts

Add language setting.
Currently the setting is turned off as there are not enough translations in the UI.
The setting may be manually turned on to simplify development process.

feat: add language setting

---

src/services/api.ts

In the latest update default HC behaviour was change. To keep HC as it was before, `merge_request=true` param is needed

fix(Healthcheck): add merge_records request param

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Tenant.tsx

Fix the bug with not fully collapsed navigation tree. Steps:
1) Collapse navigation tree
2) Go to other page (Cluster, Node, Tablet, etc.)
3) Return to Tenant page
This happened because data was not updated properly

fix(Tenant): fix tree not fully collapsed bug

---

src/containers/Storage/Storage.tsx

Nodes table in Node Storage has no much sense. So it won't be available

feat(Storage): hide nodes table for node page

---

package-lock.json
package.json
src/components/CellWithPopover/CellWithPopover.scss
src/components/CellWithPopover/CellWithPopover.tsx
src/components/NodeHostWrapper/NodeHostWrapper.scss
src/components/NodeHostWrapper/NodeHostWrapper.tsx
src/containers/Nodes/getNodesColumns.tsx
src/containers/Storage/StorageGroups/StorageGroups.scss
src/containers/Storage/StorageGroups/getStorageGroupsColumns.tsx

fix: fix incorrect truncate strings with popover

---

src/containers/Tenant/Diagnostics/TopQueries/TopQueries.scss

fix: fix diagnostics top queries width

---

src/store/reducers/storage/storage.ts

In latest ydb version default storage flag in `/nodes` endpoint was set to `false`. Because of this `PDisks` disappear. To prevent it, flag is explicitly set to `true`

fix(Storage): set storage true for nodes

---

src/containers/Node/Node.tsx
src/containers/Node/NodeStructure/NodeStructure.tsx
src/containers/Node/NodeStructure/Pdisk.tsx
src/containers/Node/i18n/en.json
src/containers/Node/i18n/index.ts
src/containers/Node/i18n/ru.json
src/utils/developerUI.ts

Update links to PDIsk and VDisk DeveloperUI. They are no longer uses external logic and are always present. 
Links are formed based on current backend (node host with embedded-ui), they use clusters nodes ability to connect with each other. 
```{backend}/node/{tagetNodeId}/path```

fix: update links to VDisk and PDisk Developer UI

---

src/containers/Nodes/Nodes.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/UserSettings/i18n/en.json
src/containers/UserSettings/i18n/ru.json
src/store/reducers/nodes/nodes.ts
src/store/reducers/nodes/types.ts
src/store/reducers/settings/settings.ts

1. Disable `useNodesEndpointInDiagnostics` flag by default
2. Explicitly set `storage=false` flag for nodes request (it's implicitly set by default)
3. Use `/nodes` instead of `/compute` for not DB entities in Diagnostics
4. Request entities nodes by `path` param instead of `tenant`

fix(Nodes): always use nodes when flag is enabled

---

src/store/reducers/settings/settings.ts

Turn on "Enable additional query modes" and "Display metrics cards for database diagnostics" experiments by default.

fix: turn on query modes and metrics cards by default

---

src/containers/Nodes/getNodesColumns.tsx
src/store/reducers/nodes/types.ts
src/store/reducers/nodes/utils.ts
src/types/api/nodes.ts

Add columns `Tablet Cache`, `Query Runtime` and `Sessions`
Example 1 (version before tablet cache and sessions were added to response)
Example 2 (current version, but with small usage)

feat(TenantOverview): add columns to memory table

---

src/services/api.ts
src/store/reducers/settings/settings.ts
src/utils/settings.ts

If no `settingsApi` is provided, app should always use `localStorage`

feat: always use localStorage if no settingsApi

---

src/containers/App/Content.js
src/containers/AsideNavigation/AsideNavigation.tsx
src/containers/Tenant/Diagnostics/Partitions/Partitions.tsx
src/containers/Tenant/Query/QueryEditor/QueryEditor.js
src/services/api.ts
src/services/settings.ts
src/store/reducers/executeQuery.ts
src/store/reducers/settings/settings.ts
src/store/reducers/settings/types.ts
src/types/window.d.ts
src/utils/hooks/useSetting.ts
src/utils/i18n/i18n.ts
src/utils/settings.ts

If some external storage was used before, all user settings should migrate to localStorage, when user enters the page.

feat: migrate from external settings api

---

src/services/settings.ts
src/store/reducers/settings/settings.ts
src/store/reducers/settings/types.ts

Make possible to extract and set settings manually (not only when reducer inited), so it will be possible to set specific additional settings in internal version

fix: enable extract and set user settings manually

---

.github/workflows/release.yml

Also:
- refactor to stop using `yandex-cloud/ui-release-action` action;
- add `embedded_ui_refresh` event dispatch.

ci: add Embedded UI build to releases

---

.github/workflows/publication.yml
.github/workflows/release.yml

Now publishing to NPM and triggering the refresh action are separated from the release creation workflow.

ci: split Release and Publication workflows

---

.github/workflows/release.yml

Based on https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md.

chore: add last release SHA

---

src/components/MetricChart/convertReponse.ts
src/components/MetricChart/getDefaultDataFormatter.ts
src/components/MetricChart/types.ts
src/utils/constants.ts

Decided no to connect null datapoints, so intervals, where data was not collected, will be explicitly shown
Before:
After:

fix(MetricChart): do not convert nulls

---

src/components/VirtualTable/VirtualTable.tsx

Updated `VirtualTable` could be seen here: https://nda.ya.ru/t/se1OYEka74Uxro
Ensure that experiment "Use table with data load on scroll for Nodes and Storage cluster tabs" is turned on before reviewing this table

fix(VirtualTable): optimise requests

---

.github/workflows/publication.yml
package.json

* ci: fix build asset packing
Before `embedded-ui.zip` release asset was unpacked as `tmp/embedded-ui` instead of just `embedded-ui`.
* build: disable sourcemap generation for Embedded UI build
It seems to me that it is more correct to build a fully ready release, rather than removing `*.map` during placing files in `ydb`.

chore: Embedded UI release fix

---

src/components/VirtualTable/useIntersectionObserver.ts
src/containers/Node/Node.tsx
src/containers/Nodes/NodesWrapper.tsx
src/containers/Nodes/VirtualNodes.tsx
src/containers/Tenant/Diagnostics/Diagnostics.scss
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/UserSettings/i18n/en.json
src/containers/UserSettings/i18n/ru.json

`VirtualTable` now is used for Node pages and Diagnostics Nodes and Storage tab (previously it was used only for Cluster tabs)
Updated UI can be reviewed here: https://nda.ya.ru/t/zALAQfCs74VVEv
Ensure that experiment "Use table with data load on scroll for Nodes and Storage tabs" is turned on before reviewing this table

feat: use VirtualTable in Nodes and Diagnostics

---

src/components/CellWithPopover/CellWithPopover.scss
src/components/VirtualTable/TableHead.tsx
src/components/VirtualTable/TableRow.tsx
src/components/VirtualTable/VirtualTable.scss
src/components/VirtualTable/VirtualTable.tsx
src/components/VirtualTable/types.ts
src/containers/Nodes/VirtualNodes.tsx
src/containers/Nodes/getNodesColumns.tsx
src/utils/hooks/useTableResize.ts

Add resize for "Version" column in Nodes table - little native resize triangle near right bottom corner.
The table could be reviewed in UI here: https://nda.ya.ru/t/aL9co3Y674WeyY
To enable `VirtualTable` turn on "Use table with data load on scroll for Nodes and Storage tabs " experiment in settings.

feat(VirtualTable): enable columns resize

---

src/components/BasicNodeViewer/BasicNodeViewer.tsx
src/components/FullNodeViewer/FullNodeViewer.tsx
src/containers/Node/Node.tsx
src/containers/Nodes/getNodesColumns.tsx
src/containers/Storage/StorageNodes/getStorageNodesColumns.tsx
src/store/reducers/node/node.ts
src/store/reducers/node/selectors.ts
src/store/reducers/node/types.ts
src/store/reducers/node/utils.ts
src/store/reducers/nodes/types.ts
src/store/reducers/nodes/utils.ts
src/store/reducers/storage/types.ts
src/store/reducers/storage/utils.ts

In raw data we have `DataCenter` field. However, in code we reference it as `DC`, also backend sort works only with field short name. So replaced `DataCenter` field with `DC` everywhere, use `DataCenter` and `Rack` from node `Location` field, where it's possible (it's not present in `/viewer/json/compute` endpoint)
`DC` and `Rack` should appear in Node page, in Nodes and Storage tables, also sort by DC in Nodes and Storage tables now should work properly (experiment "Use table with data load on scroll for Nodes and Storage tabs" should be turned off).
Node page:
Nodes table:
Node to test UI: https://nda.ya.ru/t/se1OYEka74Uxro

fix: use DC and Rack from Location for nodes

---

src/containers/Tenant/Diagnostics/TopQueries/getTopQueriesColumns.tsx
src/store/reducers/executeTopQueries/executeTopQueries.ts
src/utils/diagnostics.ts

feat: add Duration column to TopQueries

---

src/containers/App/Content.tsx
src/containers/Cluster/Cluster.scss
src/containers/Cluster/Cluster.tsx
src/containers/Cluster/ClusterInfo/ClusterInfo.scss
src/containers/Cluster/ClusterInfo/ClusterInfo.tsx
src/containers/Cluster/utils.tsx
src/containers/Clusters/columns.tsx
src/containers/Node/Node.tsx
src/routes.ts
src/services/settings.ts
src/store/reducers/cluster/cluster.ts
src/store/reducers/cluster/types.ts
src/utils/constants.ts

feat: move cluster info to overview tab

---

src/containers/Tenant/Query/utils/getPreparedResult.ts

fix(ExecuteResults): escape values in table cells when copy as tsv

---

src/utils/monitoring.ts

We have monitoring data in different format, `console.log` with error for dozens of databases looks quite annoying

fix: remove console log on monitoring data parsing error

---

src/store/reducers/executeTopQueries/utils.ts

Test stand: https://nda.ya.ru/t/h3ivZEO074jcAL
Currently we use `IntervalEnd` for `TopQueries` filters, but in the table we use `EndTime`. These values are different, so filters could work unexpectedly.
For example, I set filter from 11.00 to 12.30. Queries, that was ended in 12.10 and 12.15 won't be displayed, because they have `IntervalEnd` 13.00
Before: 
Now:

fix(TopQueries): use EndTime

---

src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricCard/MetricCard.tsx
src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricsCards.tsx
src/containers/Tenant/Diagnostics/TenantOverview/i18n/en.json
src/store/reducers/tenants/utils.ts
src/types/api/nodes.ts

Test stand: https://nda.ya.ru/t/HR25d4Hp74oDd9
Although we didn't agree how to show CPU card properly, these small fixes could help to improve current view

fix: update tenant cpu

---

src/components/MetricChart/MetricChart.tsx
src/components/MetricChart/getChartData.ts
src/containers/Tenant/Diagnostics/TenantOverview/DefaultOverviewContent/DefaultOverviewContent.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TenantCpu.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantDashboard/TenantDashboard.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TenantMemory.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TenantStorage.tsx
src/services/api.ts
src/types/api/render.ts

Test stand: https://nda.ya.ru/t/yeplVdn_74tpFU

feat(MetricChart): make charts database specific

---

src/components/ButtonWithConfirmDialog/ButtonWithConfirmDialog.tsx
src/containers/PDisk/PDisk.scss
src/containers/PDisk/PDisk.tsx
src/containers/PDisk/i18n/en.json
src/services/api.ts

Closes [#761](https://github.com/ydb-platform/ydb-embedded-ui/issues/761)

feat(PDisk): add restart button

---

src/containers/Storage/StorageGroups/getStorageGroupsColumns.tsx
src/store/reducers/pdisk/utils.ts
src/store/reducers/storage/types.ts
src/store/reducers/storage/utils.ts
src/types/api/storage.ts
src/utils/storage.ts

fix(Storage): use media type for groups

---

src/components/CriticalActionDialog/CriticalActionDialog.scss
src/containers/PDiskPage/PDiskPage.tsx
src/services/api.ts
src/types/api/restartPDisk.ts

Fixes #820
How to test - try to restart PDisks with id 1001 on different nodes.
monitoring/pDisk?nodeId=1&pDiskId=1001
monitoring/pDisk?nodeId=2&pDiskId=1001
On the third PDisk it should return error
Test stand: https://nda.ya.ru/t/23_-Vw3t75tawa

fix(PDiskPage): explicit error on failed restart

---

src/components/EntityStatus/EntityStatus.scss
src/containers/App/App.scss

Copy button didn't hide after copy. Made it be shown only on hover
Test stand: https://nda.ya.ru/t/01pCgQBZ763DPX

fix: fix copy button not hidden after copy

---

package-lock.json
package.json

There is a warning in `@gravity-ui/components`. In CI warnings are considered as errors, so project doesn't build successfully. Temporarily downgraded components, until warning is fixed, since we do not use features, added with recent updates

fix: @gravity-ui/components -> 3.4.1

---

src/store/reducers/tenants/utils.ts

Prevent the case, when limit is set, but since the metric is `undefined`, it is displayed as "no data" (sometimes backend doesn't return 0 values)
Before:
After:

fix: set 0 for tenant metrics if consumption undefined

---

.github/workflows/ci.yml
README.md

Closes #875
Currently we use old ydb image (it was updated more that a year ago). I suggest switch to trunk version. 
Pros: we will be able to test all latest features. Cons: sometimes trunk image is broken

ci: use ydb trunk image for e2e

---

src/containers/App/App.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.scss
src/styles/mixins.scss

Closes #886
Test stand: https://nda.ya.ru/t/yQN0U4t776LxxG

fix(AsyncReplication): fix table styles

---

commitlint.config.js

Prevent text-overflow in PRs headers and changelog. Config-conventional length is 100, I set it to 72 - the length, that GH can process. 
Problem example:

chore: limit commit header length

---

src/containers/Tenant/TenantNavigation/TenantNavigation.tsx

fix(TenantNavigation): fix radio button value

---

src/containers/AppWithClusters/AppWithClusters.tsx
src/containers/UserSettings/Setting.tsx
src/containers/UserSettings/UserSettings.scss
src/containers/UserSettings/UserSettings.tsx
src/containers/UserSettings/i18n/en.json
src/containers/UserSettings/settings.tsx

fix(UserSettings): fix highlight on search

---

src/components/FullNodeViewer/FullNodeViewer.tsx
src/containers/Nodes/getNodesColumns.tsx
src/containers/Versions/NodesTable/NodesTable.tsx
src/store/reducers/clusterNodes/clusterNodes.tsx
src/store/reducers/nodes/types.ts
src/store/reducers/nodes/utils.ts
src/utils/nodes.ts

Closes #963 
`LoadAverage` contains absolute values, but everywhere we use them as percents. Made them really percents

fix: fix node LoadAverage calculation

---

src/components/Errors/ResponseError/ResponseError.tsx
src/containers/Tenant/Schema/CreateDirectoryDialog/CreateDirectoryDialog.scss
src/containers/Tenant/Schema/CreateDirectoryDialog/CreateDirectoryDialog.tsx
src/containers/Tenant/Schema/SchemaTree/SchemaTree.scss
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/i18n/en.json
src/containers/Tenant/utils/schemaActions.ts
src/services/api.ts
src/store/reducers/schema/schema.ts

feat: add creating directory through context menu in navigation tree

---

src/containers/Header/Header.tsx

Fix bug `Error: A state mutation was detected between dispatches, in the path 'header.pageBreadcrumbsOptions.clusterName'` when going from all clusters page to cluster page

fix(Header): fix state mutation

---

src/store/reducers/storage/storage.ts

Do not request tablets in `Storage` table - they are not displayed anyway. Goal - to reduce response size and increase performance

fix(Storage): do not request tablets for nodes

---

src/containers/Tenant/Diagnostics/HotKeys/HotKeys.tsx
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/schema/schema.ts

fix(schema): use one cache entree for tenant path schemas

---

src/components/PDiskInfo/PDiskInfo.scss
src/components/PDiskInfo/PDiskInfo.tsx
src/components/PDiskInfo/i18n/en.json
src/store/reducers/pdisk/utils.ts
src/utils/disks/prepareDisks.ts
src/utils/disks/types.ts

feat(PDiskPage): add pdisk attributes, display in 2 columns

---

src/services/api.ts
src/store/reducers/executeTopQueries/executeTopQueries.ts
src/store/reducers/explainQuery/explainQuery.ts
src/store/reducers/preview.ts
src/store/reducers/shardsWorkload/shardsWorkload.ts
src/store/reducers/tenantOverview/executeTopTables/executeTopTables.ts
src/store/reducers/tenantOverview/topShards/tenantOverviewTopShards.ts
src/store/reducers/viewSchema/viewSchema.ts

Closes #1047
Disabled retries for:
- `sendQuery`, if it was initiated by user
- `evictVDisk`
- `restartPDisk`
- `killTablet`
- `stopTablet`
- `resumeTablet`
When node is broken, requests fail with `ERR_CONNECTION_RESET` or `ERR_CONNECTION_REFUSED`. It produces `AxiosError` in format 
```
{
code: "ERR_NETWORK”,
message: “Network Error”,
name: “"AxiosError”
}
```
The node could be broken by bad queries, but these queries are considered network error in `axios-retry` and retried, but they should not.

fix: do not retry requests by user

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/utils/constants.ts
src/utils/hooks/index.ts
src/utils/hooks/useEventHandler.ts

**Status**: <span style="color: green; font-weight: bold;">✅ PASSED</span>
| Total | Passed | Failed | Skipped |
|-------|--------|--------|---------|
| 38 | 38 | 0 | 0 |
For detailed results, please check the [Playwright Report](https://ydb-platform.github.io/ydb-embedded-ui/1107/)
Video recordings of failed tests (if any) are available in the report.
---
<details>
<summary>ℹ️ How to use this report</summary>
1. Click on the "Playwright Report" link above to view the full test results.
2. In the report, you can see a breakdown of all tests, including any failures.
3. For failed tests, you can view screenshots and video recordings to help debug the issues.
4. Use the filters in the report to focus on specific test statuses or suites.
</details>
📊 [Full …

refactor(QueryEditor): get rid of some misused useEffects

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx
tests/suites/tenant/queryEditor/QueryEditor.ts
tests/suites/tenant/queryHistory/queryHistory.test.ts
tests/suites/tenant/queryHistory/utils.ts

Looks like saving queries to history is broken
because handleExecute recieves react event as argument
made calling these functions explicit
added tests
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1111/)
Current: 78.85 MB | Main: 78.85 MB
Diff: +0.24 KB (0.00%)
<details>
</details>

fix(QueryHistory): query history not saving

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/ObjectSummary/__test__/transformPath.test.ts
src/containers/Tenant/ObjectSummary/transformPath.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1006
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1118/)
<details>
</details>

feat: display relative schema object path on left overview tab

---

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.scss
src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/services/api.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1119/)
Diff: +0.15 KB (0.00%)
<details>
</details>

fix: schema in sendQuery is only query parameter

---

playwright.config.ts
src/playwrightSetup.ts

to reduce number of flaky tests
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1122/)
<details>
</details>

feat(e2e): add warmup for e2e

---

src/playwrightSetup.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1123/)
<details>
</details>

fix(e2e): use baseurl from config

---

src/containers/Tenant/Query/ExplainResult/components/SimplifiedPlan/OperationCell.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1124/)
<details>
</details>

fix(SimplifiedPlan): should hide dividers if item is collapsed

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
tests/suites/tenant/queryEditor/QueryEditor.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1131
[Stand ](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1132/)
| 70 | 65 | 0 | 5 | 0 |
Current: 78.88 MB | Main: 78.88 MB
<details>
- 🔺 …

fix: completed query status on page load

---

src/components/VDiskInfo/VDiskInfo.tsx

Do not show developer UI link to users with viewer rights similar to PDisk page
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1137/)
| 70 | 68 | 0 | 2 | 0 |
Current: 78.89 MB | Main: 78.88 MB
<details>
</details>

fix(VDiskInfo): hide developer ui link for users with viewer rights

---

src/components/CriticalActionDialog/CriticalActionDialog.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1149/)
| 70 | 70 | 0 | 0 | 0 |
Current: 78.89 MB | Main: 78.89 MB
<details>
</details>

fix(CriticalActionDialog): increase padding-top

---

src/containers/Nodes/getNodes.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TopNodesByMemory.tsx
src/services/api.ts
src/store/reducers/nodes/nodes.ts
src/store/reducers/storage/storage.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1148/)
| 70 | 70 | 0 | 0 | 0 |
Current: 78.89 MB | Main: 78.89 MB
<details>
</details>

fix: remove tablets from some api handlers

---

src/components/Errors/PageError/PageError.tsx
src/containers/App/Content.tsx
src/containers/Tenant/Tenant.tsx

Closes #1140 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1150/)
| 70 | 68 | 0 | 2 | 0 |
Current: 78.90 MB | Main: 78.89 MB
<details>
</details>

fix: don't show data for un auth user

---

src/containers/Tenant/Acl/Acl.scss
src/containers/Tenant/Acl/Acl.tsx
src/containers/Tenant/Acl/i18n/en.json
src/store/reducers/schemaAcl/schemaAcl.ts
src/types/api/acl.ts

closes #1151 #1133
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1154/)
| 70 | 70 | 0 | 0 | 0 |
<details>
</details>

feat(Acl): support InterruptInheritance, fix styles

---

src/services/api.ts

Base64 doesn't work on ydb before 24-3
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1172/)
| 78 | 78 | 0 | 0 | 0 |
<details>
</details>

fix: base64 flag both in sendQuery params and body

---

src/containers/Tenant/Diagnostics/Overview/TableInfo/prepareTableInfo.tsx
src/containers/Tenant/utils/queryTemplates.ts
src/types/api/schema/table.ts

Resolves #1080
Also removed bloom filter enable from default create table

feat(diagnostics): render bloom filter better

---

.husky/commit-msg

There is no check in CI, it seems there is no need for local check as well
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1181/)
| 108 | 107 | 0 | 1 | 0 |
<details>
</details>

chore: remove local commit message check

---

src/.eslintrc
src/components/ElapsedTime/ElapsedTime.tsx
src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.tsx
src/containers/Tenant/Query/utils/useSavedQueries.tsx
src/index.tsx
src/store/reducers/tenants/selectors.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1182/)
| 108 | 104 | 0 | 4 | 0 |
<details>
</details>

refactor: use direct imports instead of lib imports

---

src/containers/PDiskPage/PDiskGroups/PDiskGroups.tsx
src/containers/Storage/StorageGroups/getStorageGroupsColumns.tsx
src/containers/VDiskPage/VDiskPage.scss
src/containers/VDiskPage/VDiskPage.tsx
src/store/reducers/vdisk/types.ts

Closes #1126
Default storage table for the page to simplify further implementation of storage changes, including advanced storage
Before:
After: 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1209/)
| 120 | 113 | 0 | 7 | 0 |
Current: 78.83 MB | Main: 78.87 MB
Diff: 0.04 MB (-0.05%)
<details>
</details>

feat(VDiskPage): use storage table instead of storage info

---

src/containers/UserSettings/i18n/en.json
src/containers/UserSettings/settings.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1180/)
| 120 | 117 | 0 | 3 | 0 |
Current: 78.83 MB | Main: 78.83 MB
<details>
</details>

fix: remove binary data setting description

---

src/containers/Cluster/ClusterInfo/ClusterInfo.tsx
src/store/reducers/nodes/types.ts
src/store/reducers/nodes/utils.ts
src/types/api/nodes.ts
src/utils/versions/parseNodesToVersionsValues.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1230/)
| 124 | 121 | 0 | 3 | 0 |
Current: 78.83 MB | Main: 78.83 MB
<details>
</details>

fix(Overview): use nodes?group=Version to get node versions

---

src/components/PaginatedTable/PaginatedTable.scss
src/components/PaginatedTable/TableChunk.tsx
src/components/PaginatedTable/TableHead.tsx

The problem was that Safari is not applying height to tbody by default
it can be achieved by making display: block on tbody (and display: table on header for it to still be header)
https://stackoverflow.com/a/23989771
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1223
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1231/)
Current: 78.84 MB | Main: 78.83 MB
Diff: +0.90 KB (0.00%)
<details> …

fix: paginated tables not working in safari

---

src/components/PaginatedTable/PaginatedTable.scss
src/components/PaginatedTable/TableHead.tsx

1 part of #1236 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1237/)
Current: 78.84 MB | Main: 78.84 MB
Diff: +0.38 KB (0.00%)
<details>
</details>

fix(PaginatedTable): fix layout

---

src/containers/AppWithClusters/ExtendedNode/ExtendedNode.tsx
src/containers/AppWithClusters/ExtendedTenant/ExtendedTenant.tsx
src/containers/AppWithClusters/useClusterData.ts
src/containers/Header/Header.tsx
src/containers/Tenant/Query/ExecuteResult/ExecuteResult.scss
src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/containers/Tenant/Query/ExecuteResult/TraceButton.tsx
src/services/api.ts
src/services/parsers/parseMetaCluster.ts
src/store/reducers/cluster/cluster.ts
src/store/reducers/trace.ts
src/types/api/trace.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1251/)
Current: 78.92 MB | Main: 78.91 MB
<details>
</details>

feat: use /db_clusters to get base cluster info

---

src/containers/PDiskPage/PDiskGroups/PDiskGroups.tsx
src/containers/Storage/Storage.tsx
src/containers/Storage/StorageGroups/PaginatedStorageGroups.tsx
src/containers/Storage/StorageGroups/getGroups.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopGroups.tsx
src/containers/VDiskPage/VDiskPage.tsx
src/services/api.ts
src/store/reducers/capabilities/hooks.ts
src/store/reducers/storage/requestStorageData.ts
src/store/reducers/storage/storage.ts

Closes #1160 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1225/)
Current: 78.87 MB | Main: 78.86 MB
<details>
</details>

feat: use groups handler for storage

---

config-overrides.js
package-lock.json
package.json

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1298/)
Current: 78.81 MB | Main: 78.81 MB
Diff: +0.28 KB (0.00%)
<details>
</details>

chore(build): ignore order of css files

---

src/components/CriticalActionDialog/CriticalActionDialog.tsx
src/components/CriticalActionDialog/i18n/en.json
src/containers/PDiskPage/DecommissionButton/DecommissionButton.tsx

Closes #1207
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1294/)
| 124 | 117 | 1 | 6 | 0 |
Current: 78.85 MB | Main: 78.81 MB
Diff: +0.04 MB (0.05%)
<details>
</details>

fix(DecommissionButton): add checkbox to dialog

---

src/services/api.ts
src/store/reducers/cluster/utils.ts
src/store/reducers/executeQuery.ts
src/store/reducers/explainQuery/utils.ts
src/store/reducers/viewSchema/viewSchema.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1304/)
| 124 | 118 | 1 | 5 | 0 |
Current: 78.85 MB | Main: 78.85 MB
<details>
</details>

fix(queries): do not fail on response with 200 code and null body

---

src/services/api.ts
src/types/api/meta.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1314/)
| 124 | 119 | 0 | 5 | 0 |
Current: 78.96 MB | Main: 78.96 MB
Diff: +0.07 KB (0.00%)
<details>
</details>

fix(api): correctly get cluster info from data (/meta/db_clusters)

---

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.scss
src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/containers/Tenant/Query/ExecuteResult/i18n/en.json
src/types/api/query.ts
src/types/store/query.ts
src/utils/query.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1276
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1309/)
Current: 78.96 MB | Main: 78.96 MB
<details>
- 🔺 …

feat: in query results show when it was truncated

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1326/)
| 124 | 119 | 1 | 4 | 0 |
Current: 78.99 MB | Main: 78.99 MB
Diff: +0.70 KB (0.00%)
<details>
</details>

feat(ObjectSummary): add paths and shards limits

---

src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/ObjectSummary/ObjectSummary.scss
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/ObjectSummary/ObjectTree.tsx
src/containers/Tenant/ObjectSummary/SchemaActions.tsx
src/containers/Tenant/ObjectSummary/i18n/en.json
src/containers/Tenant/ObjectSummary/i18n/index.ts
src/containers/Tenant/ObjectSummary/shared.ts
src/containers/Tenant/utils/schema.ts
tests/suites/tenant/summary/ObjectSummary.ts

closes #1303 
[Stand](https://nda.ya.ru/t/U4YSiwn778NMtu)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1323/)
Current: 79.00 MB | Main: 78.99 MB
<details>
</details>

feat(ObjectSummary): add link to Schema in Diagnostics

---

.github/workflows/ci.yml
.github/workflows/pr-title.yml

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1355/)
<details>
</details>

ci: add merge group to ci triggers

---

src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/StorageGroups/columns/constants.ts

Closes #1337
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1351/)
<details>
</details>

fix(StorageGroups): make group id first column

---

src/components/PDiskInfo/PDiskInfo.tsx
src/components/VDiskInfo/VDiskInfo.tsx
src/containers/Node/Node.tsx
src/containers/Node/NodePages.ts
src/containers/PDiskPage/PDiskPage.tsx
src/containers/VDiskPage/VDiskPage.tsx
src/services/api.ts
src/store/reducers/capabilities/capabilities.ts
src/store/reducers/pdisk/pdisk.ts
src/store/reducers/pdisk/utils.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1338/)
Current: 79.05 MB | Main: 79.00 MB
Diff: +0.06 MB (0.07%)
<details>
</details>

fix: show structure tab and PDisk/VDisk if disk's new API is absent

---

src/containers/Tenant/Diagnostics/DiagnosticsPages.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1356/)
Diff: 0.08 KB (-0.00%)
<details>
</details>

fix(Diagnostics): hide graph for column tables

---

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/containers/Tenant/Query/ExecuteResult/i18n/en.json

closes #1328 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1368/)
<details>
</details>

feat(ExecuteResult): add row count for all results

---

src/containers/Storage/PaginatedStorage.tsx
src/containers/Storage/PaginatedStorageGroups.tsx
src/containers/Storage/PaginatedStorageNodes.tsx
src/containers/Storage/Storage.tsx
src/containers/Storage/StorageGroups/PaginatedStorageGroupsTable.tsx
src/containers/Storage/StorageGroups/getGroups.ts
src/containers/Storage/StorageNodes/PaginatedStorageNodesTable.tsx
src/containers/Storage/StorageNodes/getNodes.ts
src/store/reducers/storage/types.ts

Closes #1380 
If `PaginatedStorage` enabled, Storage tab on Node page show cluster nodes, while it should show only one node
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1382/)
<details>
</details>

fix(PaginatedStorage): properly pass ids, display 1 node on Node page

---

src/components/QueryResultTable/QueryResultTable.tsx
src/components/QueryResultTable/utils/getColumnWidth.test.ts
src/components/QueryResultTable/utils/getColumnWidth.ts
src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/utils/query.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1340
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1386
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1387
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=query&queryTab=newQuery&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065&schema=%2Fdev02%2F.sys%2Fds_vslots)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1384/)
| 124 | 123 | 0 | 1 | 0 |
<details>
<summary>ℹ️ CI …

fix: fix columns width on long rowset

---

src/components/StorageGroupInfo/StorageGroupInfo.tsx
src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/StorageGroups/columns/constants.ts
src/containers/Storage/StorageGroups/columns/i18n/en.json
src/store/reducers/storage/types.ts
src/store/reducers/storage/utils.ts
src/types/api/storage.ts
src/utils/storage.ts

Closes #1185
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1390/)
Current: 79.14 MB | Main: 79.13 MB
<details>
</details>

feat(StorageGroups): add latency and allocation units columns

---

src/types/api/cluster.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1401/)
Diff: +0.15 KB (0.00%)
<details>
</details>

fix(cluster): infoV2 check

---

config-overrides.js
package-lock.json
package.json

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1406
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1405/)
| 124 | 122 | 0 | 2 | 0 |
Current: 79.31 MB | Main: 79.14 MB
Diff: +0.18 MB (0.22%)
<details>
</details>

fix: autocomplete not working in standalone version

---

src/components/PaginatedTable/TableChunk.tsx
src/containers/PDiskPage/PDiskPage.tsx
src/containers/Storage/Disks/Disks.tsx
src/containers/Storage/PDisk/PDisk.tsx
src/containers/Storage/PaginatedStorage.tsx
src/containers/Storage/PaginatedStorageGroups.tsx
src/containers/Storage/PaginatedStorageNodes.tsx
src/containers/Storage/Storage.tsx
src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/StorageGroups/columns/hooks.ts
src/containers/Storage/StorageGroups/columns/types.ts
src/containers/Storage/StorageNodes/columns/columns.tsx
src/containers/Storage/StorageNodes/columns/hooks.ts
src/containers/Storage/StorageNodes/columns/types.ts
src/containers/Storage/StorageWrapper.tsx
src/containers/Storage/types.ts
src/containers/Storage/utils/index.ts
src/containers/StorageGroupPage/StorageGroupPage.tsx
src/containers/VDiskPage/VDiskPage.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1373
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1397/)
| 124 | 121 | 0 | 3 | 0 |
Current: 79.31 MB | Main: 79.31 MB
Diff: 0.01 MB (-0.01%)
<details>
- 🔺 …

feat: add dimming to vdisk page (nodes) and pdisk page (vdisks)

---

config-overrides.js
package-lock.json
package.json

react-scripts already has babel-loader dependency https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/package.json#L35
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1410
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=query&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1409/)
Current: 79.14 MB | Main: 79.31 MB
Diff: 0.16 MB (-0.21%)
<details>
- Test recordings for failed tests are …

fix: use babel loader from create-react-app

---

src/containers/AppWithClusters/ExtendedCluster/ExtendedCluster.tsx
src/containers/Tenants/Tenants.tsx
src/store/reducers/tenants/types.ts
src/store/reducers/tenants/utils.ts
src/types/additionalProps.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1418/)
| 124 | 122 | 0 | 2 | 0 |
<details>
</details>

feat(Databases): use balancer + /node/:id as backend endpoint

---

src/containers/Storage/StorageGroups/columns/StorageGroupsColumns.scss
src/containers/Storage/StorageGroups/columns/columns.tsx

Closes #1404 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1421/)
| 124 | 121 | 0 | 3 | 0 |
Diff: +0.49 KB (0.00%)
<details>
</details>

fix(StorageGroups): display full pool name with left cut

---

src/containers/Authentication/Authentication.tsx

Closes #1423 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1426/)
| 128 | 127 | 0 | 1 | 0 |
Diff: +0.08 KB (0.00%)
<details>
</details>

fix(Authentication): handle login error properly

---

src/components/VDisk/VDisk.scss
src/components/VDisk/VDisk.tsx
src/components/VDisk/VDiskWithDonorsStack.tsx
src/components/VDisk/utils.ts
src/components/VDiskPopup/VDiskPopup.tsx
src/containers/Storage/Disks/Disks.tsx
src/containers/Storage/PDisk/PDisk.tsx
src/utils/disks/__test__/calculateVDiskSeverity.test.ts
src/utils/disks/calculateVDiskSeverity.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1422/)
| 128 | 127 | 0 | 1 | 0 |
Current: 79.14 MB | Main: 79.13 MB
<details>
</details>

feat(VDisk): show VDisk donors inside popup

---

src/containers/Cluster/Cluster.tsx
src/containers/Cluster/utils.tsx
src/containers/Tablets/Tablets.tsx
src/containers/Tablets/TabletsTable.tsx

[Stand](https://nda.ya.ru/t/Z7VIjCAb78pyzw)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1438/)
| 128 | 128 | 0 | 0 | 0 |
Current: 78.98 MB | Main: 78.96 MB
<details>
</details>

feat(Cluster): add Tablets tab

---

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
tests/suites/tenant/constants.ts
tests/suites/tenant/queryEditor/QueryEditor.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts

closes #1443 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1444/)
Diff: 0.06 KB (-0.00%)
<details>
</details>

fix(ExecuteResult): do not show title if no result

---

src/components/CellWithPopover/CellWithPopover.tsx
src/components/PDiskPopup/PDiskPopup.tsx
src/components/VDisk/VDisk.tsx
src/components/VDiskPopup/VDiskPopup.tsx
src/containers/Storage/PDisk/PDisk.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1360
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/cluster/storage)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1435/)
| 128 | 123 | 0 | 5 | 0 |
<details>
</details>

fix: do not hide pdisk and vdisk popups if mouse on popup content

---

src/containers/Tenant/ObjectSummary/ObjectSummary.scss
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx

closes #1359 
[Stand](https://nda.ya.ru/t/QOhz4nuP78r7Cg)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1447/)
Current: 78.98 MB | Main: 78.98 MB
<details>
</details>

feat(ObjectSummary): improve object overview

---

src/containers/Header/breadcrumbs.tsx
src/containers/Tablet/Tablet.tsx
src/containers/Tablets/TabletsTable.tsx
src/services/api.ts
src/store/reducers/header/types.ts
src/store/reducers/tablet.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1461/)
Diff: 0.01 MB (-0.01%)
<details>
</details>

fix(Tablet): remove nodeId from header and api requests for tablet

---

src/containers/Tenant/Diagnostics/TopQueries/RunningQueriesData.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueriesData.tsx
src/containers/Tenant/Diagnostics/TopQueries/i18n/en.json
src/store/reducers/executeTopQueries/executeTopQueries.ts
src/store/reducers/executeTopQueries/utils.ts
tests/suites/tenant/diagnostics/Diagnostics.ts
tests/suites/tenant/diagnostics/diagnostics.test.ts

Added mixed search by query text and userSID
[Demo](http://ydb-vla-dev02-001.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&selectedConsumer=&name=%2Fdev02%2Fhome%2Fxenoxeno%2Fdb1&queryMode=top)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1462/)
Current: 78.95 MB | Main: 78.96 MB
<details> …

feat(RunningQueries): add userSID search

---

src/containers/Cluster/Cluster.tsx
src/containers/Cluster/VersionsBar/VersionsBar.scss
src/containers/Cluster/VersionsBar/VersionsBar.tsx
src/containers/Versions/Versions.scss
src/containers/Versions/Versions.tsx
src/containers/Versions/i18n/en.json
src/containers/Versions/i18n/index.ts
src/containers/Versions/utils.ts
src/utils/clusterVersionColors.ts
src/utils/versions/getVersionsColors.ts
src/utils/versions/parseNodesToVersionsValues.ts

[Stand](https://nda.ya.ru/t/d8TZTltD78pzs9)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1442/)
Current: 78.97 MB | Main: 78.96 MB
<details>
</details>

feat(Versions): show overall version info in Versions tab

---

src/containers/Tenant/Diagnostics/Describe/Describe.tsx
src/containers/Tenant/Diagnostics/HotKeys/HotKeys.tsx
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/overview/overview.ts
src/store/reducers/schema/schema.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1489/)
Current: 78.94 MB | Main: 78.94 MB
Diff: 0.49 KB (-0.00%)
<details>
</details>

fix: get info about topic children from overview

---

src/containers/Tenant/Query/Preview/Preview.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1503/)
Diff: 0.21 KB (-0.00%)
<details>
</details>

fix(Preview): do not auto refresh table preview

---

src/components/PaginatedTable/TableChunk.tsx
src/components/PaginatedTable/types.ts
src/components/nodesColumns/columns.tsx
src/components/nodesColumns/constants.ts
src/components/nodesColumns/i18n/en.json
src/components/nodesColumns/types.ts
src/containers/Nodes/columns/columns.tsx
src/containers/Nodes/getNodes.ts
src/containers/Storage/StorageGroups/columns/constants.ts
src/containers/Storage/StorageGroups/columns/types.ts
src/containers/Storage/StorageGroups/getGroups.ts
src/containers/Storage/StorageNodes/columns/columns.tsx
src/containers/Storage/StorageNodes/columns/constants.ts
src/containers/Storage/StorageNodes/columns/hooks.ts
src/containers/Storage/StorageNodes/columns/i18n/en.json
src/containers/Storage/StorageNodes/columns/i18n/index.ts
src/containers/Storage/StorageNodes/columns/types.ts
src/containers/Storage/StorageNodes/getNodes.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByLoad.tsx
src/store/reducers/tableData.ts
src/types/api/storage.ts
src/utils/tableUtils/getRequiredDataFields.ts
src/utils/tableUtils/types.ts

Closes #1249 
Stand: https://nda.ya.ru/t/44KfyLRl792MHn
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1491/)
Current: 79.03 MB | Main: 79.02 MB
<details>
</details>

feat(Storage,Nodes): request only needed fields from backend

---

src/components/TableWithControlsLayout/TableWithControlsLayout.scss
src/containers/Cluster/Cluster.scss
src/containers/Cluster/Cluster.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1507/)
Diff: +0.48 KB (0.00%)
<details>
</details>

fix: cluster layout

---

src/containers/UserSettings/UserSettings.tsx
src/containers/UserSettings/settings.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1506
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1508/)
Diff: +0.46 KB (0.00%)
<details>
</details>

fix: remove unneeded titles

---

src/components/HoverPopup/HoverPopup.tsx
src/components/PDiskPopup/PDiskPopup.tsx
src/components/VDiskPopup/VDiskPopup.tsx
src/containers/PDiskPage/PDiskSpaceDistribution/PDiskSpaceDistribution.tsx
src/store/reducers/pdisk/utils.ts

Closes #1434 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1512/)
Diff: +0.00 MB (0.01%)
<details>
</details>

feat: add developer ui links to disks popups

---

src/containers/Storage/Disks/Disks.scss
src/containers/Storage/Disks/Disks.tsx

Closes #1433 
---
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1511/)
<details>
</details>

fix(Storage): display unavailable vdisks with average size

---

src/containers/Storage/Storage.tsx
src/containers/StorageGroupPage/StorageGroupPage.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByCpu.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByLoad.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TopNodesByMemory.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopGroups.tsx
src/services/api.ts
src/utils/tableUtils/getRequiredDataFields.ts

Closes #1485 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1515/)
Current: 79.04 MB | Main: 79.03 MB
<details>
</details>

fix: fields required in all groups and nodes requests

---

src/components/PDiskInfo/PDiskInfo.tsx
src/components/StatusIcon/StatusIcon.scss
src/components/StorageGroupInfo/StorageGroupInfo.tsx
src/components/VDiskInfo/VDiskInfo.tsx
src/containers/Node/NodeStructure/Pdisk.tsx
src/containers/Storage/StorageGroups/columns/columns.tsx

In some places we had `EntityStatus` without `name` prop. Because now it has minimum width, without name it looks weird. Replaced it with `StatusIcon` where it's possible
Before:
After:

fix: replace EntityStatus with StatusIcon where possible

---

src/components/nodesColumns/columns.tsx
src/containers/Clusters/columns.tsx
src/containers/Node/NodeStructure/Pdisk.tsx
src/containers/Versions/NodesTable/NodesTable.tsx

Closes #1520 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1522/)
Current: 79.03 MB | Main: 79.04 MB
<details>
</details>

fix: correct width for columns with ProgressViewer

---

src/containers/Cluster/Cluster.tsx
src/containers/Cluster/ClusterDashboard/ClusterDashboard.scss
src/containers/Cluster/ClusterDashboard/ClusterDashboard.tsx
src/types/api/cluster.ts

closes #1517
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1525/)
Current: 79.04 MB | Main: 79.03 MB
Diff: +0.00 MB (0.01%)
<details>
</details>

fix(Cluster): handle cluster error in meta requests

---

src/components/BasicNodeViewer/BasicNodeViewer.tsx
src/components/NodeHostWrapper/NodeHostWrapper.tsx
src/utils/__test__/prepareBackend.test.ts
src/utils/developerUI/__test__/developerUI.test.ts
src/utils/developerUI/developerUI.ts
src/utils/prepareBackend.ts

Closes #1534 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1537/)
Diff: 0.01 KB (-0.00%)
<details>
</details>

fix: remove excessive slash for requests via tenant node

---

src/components/EntityStatus/EntityStatus.scss
src/components/EntityStatus/EntityStatus.tsx

closes #1536
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1538/)
Diff: +0.30 KB (0.00%)
<details>
</details>

fix(EntityStatus): wrapper layout without clipboard

---

src/containers/Cluster/Cluster.tsx
src/containers/Cluster/ClusterDashboard/ClusterDashboard.tsx
src/store/reducers/capabilities/hooks.ts
src/types/api/capabilities.ts

fix(Cluster): use /capabilities to show dashboard

---

src/components/NodeHostWrapper/NodeHostWrapper.tsx
src/components/Tablet/Tablet.tsx
src/components/TabletNameWrapper/TabletNameWrapper.tsx
src/components/TabletsStatistic/TabletsStatistic.tsx
src/components/TenantNameWrapper/TenantNameWrapper.tsx
src/components/nodesColumns/columns.tsx
src/containers/App/Content.tsx
src/containers/Header/breadcrumbs.tsx
src/containers/Node/Node.tsx
src/containers/Node/NodePages.ts
src/containers/Tablet/Tablet.tsx
src/containers/Tenant/Diagnostics/Consumers/columns/columns.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/Tenant.tsx
src/containers/Tenant/TenantPages.tsx
src/routes.ts
src/services/api.ts
src/store/reducers/capabilities/capabilities.ts
src/store/reducers/capabilities/hooks.ts
src/store/reducers/pdisk/pdisk.ts
tests/suites/tenant/diagnostics/diagnostics.test.ts
tests/suites/tenant/initialLoad.test.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts
tests/suites/tenant/queryHistory/queryHistory.test.ts
tests/suites/tenant/summary/objectSummary.test.ts

Closes #1526
`/viewer/capabilities` is used on several pages and in different components. In order not to pass `database` param every time to hook, I made hook to take `database` param from search query by itself. To make it possible I named param the same way on every page where it's used
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1551/)
Current: 79.11 MB | Main: 79.11 MB
<details>
- 🔺 …

fix: pass database to capabilities query

---

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx
src/containers/Tenant/Query/ExecuteResult/TraceButton.tsx
src/services/api.ts
src/store/reducers/executeQuery.ts
src/store/reducers/trace.ts
src/types/store/executeQuery.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1544
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1555/)
Current: 79.11 MB | Main: 79.11 MB
<details>
</details>

fix: tracing issues

---

src/components/VDiskInfo/VDiskInfo.tsx

fix(VDiskInfo): fix title layout

---

src/containers/Nodes/Nodes.tsx
src/containers/Nodes/PaginatedNodes.tsx
src/containers/Storage/StorageControls/StorageControls.tsx

Closes #1558 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1562/)
Current: 79.12 MB | Main: 79.12 MB
<details>
</details>

fix(Nodes,Storage): reorder controls - prevent moving on count change

---

src/components/TooltipsContent/NodeEndpointsTooltipContent/NodeEndpointsTooltipContent.tsx
src/components/TooltipsContent/NodeEndpointsTooltipContent/i18n/en.json

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1566/)
| 134 | 130 | 0 | 4 | 0 |
Current: 79.19 MB | Main: 79.19 MB
<details>
</details>

feat(NodeEndpointsTooltipContent): add fields

---

src/components/AutoRefreshControl/AutoRefreshControl.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/RefreshTreeButton.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1572/)
Current: 79.20 MB | Main: 79.20 MB
<details>
</details>

fix: refresh schema and autoresresh icons should be similar

---

src/components/NodeHostWrapper/NodeHostWrapper.tsx
src/components/TabletNameWrapper/TabletNameWrapper.tsx
src/components/TenantNameWrapper/TenantNameWrapper.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1573/)
Current: 79.20 MB | Main: 79.20 MB
Diff: +0.28 KB (0.00%)
<details>
</details>

fix: if popover has actions increase delayClosing

---

src/components/PDiskPopup/PDiskPopup.tsx
src/components/VDiskPopup/VDiskPopup.tsx
src/containers/Storage/Disks/Disks.tsx
src/store/reducers/node/selectors.ts
src/store/reducers/node/types.ts
src/store/reducers/pdisk/utils.ts
src/store/reducers/storage/__test__/prepareGroupsDisks.test.ts
src/store/reducers/storage/prepareGroupsDisks.ts
src/store/reducers/storage/utils.ts
src/store/reducers/vdisk/utils.ts
src/types/api/pdisk.ts
src/types/api/storage.ts
src/utils/disks/__test__/calculatePDiskSeverity.test.ts
src/utils/disks/__test__/calculateVDiskSeverity.test.ts
src/utils/disks/__test__/prepareDisks.test.ts
src/utils/disks/calculatePDiskSeverity.ts
src/utils/disks/calculateVDiskSeverity.ts
src/utils/disks/helpers.ts
src/utils/disks/prepareDisks.ts
src/utils/disks/types.ts

Closes #1457, closes #1428, closes #1429
UI should work as before, PR covers cases of DC shutdown
Stand: https://nda.ya.ru/t/dvb-Acis79L6xg
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1564/)
| 134 | 129 | 2 | 3 | 0 |
Current: 79.21 MB | Main: 79.20 MB
<details>
</details>

fix: use both BSC and Whiteboard for disks

---

src/components/TooltipsContent/NodeEndpointsTooltipContent/NodeEndpointsTooltipContent.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1585/)
Current: 79.21 MB | Main: 79.21 MB
Diff: +0.00 KB (0.00%)
<details>
</details>

fix(NodeEndpointsTooltipContent): change fields order

---

package-lock.json
package.json
src/components/TooltipsContent/NodeEndpointsTooltipContent/NodeEndpointsTooltipContent.scss
src/utils/monaco/yql/constants.ts
src/utils/monaco/yql/generateSuggestions.ts
src/utils/monaco/yql/yqlSuggestions.ts

closes #1283
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1599/)
Current: 66.00 MB | Main: 79.23 MB
Diff: 13.23 MB (-16.69%)
<details>
</details>

feat(autocomplete): suggest all columns in a row

---

src/containers/Clusters/Clusters.scss
src/containers/Clusters/Clusters.tsx

closes #1587 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1588/)
Current: 79.21 MB | Main: 79.21 MB
Diff: +0.23 KB (0.00%)
<details>
</details>

fix(Clusters): controls and aggregations layout

---

src/containers/Tenant/utils/schemaActions.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1615/)
Current: 66.02 MB | Main: 66.02 MB
Diff: 0.75 KB (-0.00%)
<details>
</details>

fix(schemaActions): preserve query settings when insert snippet

---

src/components/nodesColumns/columns.tsx
src/components/nodesColumns/constants.ts
src/components/nodesColumns/i18n/en.json
src/containers/Nodes/columns/columns.tsx
src/containers/Nodes/columns/constants.ts
src/containers/Nodes/getNodes.ts
src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/StorageGroups/columns/constants.ts
src/containers/Storage/StorageGroups/getGroups.ts
src/containers/Storage/StorageNodes/columns/columns.tsx
src/containers/Storage/StorageNodes/columns/constants.ts
src/containers/Storage/StorageNodes/getNodes.ts
src/types/api/nodes.ts
src/types/api/storage.ts
src/utils/nodes.ts
src/utils/storage.ts

- Add columns ids to sort fields mapping to enable different columns ids with the same sort fields
- Make group by params titles not connected with columns titles - there won't be a need to define data fields and sort fields for all group by values
- Actualize params lists - add params from nodes v13, add version comments
- Remove not used nodes shared cache column
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1614/)
Current: 66.03 MB | Main: 66.02 MB
<details>
- Bundle size is measured for the entire …

refactor: rework columns group by and sorting

---

package-lock.json
package.json
src/components/ConfirmationDialog/ConfirmationDialog.scss
src/components/ConfirmationDialog/ConfirmationDialog.tsx
src/components/ConfirmationDialog/i18n/en.json
src/components/ConfirmationDialog/i18n/index.ts
src/containers/App/Providers.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopQueries.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Query/NewSQL/NewSQL.tsx
src/containers/Tenant/Query/QueriesHistory/QueriesHistory.tsx
src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/SavedQueries/SavedQueries.tsx
src/containers/Tenant/utils/newSQLQueryActions.ts
src/containers/Tenant/utils/schemaActions.ts
src/store/reducers/executeQuery.ts
src/store/reducers/queryActions/queryActions.ts
src/store/reducers/schema/schema.ts
src/types/store/executeQuery.ts
src/utils/hooks/withConfirmation/i18n/en.json
src/utils/hooks/withConfirmation/i18n/index.ts
src/utils/hooks/withConfirmation/useChangeInputWithConfirmation.ts

[Stand](https://nda.ya.ru/t/UoVjvLhZ79eZCM)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1620/)
Current: 66.06 MB | Main: 66.03 MB
Diff: +0.04 MB (0.06%)
<details>
</details>

feat: warn about unsaved changes in editor

---

.github/workflows/ci.yml
tests/suites/tenant/queryEditor/queryEditor.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1631
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1630/)
| 134 | 129 | 0 | 5 | 0 |
Current: 66.07 MB | Main: 66.07 MB
<details>
</details>

fix: dont remove previous tests reports

---

src/components/ConfirmationDialog/ConfirmationDialog.scss
src/components/ConfirmationDialog/ConfirmationDialog.tsx
src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx
src/containers/Tenant/Query/SaveQuery/SaveQuery.tsx
src/utils/hooks/withConfirmation/i18n/en.json
src/utils/hooks/withConfirmation/useChangeInputWithConfirmation.tsx

[Stand](https://nda.ya.ru/t/4q4ngeXw79g32F)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1629/)
Current: 66.07 MB | Main: 66.07 MB
Diff: 0.53 KB (-0.00%)
<details>
</details>

feat(ConfirmationDialog): add saving query before replace

---

.github/workflows/cleanup-gh-pages.yml
tests/suites/tenant/queryEditor/queryEditor.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1636
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1638/)
| 134 | 130 | 0 | 4 | 0 |
Current: 66.07 MB | Main: 66.07 MB
<details>
</details>

fix: delete directory from gh-pages on pr close

---

src/containers/AsideNavigation/AsideNavigation.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1628/)
Current: 66.07 MB | Main: 66.07 MB
Diff: +0.21 KB (0.00%)
<details>
</details>

feat(Navigation): allow to change user icon

---

src/containers/Tenant/Query/ExecuteResult/PlanToSvgButton.tsx
src/containers/Tenant/Query/ExecuteResult/TraceButton.tsx
src/store/reducers/planToSvg.ts
src/store/reducers/trace.ts
tests/suites/nodes/nodes.test.ts
tests/suites/sidebar/Sidebar.ts
tests/suites/sidebar/sidebar.test.ts
tests/suites/tenant/TenantPage.ts
tests/suites/tenant/planToSvg/planToSvg.test.ts
tests/suites/tenant/queryEditor/planToSvg.test.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts
tests/suites/tenant/queryEditor/querySettings.test.ts
tests/suites/tenant/queryEditor/queryStatus.test.ts
tests/suites/tenant/queryHistory/queryHistory.test.ts
tests/utils/toggleExperiment.ts

This pull request includes several changes to the `src/containers/Tenant/Query/ExecuteResult` components, updates to API endpoints, and new test cases for the sidebar and query editor functionalities. The most important changes include modifying API queries, adding new test utilities and classes, and updating existing test cases.
API Query Modifications:
* [`src/containers/Tenant/Query/ExecuteResult/PlanToSvgButton.tsx`](diffhunk://#diff-62f2554948e44bc1e211385b3a124c4a1f36a6490cb39ac7cd944cc8899be4d8L26-R26): Changed from `usePlanToSvgQueryMutation` to `useLazyPlanToSvgQueryQuery`.
* [`src/containers/Tenant/Query/ExecuteResult/TraceButton.tsx`](diffhunk://#diff-094308e786b6201558e689e0266f990fa466bda19f0d4e23100c40ab62982a03L23-R23): Changed from `useCheckTraceMutation` to …

fix: change trace and svg mutations to lazy query

---

src/containers/Tenant/Query/NewSQL/NewSQL.tsx
src/containers/Tenant/Query/NewSQL/i18n/en.json
src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/utils/newSQLQueryActions.ts
src/containers/Tenant/utils/schemaActions.ts
src/containers/Tenant/utils/schemaQueryTemplates.ts
src/types/window.d.ts
src/utils/monaco/insertSnippet.ts

closes #1625 
[Stand](https://nda.ya.ru/t/EHkvxCEu79foM7)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1626/)
| 154 | 154 | 0 | 0 | 0 |
Current: 66.08 MB | Main: 66.08 MB
<details>
</details>

feat: use monaco snippets for query templates

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/SaveQuery/SaveQuery.tsx
src/store/reducers/queryActions/types.ts
src/utils/hooks/withConfirmation/useChangeInputWithConfirmation.tsx

This pull request introduces significant refactoring to the `QueryEditor` and `SaveQuery` components, focusing on integrating the `NiceModal` library for improved modal handling. The changes also include updates to the `SaveQueryDialog` and related components to enhance their functionality and usability.
Key changes include:
* [`src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx`](diffhunk://#diff-867201b43dc491552cf6cdbf05fadf8969ec80f3df30886429f1c87287ef58f4R3): Imported `NiceModal` and replaced the direct usage of `SaveQueryDialog` with `NiceModal.show` to display the dialog. [[1]](diffhunk://#diff-867201b43dc491552cf6cdbf05fadf8969ec80f3df30886429f1c87287ef58f4R3) [[2]](diffhunk://#diff-867201b43dc491552cf6cdbf05fadf8969ec80f3df30886429f1c87287ef58f4L57-R58) …

fix(SaveQueryDialog): should not duplicate component in DOM

---

src/containers/Tenant/Diagnostics/Partitions/Partitions.tsx
src/containers/Tenant/Diagnostics/Partitions/PartitionsControls/PartitionsControls.tsx
src/store/reducers/partitions/partitions.ts
src/store/reducers/partitions/types.ts

Closes #1482 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1644/)
| 154 | 152 | 0 | 2 | 0 |
Current: 66.07 MB | Main: 66.08 MB
Diff: 0.00 MB (-0.01%)
<details>
</details>

fix: remove empty selectedConsumer from url

---

src/components/MemoryViewer/MemoryViewer.tsx
src/components/nodesColumns/columns.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TenantMemory.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/services/api.ts
src/types/api/tenant.ts

Addition to #1177
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1623/)
| 134 | 130 | 0 | 4 | 0 |
Current: 66.07 MB | Main: 66.06 MB
<details>
</details>

feat: render tenant memory details

---

src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.tsx
src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsSelect.tsx
src/containers/Tenant/Query/QuerySettingsDialog/i18n/en.json
src/containers/Tenant/Query/QuerySettingsDialog/i18n/ru.json
src/containers/UserSettings/i18n/en.json
src/utils/hooks/useQueryExecutionSettings.ts
tests/suites/tenant/queryEditor/planToSvg.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1656
[Stand](https://nda.ya.ru/t/iU0ULtLu79neC3) 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1658/)
| 176 | 176 | 0 | 0 | 0 |
<details>
</details>

fix: make plan to svg more comprehensive

---

.github/workflows/ci.yml
playwright.config.ts
src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.tsx
src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsSelect.tsx
tests/suites/tenant/queryEditor/models/QueryEditor.ts
tests/suites/tenant/queryEditor/models/SettingsDialog.ts
tests/suites/tenant/queryEditor/planToSvg.test.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts
tests/suites/tenant/queryEditor/querySettings.test.ts
tests/suites/tenant/queryEditor/queryStatus.test.ts
tests/suites/tenant/queryHistory/queryHistory.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1659
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1660/)
| 182 | 182 | 0 | 0 | 0 | ✨ 3 |
Diff: +0.19 KB (0.00%)
<details>
- ✨ indicates 3 new test cases added in this PR.
</details>

chore: tests for disabled statistics

---

.github/workflows/ci.yml
tests/suites/tenant/queryEditor/models/NewSqlDropdownMenu.ts
tests/suites/tenant/queryEditor/queryTemplates.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1655
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1662/)
| 186 | 186 | 0 | 0 | 0 | ✨ 2 |
<details>
- ✨ indicates 2 new test cases added in this PR.
</details>

fix: add couple of template tests

---

.github/workflows/ci.yml

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1670/)
| 186 | 186 | 0 | 0 | 0 | ➖ 0 |
<details>
- ➖ indicates 0 new test cases added in this PR.
</details>

fix: split deploy and update pr

---

src/types/api/autocomplete.ts
src/utils/monaco/yql/generateSuggestions.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1665/)
| 182 | 182 | 0 | 0 | 0 | ➖ 0 |
Current: 66.12 MB | Main: 66.11 MB
<details>
- ➖ indicates 0 new test cases added in this PR.
</details>

feat(autocomplete): show column attributes

---

.github/workflows/quality.yml
package-lock.json
package.json
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/utils/schemaActions.tsx
src/containers/Tenant/utils/schemaQueryTemplates.ts
src/services/api.ts
src/store/reducers/overview/overview.ts
src/store/reducers/tableSchemaData.ts
src/store/reducers/viewSchema/viewSchema.ts
tests/suites/tenant/queryEditor/queryEditor.test.ts
tests/suites/tenant/summary/ActionsMenu.ts
tests/suites/tenant/summary/ObjectSummary.ts
tests/suites/tenant/summary/objectSummary.test.ts
tests/utils/constants.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1502
[Stand](https://nda.ya.ru/t/xab3ACJP79p9PJ)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1672/)
| 194 | 194 | 0 | 0 | 0 |
Current: 66.12 MB | Main: 66.12 MB
<details>
</details>

feat: indicate schema description loading

---

src/containers/Tenant/Schema/SchemaViewer/prepareData.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1681/)
| 194 | 193 | 0 | 1 | 0 |
Current: 66.12 MB | Main: 66.12 MB
Diff: +0.08 KB (0.00%)
<details>
</details>

fix: show zero default for column

---

src/containers/AsideNavigation/AsideNavigation.tsx

Link `https://ydb.tech/docs` doesn't work anymore, it requires language to be set. Added correct link, make link dependent on user's language
Closes #1686
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1687/)
| 194 | 194 | 0 | 0 | 0 |
Current: 66.10 MB | Main: 66.10 MB
Diff: +0.57 KB (0.00%)
<details>
</details>

fix(AsideNavigation): fix documentation link

---

src/utils/query.ts
tests/suites/tenant/queryEditor/models/SettingsDialog.ts
tests/suites/tenant/queryEditor/querySettings.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1679
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1695/)
| 202 | 202 | 0 | 0 | 0 |
<details>
<summary>Test Changes Summary ✨4 </summary>
1. Shows error for limit rows > 100000 (tenant/queryEditor/querySettings.test.ts)
2. Shows error for negative limit rows (tenant/queryEditor/querySettings.test.ts)
3. Persists valid limit rows value (tenant/queryEditor/querySettings.test.ts)
4. Allows empty limit rows value (tenant/queryEditor/querySettings.test.ts)
</details>
Diff: +0.00 KB (0.00%)
<details>
- Test recordings for failed …

fix: make limit rows less or equal to 100_000

---

src/components/MemoryViewer/MemoryViewer.tsx
src/components/MemoryViewer/utils.ts
src/types/api/nodes.ts
tests/suites/memoryViewer/MemoryViewer.ts
tests/suites/memoryViewer/memoryViewer.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1682
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1696/)
<details>
<summary>Test Changes Summary ✨7 </summary>
1. Memory viewer is visible and has correct status (memoryViewer/memoryViewer.test.ts)
2. Memory viewer shows correct base metrics (memoryViewer/memoryViewer.test.ts)
3. Memory viewer popup shows on hover with all metrics (memoryViewer/memoryViewer.test.ts)
4. Shows error for limit rows > 100000 (tenant/queryEditor/querySettings.test.ts)
5. Shows error for negative limit rows (tenant/queryEditor/querySettings.test.ts)
6. Persists valid limit rows value …

fix: fallback for detailed memory

---

tests/suites/memoryViewer/MemoryViewer.ts
tests/suites/memoryViewer/memoryViewer.test.ts
tests/suites/paginatedTable/paginatedTable.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1698
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1699/)
<details>
</details>

fix: memory tests

---

.github/workflows/cleanup-gh-pages.yml
.github/workflows/quality.yml
README.md

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1702
Should run sequentially or
```
Run peaceiris/actions-gh-pages@v3
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
Prepare publishing assets
Setup Git config
Create a commit
Push the commit or tag
/usr/bin/git push origin --force gh-pages
To https://github.com/ydb-platform/ydb-embedded-ui.git
! [remote rejected] gh-pages -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at aac9b855b126a1fb0630e87cf89be6e597a8b33c but expected 42c0e40f[13](https://github.com/ydb-platform/ydb-embedded-ui/actions/runs/12030274326/job/33538148088#step:6:14)fb6ced9aec921cce88e8cacd07b72d)
error: failed to push some refs to 'https://github.com/ydb-platform/ydb-embedded-ui.git'
Error: Action …
```

fix: deploy test report error

---

src/components/QueryResultTable/QueryResultTable.tsx

Closes #616 
With `dynamicRenderType: 'variable'` and `dynamicItemSizeGetter` table renders all its cells, it causes performance issues on big tables.
Rendering of a query result table with 100 000 rows.
With `dynamicRenderType: 'variable'` and `dynamicItemSizeGetter`:
With `'uniform'` rendering:
Stand: https://nda.ya.ru/t/VwIwqa8k79xSUi
Select 100 000 rows from `kv_test` table to check
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1697/)
Diff: 0.19 KB (-0.00%)
<details>
- Test recordings for failed tests are available in the full …

fix(QueryResultTable): optimise rendering

---

src/components/nodesColumns/columns.tsx
src/containers/Versions/GroupedNodesTree/GroupedNodesTree.scss
src/containers/Versions/GroupedNodesTree/GroupedNodesTree.tsx
src/containers/Versions/NodesTable/NodesTable.tsx
src/containers/Versions/groupNodes.ts
src/containers/Versions/types.ts

Closes #1072 
I used equivalent columns from Nodes table.
- Host + Endpoints -> nodes Host column (endpoints are displayed in popup)
- Memory used + Memory limit -> RAM (memory details are displayed in popup)
- Pools -> CPU (pools stats are displayed in popup)
Motivation: new columns have more data (e.g. node data in host popup), it is enough to update columns in one place to update it everywhere.
Although the displayed data remained the same, new version table look deserted, because new columns are much compact. However, we could easily add new columns with columns getters, if we want it.
Before:
After:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1713/) …

feat(Versions): use columns from Nodes table

---

src/components/QueryResultTable/QueryResultTable.tsx
src/styles/mixins.scss

Closes #1470 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1714/)
| 208 | 207 | 0 | 1 | 0 |
Diff: +0.68 KB (0.00%)
<details>
</details>

feat(QueryResultTable): display row number

---

src/containers/Tenant/Query/Preview/Preview.scss
src/containers/Tenant/Query/Preview/Preview.tsx
src/containers/Tenant/Query/i18n/en.json
src/store/reducers/preview.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1715/)
Current: 66.09 MB | Main: 66.08 MB
Diff: +1.18 KB (0.00%)
<details>
</details>

feat(Preview): add rows count and truncated flag

---

src/components/PaginatedTable/PaginatedTable.scss
src/containers/App/App.scss
src/containers/Tablet/components/TabletStorageInfo/TabletStorageInfo.scss
src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/SimplifiedPlan.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1710/)
Current: 65.96 MB | Main: 65.96 MB
Diff: +0.06 KB (0.00%)
<details>
</details>

fix(styles): tune hover for tables

---

src/containers/Nodes/Nodes.tsx
src/containers/Nodes/NodesControls/NodesControls.tsx
src/containers/Nodes/NodesTable.tsx
src/containers/Nodes/PeerRoleFilter/PeerRoleFilter.tsx
src/containers/Nodes/PeerRoleFilter/utils.tsx
src/containers/Nodes/getNodes.ts
src/containers/Nodes/i18n/en.json
src/containers/Nodes/useNodesPageQueryParams.ts
src/containers/Tenant/Diagnostics/Network/NetworkWrapper.tsx
src/store/reducers/capabilities/hooks.ts
src/store/reducers/nodes/types.ts
src/types/api/nodes.ts

Closes #1689
Stand: https://nda.ya.ru/t/jhLWCrm77A2kku
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1724/)
Current: 65.97 MB | Main: 65.96 MB
Diff: +6.06 KB (0.01%)
<details>
</details>

feat(Network): add peer role filter

---

src/types/api/autocomplete.ts
src/utils/monaco/yql/generateSuggestions.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1726/)
Diff: +0.30 KB (0.00%)
<details>
</details>

fix(autocomplete): should work properly if handler returns no entites

---

src/containers/Cluster/ClusterInfo/ClusterInfo.tsx
src/containers/Cluster/ClusterInfo/utils.tsx
src/containers/Cluster/i18n/en.json
src/types/api/meta.ts

Closes #1729, closes #1730
Add additional links to Cluster Links field
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1731/)
Diff: +2.31 KB (0.00%)
<details>
</details>

feat(ClusterInfo): add cores and logging links

---

src/containers/Clusters/columns.tsx
src/types/api/meta.ts
src/utils/developerUI/developerUI.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1712
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1732/)
Diff: +0.67 KB (0.00%)
<details>
</details>

feat: redirect to embedded

---

src/components/MemoryViewer/MemoryViewer.scss

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1733
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1738/)
Diff: +0.00 KB (0.00%)
<details>
</details>

fix: make grey more grey

---

package-lock.json
package.json
src/components/Table/Table.scss
src/components/Table/Table.tsx
src/containers/Tablet/components/TabletStorageInfo/TabletStorageInfo.scss
src/containers/Tablet/components/TabletStorageInfo/TabletStorageInfo.tsx
src/containers/Tablet/components/TabletStorageInfo/columns.tsx
src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/OperationCell.tsx
src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/SimplifiedPlan.scss
src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/SimplifiedPlan.tsx

closes #1427
[Stand](https://nda.ya.ru/t/aHLFDTun7AAxqv)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1736/)
Current: 65.85 MB | Main: 65.97 MB
Diff: 0.13 MB (-0.19%)
<details>
</details>

feat: add wrapper for gravity-ui/table

---

src/store/reducers/nodes/selectors.ts

Remove old funcs that were used for not paginated Nodes table
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1739/)
Diff: 1.50 KB (-0.00%)
<details>
</details>

chore: remove unneeded nodes utils

---

src/components/TooltipsContent/TabletTooltipContent/TabletTooltipContent.tsx
src/components/nodesColumns/columns.tsx
src/components/nodesColumns/constants.ts
src/containers/Tablet/components/TabletInfo/TabletInfo.tsx
src/containers/Tablet/components/TabletTable/TabletTable.tsx
src/containers/Tablets/TabletsTable.tsx
src/store/reducers/nodes/selectors.ts
src/utils/dataFormatters/__test__/formatUptime.test.ts
src/utils/dataFormatters/dataFormatters.ts
src/utils/nodes.ts

Closes #1065 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1740/)
Current: 65.86 MB | Main: 65.86 MB
Diff: +1.72 KB (0.00%)
<details>
</details>

feat: show negative uptime for nodes when disconnected

---

src/utils/dataFormatters/__test__/formatUptime.test.ts
src/utils/dataFormatters/dataFormatters.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1759/)
Diff: +0.18 KB (0.00%)
<details>
</details>

fix: fix 1 week uptime formatting

---

src/utils/monaco/insertSnippet.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1766/)
Diff: +0.76 KB (0.00%)
<details>
</details>

fix(SchemaTree): snippet not insert if user is not on Query tab

---

src/components/CellWithPopover/CellWithPopover.scss
src/components/CellWithPopover/CellWithPopover.tsx
src/components/FullNodeViewer/FullNodeViewer.tsx
src/components/TooltipsContent/TabletTooltipContent/TabletTooltipContent.tsx
src/components/UptimeViewer/UptimeViewer.tsx
src/components/UptimeViewer/i18n/en.json
src/components/UptimeViewer/i18n/index.ts
src/components/nodesColumns/columns.tsx
src/containers/Tablet/components/TabletInfo/TabletInfo.tsx
src/containers/Tablet/components/TabletTable/TabletTable.tsx
src/containers/Tablets/TabletsTable.tsx
src/store/reducers/nodes/types.ts
src/utils/dataFormatters/__test__/formatUptime.test.ts
src/utils/dataFormatters/dataFormatters.ts
src/utils/nodes.ts

Closes #1200
Stand: https://nda.ya.ru/t/bi-P0mBz7AW239
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1768/)
Current: 65.89 MB | Main: 65.88 MB
Diff: +5.32 KB (0.01%)
<details>
</details>

feat: add absolute timestamp to uptime

---

src/components/Stack/Stack.scss

Closes #667 
Stand: https://nda.ya.ru/t/5RivuhTX7AXD3g
You need to turn on VDisks column (in VDisks with PDisks column and Nodes table donors now are displayed differently)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1771/)
| 222 | 221 | 0 | 1 | 0 |
Current: 65.89 MB | Main: 65.89 MB
<details>
</details>

fix(Stack): reduce offset y on hover

---

src/components/Table/Table.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1778/)
Current: 65.89 MB | Main: 65.89 MB
Diff: +0.04 KB (0.00%)
<details>
</details>

fix(Table): selectors specifity

---

tests/suites/paginatedTable/paginatedTable.ts
tests/suites/tenant/diagnostics/Diagnostics.ts
tests/suites/tenant/diagnostics/diagnostics.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1775
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1786/)
| 232 | 231 | 0 | 1 | 0 |
<details>
<summary>Test Changes Summary ✨5 </summary>
1. Info tab shows main page elements (tenant/diagnostics/diagnostics.test.ts)
2. Info tab shows resource utilization (tenant/diagnostics/diagnostics.test.ts)
3. Info tab shows healthcheck status (tenant/diagnostics/diagnostics.test.ts)
4. Storage tab shows Groups and Nodes views (tenant/diagnostics/diagnostics.test.ts)
5. Nodes tab shows nodes table with memory viewer (tenant/diagnostics/diagnostics.test.ts)
</details>
Current: 66.16 MB | Main: 66.16 MB
✅ Bundle …

chore: add e2e tests for database info

---

package-lock.json
package.json
src/utils/monaco/yql/generateSuggestions.ts
src/utils/monaco/yql/yqlSuggestions.ts

closes #898
closes #903
[Stand](https://nda.ya.ru/t/uggCJHex7AgwZB)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1788/)
| 232 | 231 | 0 | 1 | 0 |
Current: 66.17 MB | Main: 66.16 MB
Diff: +8.91 KB (0.01%)
<details>
</details>

feat(autocomplete): suggest columns from subqueries

---

src/containers/Tenant/Diagnostics/Configs/Configs.tsx
src/store/reducers/nodesList.ts
src/store/reducers/tenant/tenant.ts

closes #1134 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1791/)
| 232 | 232 | 0 | 0 | 0 |
Current: 66.17 MB | Main: 66.17 MB
Diff: +0.28 KB (0.00%)
<details>
</details>

fix: handlers list that should be refetched in autorefresh mode

---

src/containers/Tenant/ObjectSummary/SchemaTree/RefreshTreeButton.tsx
tests/suites/tenant/summary/ObjectSummary.ts
tests/suites/tenant/summary/objectSummary.test.ts
tests/suites/tenant/summary/types.ts
tests/utils/clipboard.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1798
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1799/)
| 240 | 238 | 0 | 2 | 0 |
<details>
<summary>Test Changes Summary ✨4 </summary>
1. ACL tab shows correct access rights (tenant/summary/objectSummary.test.ts)
2. Copy path copies correct path to clipboard (tenant/summary/objectSummary.test.ts)
3. Create directory in local node (tenant/summary/objectSummary.test.ts)
4. Refresh button updates tree view after creating table (tenant/summary/objectSummary.test.ts)
</details>
Current: 66.18 MB | Main: 66.18 MB
Diff: +0.13 KB (0.00%)
<details>
- Test recordings …

chore: e2e tests part 2

---

src/components/Errors/PageError/PageError.tsx
src/containers/Operations/Operations.tsx
src/containers/Tenant/Tenant.tsx
src/services/api/base.ts
src/utils/response.ts

Coses #1802 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1803/)
| 240 | 240 | 0 | 0 | 0 |
Current: 66.18 MB | Main: 66.18 MB
Diff: +1.04 KB (0.00%)
<details>
</details>

fix(Auth): do not show access error when redirecting to auth

---

src/containers/Tenant/Query/Issues/Issues.tsx

closes #1074 
[Stand](https://nda.ya.ru/t/Rblkl2jG7AinoP)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1797/)
| 232 | 232 | 0 | 0 | 0 |
Current: 66.18 MB | Main: 66.18 MB
Diff: +5.70 KB (0.01%)
<details>
</details>

feat(Issues): click on issue sets cursor to error in editor

---

src/containers/VDiskPage/VDiskPage.tsx

Closes #1815 
Issue for further improvements (tests): #1816
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1817/)
Current: 66.14 MB | Main: 66.14 MB
Diff: +0.25 KB (0.00%)
<details>
</details>

fix(VDiskPage): fix evict action

---

src/components/MemoryViewer/MemoryViewer.tsx
src/components/ProgressViewer/ProgressViewer.tsx
src/components/nodesColumns/columns.tsx
src/containers/Cluster/ClusterDashboard/utils.tsx
src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/utils/index.ts
src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricsCards.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TenantStorage.tsx
src/containers/Tenant/Diagnostics/TopShards/columns/columns.tsx
src/store/reducers/nodes/utils.ts
src/store/reducers/tenantOverview/topShards/utils.ts
src/store/reducers/tenants/utils.ts
src/utils/constants.ts
src/utils/disks/calculatePDiskSeverity.ts
src/utils/generateEvaluator.ts
src/utils/progress.ts
src/utils/storage.ts

Closes #1811 
Added new default values to `generateEvaluator` and `calculateProgressStatus` functions (they are used almost everywhere), removed thresholds in other places
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1820/)
Current: 66.13 MB | Main: 66.14 MB
Diff: 3.27 KB (-0.00%)
<details>
</details>

feat: use the same thresholds for all progress bars

---

src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/OperationCell.tsx
src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/SimplifiedPlan.scss

closes #1114 
[Stand](https://nda.ya.ru/t/rPiaLsFX7BB8K6)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1825/)
Current: 79.95 MB | Main: 79.95 MB
Diff: +0.26 KB (0.00%)
<details>
</details>

fix(OperationCell): increase font weight for operation name

---

src/components/BasicNodeViewer/BasicNodeViewer.tsx
src/containers/Header/Header.tsx
src/containers/Node/NodeStructure/Pdisk.tsx

Closes #1138 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1824/)
Current: 79.96 MB | Main: 79.95 MB
Diff: +1.39 KB (0.00%)
<details>
</details>

fix: hide dev ui links for users with viewer rights

---

src/containers/UserSettings/UserSettings.tsx
tests/suites/tenant/summary/objectSummary.test.ts

closes #974
[Stand](http://ydb-vla-dev02-003.search.yandex.net:8765/monitoring/cluster/tenants?search=)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1827/)
Diff: +0.77 KB (0.00%)
<details>
</details>

fix(UserSettings): show description under setting control

---

src/components/EntityStatus/EntityStatus.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1842/)
Diff: +0.03 KB (0.00%)
<details>
</details>

fix(EntityStatus): background color for button under hover

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/QueryEditor/helpers.ts
src/utils/hooks/useCancellable.ts
src/utils/monaco/highlightErrors.ts
src/utils/monaco/i18n/en.json
src/utils/monaco/i18n/index.ts

closes #1796 
[Stand](https://nda.ya.ru/t/IkSyCRaS7BCo9n)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1833/)
| 262 | 259 | 0 | 3 | 0 |
Current: 80.05 MB | Main: 79.96 MB
Diff: +0.08 MB (0.11%)
<details>
</details>

feat(QueryEditor): add error highlighting

---

src/containers/Storage/StorageGroups/columns/columns.tsx

Closes #1847 
Before - shrink when column is too narrow because of resize or too wide `MediaType`:
After - clipped, but not shrink:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1851/)
Diff: 0.07 KB (-0.00%)
<details>
</details>

fix(Storage): fix encryption label shrink

---

tests/suites/tenant/summary/ObjectSummary.ts
tests/suites/tenant/summary/objectSummary.test.ts

Closes #1861
Because of some changes in our tests or ydb docker, some of the tables, that we used in tests, occurred in the bottom virtualized part of the `SchemaTree`. Previously our tests wasn't able to locate such elements.
I added `getTreeItem` method to `ObjectSummary` test class, this method can locate object not only in the visible part of `SchemaTree`.
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1863/)
Current: 80.05 MB | Main: 80.05 MB
<details>
- Bundle size is measured …

test(ObjectSummary): properly find virtualized tree element

---

src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/StorageGroups/columns/constants.ts
src/types/api/storage.ts

Closes #1855 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1859/)
Diff: +1.02 KB (0.00%)
<details>
</details>

feat(Storage): add State column

---

src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/VDisks/VDisks.scss

Closes #1840 
Set constant VDisks, so their grouping by DC will be more visible
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1857/)
Diff: 0.08 KB (-0.00%)
<details>
</details>

fix(VDisks): use fixed VDisk width

---

package-lock.json
package.json
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/types/api/schema/schema.ts

Closes #1836 
For ydb versions without `ChildrenExist` childless tree nodes will collapse when loaded (https://github.com/ydb-platform/ydb-ui-components/pull/84).
Stand: https://nda.ya.ru/t/W_Ujns7r7BMTuJ
Before:
After - nodes without children do not have chevrons:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1868/)
| 262 | 259 | 0 | 3 | 0 |
Diff: +0.68 KB (0.00%)
<details>
- 🔺 indicates …

feat(SchemaTree): do not expand childless nodes

---

src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx

For ydb versions where `ChildrenExist` is not supported current version will show all nodes as not expandable
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1872/)
Diff: +0.24 KB (0.00%)
<details>
</details>

fix(SchemaTree): expand nodes if ChildrenExist is undefined

---

src/containers/Tenant/utils/controls.tsx

Closes #1813 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1873/)
Diff: +0.89 KB (0.00%)
<details>
</details>

fix: use eye icon for preview

---

src/components/ConnectToDB/ConnectToDB.scss
src/components/ConnectToDB/ConnectToDBDialog.tsx
src/components/ConnectToDB/ConnectToDBSyntaxHighlighter/ConnectToDBSyntaxHighlighter.scss
src/components/ConnectToDB/ConnectToDBSyntaxHighlighter/ConnectToDBSyntaxHighlighter.tsx
src/components/ConnectToDB/ConnectToDBSyntaxHighlighter/lazy.ts
src/components/ConnectToDB/getDocsLink.ts
src/components/ConnectToDB/i18n/en.json
src/components/ConnectToDB/i18n/index.ts
src/components/ConnectToDB/snippets.ts
src/components/ConnectToDB/types.ts
src/containers/App/Providers.tsx
src/containers/Header/Header.tsx
src/containers/Header/i18n/en.json
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/i18n/en.json
src/containers/Tenant/utils/schemaActions.tsx
tests/suites/internalViewer/internalViewer.test.ts

Closes #1367, closes #1839
Test stand: https://nda.ya.ru/t/rHe1yYZK7BPzpK
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1838/)
Current: 80.18 MB | Main: 80.06 MB
Diff: +0.12 MB (0.15%)
<details>
</details>

feat: add connect to DB dialog

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/QueryEditor/YqlEditor.tsx
src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx

closes #1878 
[Stand](https://nda.ya.ru/t/DeaimN6f7BUGhW)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1879/)
Current: 80.19 MB | Main: 80.18 MB
Diff: +2.17 KB (0.00%)
<details>
</details>

fix(QueryEditor): dont render Results every time editor input changes

---

src/components/HoverPopup/HoverPopup.tsx
src/components/VDisk/VDisk.tsx
src/containers/Storage/PDisk/PDisk.tsx

closes #1874 
[Stand](https://nda.ya.ru/t/7U0XZLzS7BWp3g)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1883/)
Current: 80.19 MB | Main: 80.19 MB
Diff: +0.91 KB (0.00%)
<details>
</details>

fix(Storage): tune popups for vdisk and pdisk

---

tests/suites/tenant/initialLoad.test.ts

closes #1876 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1884/)
Current: 80.19 MB | Main: 80.19 MB
<details>
</details>

fix: add additional timeout for flaky tests

---

src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/Healthcheck.scss
src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/HealthcheckDetails.tsx
src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/HealthcheckPreview.tsx

fix: disable autorefresh for ydb_ru

---

src/containers/Tenant/Tenant.tsx
src/store/reducers/schema/schema.ts

Closes #1880 
Stand: https://nda.ya.ru/t/V1P0upfw7BXe2E
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1881/)
Current: 80.19 MB | Main: 80.19 MB
Diff: +3.04 KB (0.00%)
<details>
</details>

fix(Tenant): fix tabs reset on schema object change

---

package-lock.json
package.json
src/components/MetricChart/MetricChart.tsx
src/components/MetricChart/types.ts
src/containers/Tenant/Diagnostics/TenantOverview/DefaultOverviewContent/defaultDashboardConfig.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/cpuDashboardConfig.ts

Closes #656 
Add legend for CPU and transactions latencies charts.
Update chartkit, so legend is with line colors instead of semi-transparent area colors
Stand: https://nda.ya.ru/t/l82iF3zb7BZz9X
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1893/)
Current: 80.20 MB | Main: 80.20 MB
Diff: 0.24 KB (-0.00%)
<details>
</details>

feat(MetricChart): add legend to some charts

---

src/components/FormattedBytes/utils.tsx
src/containers/Cluster/ClusterInfo/components/DiskGroupsStatsBars/DiskGroupsStatsBars.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopTables.tsx
src/utils/bytesParsers/__test__/formatBytes.test.ts
src/utils/bytesParsers/formatBytes.ts
src/utils/dataFormatters/__test__/formatNumbers.test.ts
src/utils/dataFormatters/common.ts
src/utils/dataFormatters/dataFormatters.ts
src/utils/dataFormatters/formatNumber.ts

Closes #1455 
Before:
After:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1901/)
Current: 80.19 MB | Main: 80.20 MB
Diff: 2.37 KB (-0.00%)
<details>
</details>

fix(FormattedBytes): show 1_000 with another unit

---

src/containers/PDiskPage/PDiskPage.tsx
src/containers/PDiskPage/i18n/en.json
src/store/reducers/pdisk/__tests__/preparePDiskDataResponse.test.ts
src/store/reducers/pdisk/utils.ts
src/utils/disks/calculatePDiskSeverity.ts
src/utils/disks/constants.ts
src/utils/disks/helpers.ts

Closes #1812
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1907/)
Current: 80.20 MB | Main: 80.19 MB
Diff: +0.90 KB (0.00%)
<details>
</details>

fix(PDiskSpaceDistribution): update slots severity calculation

---

src/containers/Tenant/Schema/SchemaViewer/__tests__/prepareData.test.ts
src/containers/Tenant/Schema/SchemaViewer/__tests__/utils.test.ts
src/containers/Tenant/Schema/SchemaViewer/prepareData.ts
src/containers/Tenant/Schema/SchemaViewer/types.ts
src/containers/Tenant/Schema/SchemaViewer/utils.ts
src/types/api/schema/columnEntity.ts
src/types/common.ts

Closes https://github.com/ydb-platform/ydb/issues/14247
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1916/)
| 262 | 258 | 1 | 3 | 0 |
Current: 80.20 MB | Main: 80.20 MB
Diff: +0.81 KB (0.00%)
<details>
</details>

fix(SchemaViewer): use partitioning keys order from HashColumns

---

src/components/AutoRefreshControl/AutoRefreshControl.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/HealthcheckPreview.tsx
src/store/reducers/healthcheckInfo/healthcheckInfo.ts

feat(HealthcheckPreview): manual fetch for ydb_ru

---

src/containers/Tenant/utils/schemaQueryTemplates.ts

fix(schemaQueryTemplates): insert $ sign

---

src/containers/Storage/Disks/Disks.tsx
src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Storage/VDisks/VDisks.tsx
src/containers/Storage/utils/index.ts
src/store/reducers/storage/__tests__/prepareGroupsDisks.test.ts
src/store/reducers/storage/prepareGroupsDisks.ts
src/store/reducers/storage/types.ts
src/types/api/cluster.ts
src/types/api/storage.ts

Closes #1929 
Stand with the example of degraded group: https://nda.ya.ru/t/H7kJOQl57BtQVV
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1930/)
| 262 | 259 | 0 | 3 | 0 |
Current: 80.33 MB | Main: 80.32 MB
Diff: +1.20 KB (0.00%)
<details>
</details>

fix(Storage): fix disks view for degraded group

---

src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.scss
src/containers/Tenant/Schema/SchemaViewer/columns.tsx
src/containers/Tenant/Schema/SchemaViewer/prepareData.ts

closes #1954 
[Stand](https://nda.ya.ru/t/JXJ7q19Q7C5U4x)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1957/)
| 262 | 258 | 0 | 4 | 0 |
Current: 80.46 MB | Main: 80.46 MB
Diff: +3.61 KB (0.00%)
<details>
</details>

fix(SchemaViewer): fix sort order and add key icon

---

src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/RefreshTreeButton.tsx
src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/api.ts
src/store/reducers/overview/overview.ts
src/store/reducers/preview.ts
src/store/reducers/schemaAcl/schemaAcl.ts
src/store/reducers/viewSchema/viewSchema.ts

Closes #1906 
- Do not autorefresh Preview
- Do not autorefresh Overview, ACL and Schema
- Refresh Overview, ACL and Schema with tree refresh button
Overview and Schema are still affected by `Diagnostics` manual refresh, since the same apis are used in `Diagnostics`. It does not make much difference since we refresh `overviewApi` in `Diagnostics` anyway (it is used in `Tenant` component). The only unneeded refresh is `viewSchema` - if it is opened in left panel, it will be refreshed by `Diagnostics` manual refresh since this api used both in schema tabs in diagnostics. I did not find a simple solution that prevents it, so I would leave it as before, as for me this case is rare enough, while request is not heavy (`select * limit 0`)
📊 [Full …

fix(ObjectSummary): refresh tabs with tree refresh, disable autorefresh

---

src/components/PDiskInfo/PDiskInfo.tsx
src/components/PDiskPopup/PDiskPopup.tsx
src/components/TabletNameWrapper/TabletNameWrapper.tsx
src/components/TenantNameWrapper/TenantNameWrapper.tsx
src/components/TooltipsContent/NodeEndpointsTooltipContent/NodeEndpointsTooltipContent.tsx
src/components/VDiskInfo/VDiskInfo.tsx
src/components/VDiskPopup/VDiskPopup.tsx
src/components/nodesColumns/constants.ts
src/containers/Header/Header.tsx
src/containers/Node/NodeStructure/Pdisk.tsx
src/containers/Nodes/Nodes.tsx
src/containers/PDiskPage/PDiskPage.tsx
src/containers/Storage/PaginatedStorage.tsx
src/containers/Storage/StorageControls/StorageControls.tsx
src/containers/Storage/StorageGroups/columns/constants.ts
src/containers/Storage/StorageGroups/columns/hooks.ts
src/containers/Tablet/Tablet.tsx
src/containers/Tablet/components/TabletControls/TabletControls.tsx
src/containers/Tablet/components/TabletInfo/TabletInfo.tsx
src/containers/Tablets/TabletsTable.tsx
src/containers/VDiskPage/VDiskPage.tsx
src/utils/hooks/useIsUserAllowedToMakeChanges.ts
src/utils/hooks/useNodeDeveloperUIHref.ts

Closes #1408
How UI will look like for users-viewers: https://nda.ya.ru/t/BAWCJ3407C7NKx
Changes for users with `isMonitoringAllowed: false`:
- Hide storage nodes table and groups / nodes radio button, always display groups in storage
- Hide Pools and Memory columns in nodes column - for this metrics will be available columns CPU and RAM
- Hide DiskSpaceUsage, Latency, AllocationUnits, VDisksPDisks columns in storage groups table
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1967/)
Current: 80.46 MB | Main: 80.46 MB
Diff: +1.97 KB (0.00%)
<details>
- Test recordings for …

feat: hide some columns and storage nodes for users-viewers

---

src/containers/App/Content.tsx
src/containers/AsideNavigation/YdbInternalUser/YdbInternalUser.tsx
src/containers/Authentication/Authentication.tsx
src/containers/Authentication/utils.ts
src/services/api/auth.ts
src/store/reducers/authentication/authentication.ts
src/store/reducers/capabilities/capabilities.ts
src/store/reducers/capabilities/hooks.ts
src/types/api/capabilities.ts

closes #1972, #1971
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1976/)
Current: 80.61 MB | Main: 80.61 MB
Diff: +5.73 KB (0.01%)
<details>
</details>

feat: add database to authentication process

---

src/components/NodeHostWrapper/NodeHostWrapper.tsx
src/containers/AppWithClusters/ExtendedCluster/ExtendedCluster.tsx
src/containers/AppWithClusters/ExtendedTenant/ExtendedTenant.tsx
src/containers/AppWithClusters/useClusterData.ts
src/containers/Cluster/Cluster.tsx
src/containers/Cluster/ClusterInfo/ClusterInfo.tsx
src/containers/Storage/PaginatedStorageNodes.tsx
src/containers/Versions/NodesTable/NodesTable.tsx
src/types/additionalProps.ts
src/utils/hooks/useAdditionalNodesProps.ts
src/utils/hooks/useNodeDeveloperUIHref.ts
src/utils/prepareBackend.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1979/)
Current: 80.61 MB | Main: 80.61 MB
Diff: 0.62 KB (-0.00%)
<details>
</details>

fix(Node): fix developer ui link in dev mode

---

src/containers/Cluster/Cluster.scss
src/containers/Cluster/Cluster.tsx
src/containers/Node/Node.tsx
src/containers/Tablets/Tablets.tsx
src/containers/Tablets/TabletsTable.tsx
src/containers/Tablets/i18n/en.json
src/containers/Tablets/index.ts
src/containers/Tenant/Diagnostics/Diagnostics.tsx

Closes #1465 
Stand: https://nda.ya.ru/t/ALi8tv5x7CF5z8
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1981/)
Current: 80.62 MB | Main: 80.61 MB
Diff: +3.84 KB (0.00%)
<details>
</details>

feat(TabletsTable): add search by id

---

package-lock.json
package.json
src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/Diagnostics/Overview/Overview.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/utils/controls.tsx
src/containers/Tenant/utils/schema.ts
src/containers/Tenant/utils/schemaActions.tsx
src/types/api/schema/schema.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1853
[Stand](https://nda.ya.ru/t/bsOSPWk77CGdhT)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1982/)
Current: 80.62 MB | Main: 80.62 MB
Diff: +5.06 KB (0.01%)
<details>
</details>

feat: resource pool – add proper icon

---

src/components/PDiskInfo/PDiskInfo.tsx

Closes #1990 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1991/)
<details>
</details>
Current: 80.79 MB | Main: 80.79 MB
Diff: 0.09 KB (-0.00%)
<details>
</details>

fix(PDiskInfo): display SharedWithOs only when true

---

src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/TopShards/TopShards.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1999/)
<details>
</details>
Diff: 0.34 KB (-0.00%)
<details>
</details>

fix(TopShards): display table for column entities

---

src/components/LinkWithIcon/LinkWithIcon.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2002/)
| 264 | 262 | 0 | 1 | 1 |
<details>
</details>
<details>
</details>

fix(LinkWithIcon): make inline

---

src/containers/Tenant/Diagnostics/TopShards/columns/columns.tsx

Before:
After (it could also be yellow and red, if usage is high):
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2003/)
<details>
</details>
Diff: 0.85 KB (-0.00%)
<details>
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle …

feat(TopShards): colorize usage

---

src/containers/Storage/StorageGroups/columns/columns.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByCpu.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByLoad.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopQueries.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopShards.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TopNodesByMemory.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverviewTableLayout.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopGroups.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopTables.tsx
src/containers/Tenant/Diagnostics/TopQueries/columns/columns.tsx
src/utils/constants.ts

Make `TenantOverviewTableLayout` accept table as child instead of rendering it itself. The goal - make possible to reuse some tables as components like:
```
<TenantOverviewTableLayout>
<MyCustomTable/>
</TenantOverviewTableLayout>
```
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2001/)
| 264 | 262 | 0 | 1 | 1 |
<details>
</details>
Diff: +2.08 KB (0.00%)
<details>
- Test recordings for failed tests are available in the full …

refactor(TenantOverviewTableLayout): pass table as child

---

config-overrides.js
package-lock.json
package.json
public/index.html
src/components/ErrorBoundary/utils.tsx
src/containers/UserSettings/settings.tsx
src/store/configureStore.ts
src/types/window.d.ts

When ydb-embedded-ui is used as package, there is an error, that `process` is not defined. That's why I import package json directly
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1997/)
| 264 | 261 | 0 | 2 | 1 |
<details>
</details>
Diff: 0.15 KB (-0.00%)
<details>
- 📊 indicates links to detailed …

fix: fix undefined process in package

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx
src/containers/Tenant/Query/QueryResult/components/Graph/Graph.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2015/)
<details>
</details>
Current: 83.21 MB | Main: 83.21 MB
Diff: +0.43 KB (0.00%)
<details>
</details>

feat: query streaming only for queryService

---

src/components/InfoViewer/formatters/common.ts
src/containers/Tenant/Diagnostics/Overview/ChangefeedInfo/ChangefeedInfo.tsx
src/containers/Tenant/Info/ExternalDataSource/ExternalDataSource.tsx
src/containers/Tenant/Info/ExternalTable/ExternalTable.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/utils/dataFormatters/dataFormatters.ts

Closes #1886
Prevent `1970-01-01 03:00` in created time
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2018/)
<details>
</details>
Current: 83.22 MB | Main: 83.22 MB
Diff: +1.21 KB (0.00%)
<details> …

fix(ObjectSummary): do not display CreateTime if CreateStep is 0

---

src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.tsx

Closes #1288 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2019/)
<details>
</details>
Current: 83.22 MB | Main: 83.22 MB
Diff: +0.25 KB (0.00%)
<details>
</details>

fix(ShemaViewer): show loader correctly

---

src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopQueries.tsx
src/containers/Tenant/Diagnostics/TopQueries/TopQueries.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Query/QueriesHistory/QueriesHistory.tsx
src/containers/Tenant/Query/Query.tsx
src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/Query/QueryEditor/YqlEditor.tsx
src/containers/Tenant/Query/SaveQuery/SaveQuery.tsx
src/containers/Tenant/Query/SavedQueries/SavedQueries.tsx
src/store/reducers/query/query.ts
src/store/reducers/query/types.ts
src/utils/hooks/withConfirmation/useChangeInputWithConfirmation.tsx
tests/suites/tenant/TenantPage.ts
tests/suites/tenant/queryEditor/models/QueryEditor.ts
tests/suites/tenant/queryHistory/queryHistory.test.ts
tests/suites/tenant/savedQueries/models/SavedQueriesTable.ts
tests/suites/tenant/savedQueries/savedQueries.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1984
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2026/)
| 278 | 277 | 0 | 0 | 1 |
<details>
<summary>Test Changes Summary ✨7 ⏭️1 </summary>
1. No unsaved changes modal when running a query and selecting from history (tenant/queryHistory/queryHistory.test.ts)
2. No unsaved changes modal when running a query that is identical to last in history (tenant/queryHistory/queryHistory.test.ts)
3. Unsaved changes modal appears when modifying a query and selecting from history (tenant/queryHistory/queryHistory.test.ts)
4. No unsaved changes modal when selecting from history after saving a query …

fix: unsaved changes in query editor

---

src/containers/Operations/constants.ts
src/containers/Operations/i18n/en.json
src/containers/Operations/useOperationsQueryParams.ts
src/types/api/operations.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2029
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2030/)
<details>
</details>
Current: 83.22 MB | Main: 83.22 MB
Diff: 1.47 KB (-0.00%)
<details>
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle …

fix: kind export operations type

---

src/containers/Tenant/Diagnostics/Overview/TransferInfo/TransferInfo.tsx
src/types/api/schema/replication.ts

Supported changes of transfer config structure from https://github.com/ydb-platform/ydb/pull/15770

fix: supported changes of the transfer configuration structure

---

src/containers/Cluster/Cluster.tsx
src/containers/Versions/Versions.tsx
src/containers/Versions/utils.ts

closes #2046
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2047/)
| 278 | 276 | 0 | 1 | 1 |
<details>
</details>
Current: 83.23 MB | Main: 83.23 MB
<details>
</details>

fix: add required field SubDomainKey to getNodes

---

src/containers/Tablet/Tablet.tsx
src/containers/Tablet/components/TabletTable/TabletTable.tsx
src/services/api/viewer.ts
src/store/reducers/tablet.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2053
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2054/)
| 286 | 285 | 0 | 0 | 1 |
<details>
</details>
Current: 83.24 MB | Main: 83.24 MB
Diff: +0.97 KB (0.00%)
<details>
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle …

fix: whole tablet family for tabletPage

---

tests/suites/tenant/queryEditor/queryEditor.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1989
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2059/)
| 286 | 285 | 0 | 1 | 0 |
Current: 83.25 MB | Main: 83.25 MB
<details>
</details>

fix: stream test in safari

---

src/components/CriticalActionDialog/CriticalActionDialog.tsx
src/containers/Tenant/Query/utils/isQueryCancelledError.ts
src/types/api/error.ts
src/utils/__test__/response.test.ts
src/utils/errors/index.ts
src/utils/response.ts

Closes #2068 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2069/)
| 286 | 284 | 0 | 2 | 0 |
Current: 83.25 MB | Main: 83.25 MB
Diff: +3.40 KB (0.00%)
<details>
</details>

fix(PDiskPage): fix error boundary on failed restart

---

src/store/reducers/pdisk/__tests__/preparePDiskDataResponse.test.ts
src/store/reducers/pdisk/utils.ts

Closes #2060 
New logic:
1. Slots are part of PDisk, they could be occupied by VDisks or not (empty slots)
2. Slots and VDisks are different entities, slot is occupied by VDisk
3. Slot is named by group ID and pool name, we don't know actual VDisk inside slot before hovering
4. Slot and VDisk could have different statuses
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2070/)
| 286 | 286 | 0 | 0 | 0 |
Current: 83.25 MB | Main: 83.25 MB
Diff: +0.09 KB (0.00%)
<details>
- 📊 …

fix(PDiskSpaceDistribution): use only space severity for slots

---

src/components/TableWithControlsLayout/TableWithControlsLayout.scss
src/containers/App/Content.tsx
src/containers/Tenants/Tenants.scss
src/containers/Tenants/Tenants.tsx
src/containers/Tenants/i18n/en.json
src/containers/Tenants/i18n/index.ts
src/services/api/meta.ts
src/store/reducers/capabilities/capabilities.ts
src/store/reducers/capabilities/hooks.ts
src/types/api/capabilities.ts
src/types/api/tenant.ts
src/uiFactory/types.ts
src/uiFactory/uiFactory.ts
src/utils/createToast.tsx
src/utils/hooks/useDatabaseFromQuery.ts

How it will work when ui is used as a package: https://nda.ya.ru/t/a_NVBW7U7DHZKw
Stand with multi-cluster embedded version: https://nda.ya.ru/t/AUgj5s8F7DHZHW
Connected issues: #1939, #1940, #1948 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2087/)
| 298 | 298 | 0 | 0 | 0 |
Current: 83.27 MB | Main: 83.25 MB
Diff: +0.02 MB (0.02%)
<details> …

feat: allow pass create and delete DB funcs to UI

---

src/utils/disks/__test__/calculateVDiskSeverity.test.ts
src/utils/disks/calculateVDiskSeverity.ts

Closes #2081 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2110/)
| 298 | 298 | 0 | 0 | 0 |
Current: 83.27 MB | Main: 83.27 MB
Diff: +0.24 KB (0.00%)
<details>
</details>

fix: use blue color only for not replicated vdisks

---

src/containers/Tenant/Query/QueryEditor/YqlEditor.tsx
tests/suites/tenant/queryEditor/queryTemplates.test.ts
tests/suites/tenant/summary/objectSummary.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2037
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2117/)
| 312 | 311 | 0 | 1 | 0 |
<details>
<summary>Test Changes Summary ✨3 🗑️1</summary>
1. Unsaved changes modal appears when switching between templates if query was edited (tenant/queryEditor/queryTemplates.test.ts)
2. Switching between templates does not trigger unsaved changes modal (tenant/queryEditor/queryTemplates.test.ts)
3. Selecting a template and then opening history query does not trigger unsaved changes modal (tenant/queryEditor/queryTemplates.test.ts)
1. Unsaved changes modal appears when switching between templates …

fix: try no unsaved for templates

---

src/containers/Clusters/columns.tsx
src/store/reducers/clusters/types.ts
src/store/reducers/clusters/utils.ts
src/utils/__test__/parseBalancer.test.ts
src/utils/__test__/prepareBackend.test.ts
src/utils/parseBalancer.ts

Closes #2105
How it works without this fix: https://nda.ya.ru/t/1lxnjz4a7DSgCM
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2121/)
| 312 | 311 | 0 | 1 | 0 |
Current: 83.28 MB | Main: 83.28 MB
Diff: +1.61 KB (0.00%)
<details>
</details>

feat(Clusters): correct links with relative path in balancer

---

src/utils/hooks/useAutoRefreshInterval.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2063
[Stand](https://nda.ya.ru/t/95xwJVgx7DSuUQ)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2122/)
| 312 | 310 | 0 | 2 | 0 |
Current: 83.28 MB | Main: 83.28 MB
Diff: +1.61 KB (0.00%)
<details>
</details>

feat: do not automatically refresh content when browser tab is inactive

---

src/components/TenantNameWrapper/TenantNameWrapper.tsx
src/containers/AppWithClusters/ExtendedCluster/ExtendedCluster.tsx
src/store/reducers/tenants/tenants.ts
src/store/reducers/tenants/types.ts
src/store/reducers/tenants/utils.ts
src/types/additionalProps.ts
src/types/api/tenant.ts
src/utils/__test__/prepareBackend.test.ts
src/utils/additionalProps.ts
src/utils/hooks/useAdditionalNodesProps.ts
src/utils/prepareBackend.ts

Closes #2105
Changes:
- Fix links to Tenant page from Databases table with relative balancer
- Fix links to Developer UI with relative balancer
- Do not create links with nodes hosts, only with balancer
Add following changes to `.env` file and run app with `npm run start`
```
REACT_APP_BACKEND=
REACT_APP_META_BACKEND=http://ui-dev-0.ydb.yandex.net/api/meta8780
META_YDB_BACKEND=
```
`YDB DEV VLA02` and `klg1-0561` have paths relative to meta as balancer and these paths are also a little different. UI without this fix makes incorrect links to Tenant page and Developer UI.
`YDB RU PRESTABLE` has full balancer value, it works on current version and should work after fix.
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2125/) …

feat(Tenants): correct links with relative path in balancer

---

src/utils/hooks/useAutoRefreshInterval.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2123
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&clckid=5cd66065&database=%2Fdev02)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2140/)
| 318 | 315 | 0 | 3 | 0 |
Diff: +1.43 KB (0.00%)
<details>
- 📊 indicates links …

fix: update autorefresh if more that autorefresh in inactive tab passed

---

src/utils/hooks/useChangedQuerySettings.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2027
[Stand](https://nda.ya.ru/t/wnU43rID7DeXQ9)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2152/)
| 318 | 314 | 0 | 4 | 0 |
Diff: 0.03 KB (-0.00%)
<details>
</details>

fix: display query settings banner for non-default api call or txmode

---

package.json
src/components/TenantNameWrapper/TenantNameWrapper.tsx
src/containers/Cluster/utils.tsx
src/containers/Clusters/columns.tsx
src/containers/Tenant/TenantPages.tsx
src/routes.ts
src/store/__test__/getUrlData.test.ts
src/store/configureStore.ts
src/store/getUrlData.ts
src/utils/__test__/index.test.ts
src/utils/index.ts
src/utils/parseBalancer.ts

Single-cluster: https://nda.ya.ru/t/oDJve8ZJ7DegLK
Single-cluster with different `node/nodeId` in basename: https://nda.ya.ru/t/caHorlkS7DekGY
Embedded multi-cluster: https://nda.ya.ru/t/nrYduBdV7DegaP
Closes #2106 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2153/)
| 318 | 315 | 0 | 3 | 0 |
Diff: +1.88 KB (0.00%)
<details> …

feat: enable basename for multi cluster version

---

src/containers/Tenants/Tenants.tsx

Closes #2115 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2175/)
Diff: +0.07 KB (0.00%)
<details>
</details>

fix(Tenants): show create DB button only when table is loaded

---

src/utils/versions/parseNodesToVersionsValues.ts

closes #2179
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2180/)
Diff: +0.04 KB (0.00%)
<details>
</details>

fix(Versions): should calculate minor version to get color

---

src/routes.ts
src/utils/__test__/index.test.ts
src/utils/index.ts

Multiple slashed could be if we run multi-cluster mode in dev.
`.env`:
```
REACT_APP_BACKEND=
REACT_APP_META_BACKEND=http://ui-dev-0.ydb.yandex.net/api/meta8780
META_YDB_BACKEND=
```
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2186/)
Diff: +0.06 KB (0.00%)
<details>
</details>

fix: normalizePathSlashes should normalize multiple leading slashes

---

src/components/ConnectToDB/ConnectToDBDialog.tsx
src/components/ConnectToDB/__test__/utils.test.ts
src/components/ConnectToDB/snippets.ts
src/components/ConnectToDB/utils.ts
src/containers/Header/Header.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/services/api/meta.ts
src/services/api/viewer.ts
src/store/reducers/cluster/cluster.ts
src/store/reducers/tenant/tenant.ts
src/store/reducers/tenants/tenants.ts

Closes #1810 
Stand - you should click on "Connect" button in the top right corner to see the Dialog with endpoint: https://nda.ya.ru/t/6-FHwxii7DsYUf
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2198/)
Current: 83.37 MB | Main: 83.36 MB
Diff: +4.75 KB (0.01%)
<details>
</details>

feat: add endpoint to connect to db code snippets

---

src/components/TableWithControlsLayout/TableWithControlsLayout.tsx
src/containers/Storage/PaginatedStorageGroups.tsx
src/containers/Storage/PaginatedStorageNodes.tsx
src/containers/Storage/Storage.scss

closes #2195
[Stand](https://nda.ya.ru/t/QWwnT4i07Dx8SC)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2217/)
| 318 | 315 | 0 | 3 | 0 |
Current: 83.37 MB | Main: 83.37 MB
Diff: +1.35 KB (0.00%)
<details>
</details>

fix(PaginatedStorage): controls should be fixed

---

src/components/StatusIcon/StatusIcon.scss
src/components/StatusIcon/StatusIcon.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2203/)
Diff: 0.45 KB (-0.00%)
<details>
</details>

fix(StatusIcon): add icons for grey and green statuses

---

src/components/JsonViewer/JsonViewer.tsx
src/components/JsonViewer/unipika/unipika.ts

closes #2164
[Stand](https://nda.ya.ru/t/mRGZsyre7E3oo7)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2227/)
Current: 83.37 MB | Main: 83.37 MB
Diff: +1.19 KB (0.00%)
<details>
</details>

fix: fallback if unipika convert json failed

---

src/containers/Storage/utils/useStorageColumnsSettings.ts

[Stand](https://nda.ya.ru/t/6UhpysY07E3zup)
missed max instruction 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2229/)
Current: 83.38 MB | Main: 83.38 MB
Diff: +0.10 KB (0.00%)
<details>
</details>

fix: columns width

---

src/components/TableWithControlsLayout/TableWithControlsLayout.tsx
src/containers/Cluster/Cluster.scss
src/containers/Storage/PaginatedStorageGroups.tsx
src/containers/Storage/PaginatedStorageNodes.tsx
src/containers/Storage/Storage.scss
src/containers/Tenants/Tenants.scss
src/containers/Tenants/Tenants.tsx

closes #2195
[stand ](https://nda.ya.ru/t/s2IwOGmw7DxTPD)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2219/)
Current: 83.37 MB | Main: 83.37 MB
Diff: 1.22 KB (-0.00%)
<details>
</details>

fix(Cluster): layout for tabs content

---

src/containers/Header/breadcrumbs.tsx
src/containers/Tenant/ObjectSummary/ObjectTree.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2091
[Stand](http://ydb-vla-dev02-002.search.yandex.net:8765/monitoring/cluster/tenants?search=)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2244/)
Diff: +0.17 KB (0.00%)
<details>
</details>

fix: fix slashes everywhere

---

src/components/DiskStateProgressBar/DiskStateProgressBar.tsx
src/components/MemoryViewer/MemoryViewer.tsx
src/components/ProgressViewer/ProgressViewer.tsx
src/containers/Cluster/ClusterInfo/components/DiskGroupsStatsBars/DiskGroupsStats.tsx
src/store/reducers/storage/__tests__/prepareGroupsDisks.test.ts
src/utils/disks/__test__/prepareDisks.test.ts
src/utils/disks/prepareDisks.ts

Closes #2189 
Use `Math.floor` for progress bars in tables to ensure values inside will match with table groups
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2253/)
Diff: 0.02 KB (-0.00%)
<details>
</details>

fix: floor disk usage values

---

src/containers/Operations/constants.ts
src/containers/Operations/i18n/en.json
src/types/api/operations.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2258
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2256/)
Diff: +0.19 KB (0.00%)
<details>
</details>

feat: add import/s3 to operations

---

src/containers/Node/Node.tsx
src/containers/Tablets/Tablets.tsx
src/services/api/viewer.ts
src/types/store/tablets.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2262
[Stand](https://nda.ya.ru/t/0MpkPwo27EHPs4)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2263/)
Diff: +1.02 KB (0.00%)
<details>
</details>

fix: dead tablets on node page

---

src/components/TableWithControlsLayout/TableWithControlsLayout.scss

Part of #2272 
Before:
After:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2275/)
Diff: 0.09 KB (-0.00%)
<details>
</details>

fix(Tenants): move create db button to the right

---

src/containers/AppWithClusters/AppWithClusters.tsx
src/uiFactory/types.ts
src/uiFactory/uiFactory.ts

Closes #2136 
PR to merge these changes with current major.
Goals:
1) Allow further refactoring of additional props - prevent props drilling, use funcs in place
2) Single API for external options, function and configs
Usage when ui as a package:
```
const {store, history} = configureStore();
configureUIFactory({
onCreateDB: getCreateDBDialog,
onDeleteDB: getDeleteDBDialog,
getLogsLink: getLogsLink,
getMonitoringLink: getMonitoringLinkExtended,
getMonitoringClusterLink: getMonitoringClusterLinkExtended,
});
componentsRegistry
.set('StaffCard', StaffCard)
.set('AsideNavigation', AsideNavigationInternal)
.set('ShardsTable', ShardsTable);
function render() {
const container = document.getElementById('root');
if (!container) {
throw new Error("Can't find root element");
}
const root = …
```

fix!: use uiFactory for logs and monitoring links

---

src/components/VDisk/utils.ts
src/components/VDiskInfo/VDiskInfo.tsx
src/components/VDiskPopup/VDiskPopup.tsx
src/containers/PDiskPage/PDiskSpaceDistribution/PDiskSpaceDistribution.tsx
src/containers/VDiskPage/VDiskPage.tsx
src/routes.ts
src/store/reducers/storage/__tests__/prepareGroupsDisks.test.ts
src/store/reducers/storage/prepareGroupsDisks.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2267/)
Diff: +1.70 KB (0.00%)
<details>
</details>

feat(vDisk): allow evict vDisk by id

---

src/store/state-url-mapping.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2287/)
Current: 83.53 MB | Main: 83.53 MB
<details>
</details>

fix(Tenants): do not add empty search to query

---

src/components/Tags/Tags.tsx
src/containers/Cluster/ClusterInfo/ClusterInfo.scss
src/containers/Cluster/ClusterInfo/ClusterInfo.tsx
src/containers/Cluster/ClusterInfo/components/DiskGroupsStatsBars/DiskGroupsStats.scss
src/containers/Cluster/ClusterInfo/components/DiskGroupsStatsBars/DiskGroupsStats.tsx
src/containers/Cluster/ClusterInfo/utils/utils.tsx

closes #2298
[Stand](https://nda.ya.ru/t/GtuCVmVk7EXFuC
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2299/)
Current: 83.58 MB | Main: 83.57 MB
Diff: +0.56 KB (0.00%)
<details>
</details>

fix(ClusterInfo): increase fonts

---

src/containers/Tenants/Tenants.tsx
src/containers/Tenants/i18n/en.json
src/store/reducers/capabilities/hooks.ts
src/uiFactory/types.ts

Part of #2096, edit form itself will be added internally
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2305/)
Current: 83.57 MB | Main: 83.57 MB
Diff: +3.17 KB (0.00%)
<details>
</details>

feat(Tenants): add onEditDB to uiFactory, add edit button

---

package-lock.json
package.json
src/components/EntityStatus/EntityStatus.tsx
src/containers/Tenant/Diagnostics/TopicData/columns/Columns.scss
src/containers/Tenant/Diagnostics/TopicData/columns/columns.tsx
src/containers/Tenant/ObjectGeneral/ObjectGeneral.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/Query/Preview/Preview.scss
src/containers/Tenant/Query/Preview/Preview.tsx
src/containers/Tenant/Query/Preview/components/PreviewView.tsx
src/containers/Tenant/Query/Preview/components/TablePreview.tsx
src/containers/Tenant/Query/Preview/components/TopicPreview.tsx
src/containers/Tenant/Query/Preview/components/TopicPreviewTable.tsx
src/containers/Tenant/Query/Preview/i18n/en.json
src/containers/Tenant/Query/Preview/i18n/index.ts
src/containers/Tenant/Query/Preview/shared.ts
src/containers/Tenant/Query/Preview/types.ts
src/containers/Tenant/Query/Query.tsx
src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/containers/Tenant/utils/controls.tsx
src/containers/Tenant/utils/schemaActions.tsx
src/containers/Tenant/utils/types.ts
tests/suites/tenant/queryEditor/models/ResultTable.ts

Closes #1943
[Stand](https://nda.ya.ru/t/BU-ibsXL7EWxUq)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2292/)
Current: 83.58 MB | Main: 83.57 MB
Diff: +0.02 MB (0.02%)
<details>
</details>

feat(Preview): add preview for topics

---

src/components/TableWithControlsLayout/TableWithControlsLayout.scss
src/components/TableWithControlsLayout/TableWithControlsLayout.tsx
src/containers/Cluster/Cluster.scss
src/containers/Cluster/Cluster.tsx
src/containers/Cluster/ClusterOverview/ClusterOverview.scss
src/containers/Nodes/Nodes.scss
src/containers/Storage/Storage.scss
src/containers/Tenants/Tenants.scss
src/containers/Tenants/Tenants.tsx

Closes #2300 
[Stand](https://nda.ya.ru/t/Kz7h-L3E7EbP6e)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2301/)
Current: 83.57 MB | Main: 83.56 MB
Diff: +0.56 KB (0.00%)
<details>
</details>

fix(Cluster): side paddings

---

src/containers/Cluster/Cluster.tsx

closes #2306 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2307/)
Current: 83.56 MB | Main: 83.56 MB
Diff: +0.22 KB (0.00%)
<details>
</details>

fix(Cluster): autorefresh cluster data

---

src/containers/Versions/groupNodes.test.ts
src/containers/Versions/groupNodes.ts

Closes #2320
Problem: node with `Bootstrapper` was missing in the list, because it was neither storage, nor tenant and it doesn't satisfy condition `!Roles` that we had previously.
Solution: added all nodes, that are not included in Storage or Tenant group to Other group
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2327/)
Current: 83.62 MB | Main: 83.62 MB
Diff: +0.36 KB (0.00%)
<details>
- 🔺 indicates …

fix(Versions): properly include nodes with defined roles in other group

---

src/containers/Tenants/Tenants.tsx
src/uiFactory/types.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2328/)
Current: 83.62 MB | Main: 83.62 MB
Diff: 0.52 KB (-0.00%)
<details>
</details>

feat(Tenants): pass full db data to onDelete

---

src/components/Drawer/Drawer.tsx
src/components/Drawer/DrawerContext.tsx

[Stand](https://nda.ya.ru/t/orEhptcI7ExMpt)
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2350
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2351/)
Current: 83.65 MB | Main: 83.65 MB
Diff: +1.25 KB (0.00%)
<details>
</details>

fix: drawer is broken

---

src/components/PaginatedTable/PaginatedTableContext.tsx
src/components/PaginatedTable/PaginatedTableWithLayout.tsx
src/components/PaginatedTable/TableChunk.tsx
src/containers/Tenant/Diagnostics/TopicData/TopicData.tsx
src/store/reducers/tableData.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2349
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2356/)
Current: 83.65 MB | Main: 83.65 MB
Diff: +1.22 KB (0.00%)
<details>
</details>

fix: table is broken because of batching

---

.github/workflows/priority-score.yml

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2365/)
Current: 83.65 MB | Main: 83.65 MB
<details>
</details>

feat(Automation): add automation to calculate issue priority

---

.github/workflows/quality.yml

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2367
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2368/)
Current: 83.65 MB | Main: 83.65 MB
<details>
</details>

chore: run tests on actual commit not on merge commit

---

.github/workflows/add-to-project.yml
.github/workflows/priority-score.yml

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2376/)
Current: 83.76 MB | Main: 83.76 MB
<details>
</details>

fix(Automation): more automation, auto add to project

---

src/containers/Tenant/Query/Preview/components/TopicPreview.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2381/)
Current: 83.76 MB | Main: 83.76 MB
Diff: +0.04 KB (0.00%)
<details>
</details>

fix(TopicPreview): dont show negative offsets

---

src/components/VDisk/utils.ts
src/containers/VDiskPage/VDiskPage.tsx
src/utils/disks/prepareDisks.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2399/)
| 322 | 319 | 0 | 2 | 1 |
<details>
</details>
Current: 83.77 MB | Main: 83.77 MB
Diff: +0.39 KB (0.00%)
<details>
</details>

feat: evict unhealthy VDisk

---

src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/HealthcheckPreview.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2427/)
| 2 | 2 | 0 | 0 | 0 |
Current: 83.89 MB | Main: 83.90 MB
Diff: 2.47 KB (-0.00%)
<details>
</details>

fix(HealthcheckPreview): use only one query

---

src/containers/Nodes/getNodes.ts
src/services/api/viewer.ts

Currently we always request tablets on `Nodes` and `Network` tabs.
Request only data specified in `fieldsRequired`, use `tablets` param for backward compatibility
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2433/)
| 2 | 2 | 0 | 0 | 0 |
Current: 83.89 MB | Main: 83.89 MB
Diff: +0.10 KB (0.00%)
<details>
</details>

fix(Nodes): request tablets only if required

---

tests/suites/tenant/diagnostics/tabs/access.test.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2436/)
| 336 | 330 | 0 | 1 | 5 |
<details>
<summary>Test Changes Summary ✨167 ⏭️3 </summary>
1. Test internalViewer header link (internalViewer/internalViewer.test.ts)
2. Memory viewer is visible and has correct status (memoryViewer/memoryViewer.test.ts)
3. Memory viewer shows correct base metrics (memoryViewer/memoryViewer.test.ts)
4. Memory viewer popup shows on hover with all metrics (memoryViewer/memoryViewer.test.ts)
5. Nodes page is OK (nodes/nodes.test.ts)
6. Nodes page has nodes table (nodes/nodes.test.ts)
7. Table loads and displays data (nodes/nodes.test.ts)
8. Search by hostname filters the table (nodes/nodes.test.ts)
9. …

fix: unskip tests

---

tests/suites/tenant/diagnostics/tabs/access.test.ts

closes #2437
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2439/)
| 336 | 332 | 0 | 3 | 1 |
<details>
</details>
Current: 83.89 MB | Main: 83.89 MB
<details>
</details>

fix: tests

---

src/containers/Tenant/Tenant.tsx
src/containers/Tenant/useTenantQueryParams.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2458/)
| 336 | 323 | 12 | 0 | 1 |
<details>
</details>
Current: 83.90 MB | Main: 83.90 MB
Diff: 0.24 KB (-0.00%)
<details>
</details>

fix: do not expose obsolet name param

---

src/containers/Tenant/Diagnostics/Diagnostics.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2487/)
| 348 | 342 | 0 | 1 | 5 |
<details>
<summary>Test Changes Summary ⏭️3 </summary>
1. Query tab first row has values for all columns in Top mode (tenant/diagnostics/tabs/queries.test.ts)
2. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
3. TopShards tab first row has values for all columns in History mode (tenant/diagnostics/tabs/topShards.test.ts)
</details>
Current: 84.00 MB | Main: 84.00 MB
Diff: +0.28 KB (0.00%)
<details>
- Test recordings for failed tests are available in the full …

fix: do not show backups if no control_plane

---

src/components/ComponentsProvider/registry.ts
src/containers/Header/Header.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2493
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2499/)
| 354 | 348 | 0 | 1 | 5 |
<details>
<summary>Test Changes Summary ⏭️3 </summary>
1. Query tab first row has values for all columns in Top mode (tenant/diagnostics/tabs/queries.test.ts)
2. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
3. TopShards tab first row has values for all columns in History mode (tenant/diagnostics/tabs/topShards.test.ts)
</details>
Current: 84.00 MB | Main: 84.00 MB
Diff: +0.49 KB (0.00%)
<details>
<summary>ℹ️ CI …

fix: aibutton placeholder header

---

public/index.html

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2480/)
| 344 | 338 | 0 | 1 | 5 |
<details>
<summary>Test Changes Summary ⏭️3 🗑️2</summary>
1. Query tab first row has values for all columns in Top mode (tenant/diagnostics/tabs/queries.test.ts)
2. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
3. TopShards tab first row has values for all columns in History mode (tenant/diagnostics/tabs/topShards.test.ts)
1. shows access denied when operations request returns 403 (tenant/diagnostics/tabs/operations.test.ts)
2. loads all operations when scrolling to the bottom multiple times …

fix: interface blinks on reload with dark theme

---

src/containers/Tenants/Tenants.tsx

Closes #1925 
Stand: https://nda.ya.ru/t/TPpOcAN57Fpbjh
You need to turn on experiment "Show network utilization"
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2478/)
| 354 | 348 | 0 | 1 | 5 |
<details>
<summary>Test Changes Summary ⏭️3 </summary>
1. Query tab first row has values for all columns in Top mode (tenant/diagnostics/tabs/queries.test.ts)
2. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view (tenant/diagnostics/tabs/queries.test.ts)
3. TopShards tab first row has values for all columns in History mode (tenant/diagnostics/tabs/topShards.test.ts)
</details>
Current: 84.00 MB | Main: 84.00 MB
Diff: +1.94 KB (0.00%)
✅ Bundle size …

feat(Tenants): add network column

---

src/containers/Operations/Operations.tsx
src/containers/Operations/OperationsControls.tsx
src/containers/Operations/i18n/en.json
src/containers/Operations/useOperationsInfiniteQuery.ts
tests/suites/tenant/diagnostics/tabs/OperationsModel.ts
tests/suites/tenant/diagnostics/tabs/operations.test.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2538
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2540/)
| 354 | 351 | 0 | 2 | 1 |
<details>
</details>
Current: 84.01 MB | Main: 84.01 MB
Diff: 1.26 KB (-0.00%)
<details>
- 🔺 indicates increase, 🔽 decrease, and ✅ no …

fix: remove operations counter

---

src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx
src/store/reducers/query/query.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2557
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2559/)
<details>
</details>
Current: 85.06 MB | Main: 85.06 MB
Diff: +0.98 KB (0.00%)
<details>
- 📊 …

fix: cancel previous multipart request if the new one starts

---

src/components/MetricChart/MetricChart.scss
src/components/MetricChart/MetricChart.tsx
src/components/QueriesActivityBar/QueriesActivityBar.scss
src/components/QueriesActivityBar/QueriesActivityBar.tsx
src/components/QueriesActivityBar/QueriesActivityCharts.tsx
src/components/QueriesActivityBar/i18n/en.json
src/components/QueriesActivityBar/i18n/index.ts
src/components/QueriesActivityBar/utils.ts
src/components/TimeFrameDropdown/TimeFrameDropdown.tsx
src/components/TimeFrameDropdown/i18n/en.json
src/components/TimeFrameDropdown/i18n/index.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantDashboard/TenantDashboard.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantDashboard/TenantDashboard.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/TenantPages.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2444
[Stand](https://nda.ya.ru/t/SZO5eQSG7GESFy)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2549/)
<details>
</details>
Current: 85.11 MB | Main: 85.06 MB
Diff: +0.04 MB (0.05%)
<details>
- …

feat: add Queries activities banner

---

src/components/QueriesActivityBar/QueriesActivityBar.tsx
src/components/QueriesActivityBar/QueriesActivityCharts.tsx

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2572/)
<details>
</details>
Current: 85.16 MB | Main: 85.16 MB
Diff: +1.97 KB (0.00%)
<details> …

fix: query activities banner visibility

---

src/components/SpeedMultiMeter/SpeedMultiMeter.scss

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2585/)
| 354 | 350 | 0 | 2 | 2 |
<details>
</details>
Current: 85.18 MB | Main: 85.18 MB
<details> …

fix(SpeedMuliMeter): add popup content padding

---

src/containers/App/App.tsx
src/containers/App/AppTitleContext.tsx
src/containers/App/Providers.tsx
src/containers/AppWithClusters/AppWithClusters.tsx
src/containers/Cluster/Cluster.tsx
src/containers/Node/Node.tsx
src/containers/PDiskPage/PDiskPage.tsx
src/containers/StorageGroupPage/StorageGroupPage.tsx
src/containers/Tenant/Tenant.tsx
src/containers/VDiskPage/VDiskPage.tsx

closes ##2561
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2584/)
| 354 | 349 | 0 | 3 | 2 |
<details>
</details>
Current: 85.19 MB | Main: 85.18 MB
Diff: +3.55 KB (0.00%)
<details>
- 🔺 indicates …

feat: use custom app title

---

src/styles/versions.scss
src/utils/versions/getVersionsColors.ts

Closes #2593 
Stand: https://nda.ya.ru/t/C__F9a9B7GiyXY
Figma: https://nda.ya.ru/t/NOUj-4Vl7GixzX
New palette:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2596/)
| 354 | 349 | 0 | 3 | 2 |
<details>
</details>
Current: 85.21 MB | Main: 85.20 MB
Diff: +2.18 KB (0.00%)
<details>
- Bundle size is …

feat: update versions colors

---

src/services/api/index.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2613/)
| 354 | 130 | 221 | 1 | 2 |
<details>
</details>
Current: 85.21 MB | Main: 85.21 MB
Diff: +0.13 KB (0.00%)
<details> …

fix(api): constructor types

---

src/components/InfoViewer/InfoViewer.scss
src/components/InfoViewer/InfoViewer.tsx
src/components/MemoryViewer/MemoryViewer.tsx
src/components/ProgressViewer/ProgressViewer.tsx
src/components/ProgressViewer/i18n/en.json
src/components/ProgressViewer/i18n/index.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/useTenantCpuQueryParams.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantDashboard/TenantDashboard.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/ProgressWrapper.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TenantStorage.scss
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TenantStorage.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopTables.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/constants.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/i18n/en.json
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/i18n/index.ts
src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/useTenantStorageQueryParams.ts
src/containers/Tenant/Diagnostics/TenantOverview/i18n/en.json
src/containers/Tenant/TenantPages.tsx
src/store/reducers/tenant/constants.ts
src/store/reducers/tenant/tenant.ts
src/store/reducers/tenant/types.ts
src/utils/progress.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2446
[Stand](https://nda.ya.ru/t/zG98YWkq7GpMgs)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2608/)
| 354 | 350 | 0 | 2 | 2 |
<details>
</details>
Current: 85.29 MB | Main: 85.26 MB
Diff: +0.03 MB (0.03%)
<details>
- …

feat: redesign Storage section

---

src/containers/AsideNavigation/AsideNavigation.scss
tests/suites/sidebar/sidebar.test.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2629/)
<details>
</details>
Current: 85.29 MB | Main: 85.29 MB
Diff: +0.02 KB (0.00%)
<details> …

fix(AsideNavigation): hotkeys section position

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml

I want to trigger claude only manually when he is needed
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2647/)
<details>
</details>
Current: 85.35 MB | Main: 85.35 MB
<details>
- 📊 indicates …

chore: only manual claude call

---

src/store/reducers/tenant/tenant.ts
src/store/reducers/tenant/types.ts

closes #2648
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2649/)
| 354 | 349 | 0 | 3 | 2 |
<details>
</details>
Current: 85.35 MB | Main: 85.35 MB
<details>
- 🔺 indicates …

fix: tenant navigation

---

src/containers/Header/Header.tsx
src/containers/Header/breadcrumbs.tsx
src/store/reducers/authentication/authentication.ts
src/store/reducers/authentication/types.ts
src/store/reducers/header/types.ts
src/types/api/whoami.ts
src/utils/hooks/useIsUserAllowedToMakeChanges.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2672/)
| 354 | 349 | 0 | 3 | 2 |
<details>
<summary>Test Changes Summary ✨1 ⏭️2 </summary>
1. ACL tab shows redirect message and link to Diagnostics (tenant/summary/objectSummary.test.ts)
</details>
Current: 85.35 MB | Main: 85.35 MB
Diff: +1.33 KB (0.00%)
<details>
- Bundle size is measured for …

feat: add new role IsDatabaseAllowed and shrink breadcrumbs

---

src/containers/Clusters/Clusters.scss
src/containers/Clusters/columns.tsx
src/containers/Header/Header.scss
src/containers/Header/Header.tsx
src/containers/Header/i18n/en.json
src/containers/Tenants/Tenants.scss
src/containers/Tenants/Tenants.tsx
src/store/reducers/tenant/tenant.ts

Stand: https://nda.ya.ru/t/EpvLxdjq7HGMbL
Go to Database page, Manage dropdown will be in the Header
Closes #2100 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2680/)
| 358 | 353 | 0 | 3 | 2 |
<details>
</details>
Current: 85.32 MB | Main: 85.35 MB
Diff: 0.04 MB (-0.04%)
<details>
- Bundle size …

feat(Header): add manage DB dropdown

---

src/utils/versions/parseVersion.ts

Closes #2678 
Previously we had versions in format `ydb-stable-25-2-3` and removed build version (4 number), now it is a common practice to use build version - we have many versions in format `ydb-stable-25-1-2-18`
Why it is needed:
1. To properly change colors for build versions too: `ydb-stable-25-1-2-18` may have different color variant from `ydb-stable-25-1-2-12`
2. To allow selecting these specific versions in versions selector on clusters page
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2688/)
| 358 | 352 | 0 | 4 | 2 |
<details>
1. Scroll to row, get shareable link, navigate to URL and verify row is scrolled into view …

fix: do not remove build from versions

---

src/containers/Tenant/Query/QueryResult/components/ResultSetsViewer/ResultSetsViewer.tsx

closes #2541
It is possible to solve the problem 2 ways:
1) Trigger syntetic resize event to force recalculate virtualization state
2) pass `dynamicRenderMinSize` property to the table to increase minimum rendered rows.
I decided to implement first way, cause rows in query results may be very big (lots of columns). So I don't want to render more than needed.
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2704/)
| 358 | 350 | 0 | 6 | 2 |
<details>
2. Copy result button copies to clipboard …

fix(ResultSetsViewer): recount rows if fullscreen

---

tests/suites/tenant/diagnostics/Diagnostics.ts
tests/suites/tenant/diagnostics/tabs/info.test.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2705/)
| 362 | 357 | 0 | 3 | 2 |
<details>
<summary>Test Changes Summary ✨3 ⏭️2 🗑️1</summary>
1. Info tab shows healthcheck status when there are issues (tenant/diagnostics/tabs/info.test.ts)
2. Info tab hides healthcheck status when status is GOOD with no issues (tenant/diagnostics/tabs/info.test.ts)
3. Info tab shows healthcheck status when status is GOOD but has issues (tenant/diagnostics/tabs/info.test.ts)
1. Info tab …

fix: broken tests for healthcheck

---

src/containers/App/Content.tsx
src/store/reducers/capabilities/hooks.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2727/)
| 0 | 0 | 0 | 0 | 0 |
<details>
<summary>Test Changes Summary 🗑️189</summary>
1. off: no Pile Name column and no group-by option (bridge/bridge.test.ts)
2. on: shows Pile Name column (bridge/bridge.test.ts)
3. on: shows Pile Name (bridge/bridge.test.ts)
4. off: hides Pile Name (bridge/bridge.test.ts)
5. on: shows Pile Name and group-by option (bridge/bridge.test.ts)
6. off: hides Pile Name and group-by option (bridge/bridge.test.ts)
7. off: does not show Bridge piles section (bridge/bridge.test.ts)
8. on: shows Bridge piles section with data (bridge/bridge.test.ts)
9. Test internalViewer header link …

fix(Content): do not request whoami if auth is in progress

---

src/containers/Cluster/ClusterOverview/components/BridgeInfoTable.tsx
src/types/api/cluster.ts
tests/suites/bridge/bridge.test.ts
tests/suites/bridge/mocks.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2721
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2733/)
| 378 | 372 | 0 | 4 | 2 |
<details>
</details>
Diff: 1.38 KB (-0.00%)
<details>
- 📊 …

fix: 2dc format from backend

---

src/components/CellWithPopover/CellWithPopover.scss
src/components/CellWithPopover/CellWithPopover.tsx
src/components/ProgressViewer/ProgressViewer.tsx
src/components/nodesColumns/NodesColumns.scss
src/containers/Node/Threads/CpuUsageBar/CpuUsageBar.scss

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2740
[Stand](https://nda.ya.ru/t/Hcz9vHPi7HwGpM)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2748/)
<details>
</details>
Diff: +0.27 KB (0.00%)
<details>
- Bundle size is …

feat: make RAM and CPU bars fill container width in tables

---

src/components/EntityStatus/EntityStatus.scss
src/components/EntityStatus/EntityStatus.tsx

Revert changes from #2738 
Buttons now look badly when they are above the text
Created an issue for buttons bg in selected rows: #2751 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2752/)
<details>
</details>
Diff: +0.34 KB (0.00%)
<details>
- Test recordings for failed tests are available in the full …

fix(EntityStatus): return controls wrapper bg

---

src/components/Drawer/Drawer.scss
src/containers/Cluster/Cluster.tsx
src/styles/drawer.scss

It's needed for Events tab - #2670 
Stand: https://nda.ya.ru/t/kHxFA0ax7J5fYr
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2757/)
<details>
</details>
Current: 85.38 MB | Main: 85.37 MB
Diff: +2.90 KB (0.00%)
<details>
- Bundle size is measured for the entire 'dist' …

feat: enable drawer on cluster page

---

src/components/ConnectToDB/ConnectToDBDialog.tsx
src/containers/Header/Header.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/Tenant.tsx
src/containers/Tenant/useTenantQueryParams.ts
src/containers/Tenants/Tenants.tsx
src/services/api/meta.ts
src/store/reducers/capabilities/hooks.ts
src/store/reducers/tenant/tenant.ts
src/store/reducers/tenants/tenants.ts
src/types/api/capabilities.ts

closes #2777
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2782/)
<details>
</details>
Current: 85.38 MB | Main: 85.37 MB
Diff: +5.44 KB (0.01%)
<details>
- …

feat: support meta/databases handler

---

src/components/TenantNameWrapper/TenantNameWrapper.tsx
src/containers/Header/breadcrumbs.tsx
src/containers/Tenant/Tenant.tsx
src/store/reducers/header/types.ts
src/store/reducers/tenant/tenant.ts
src/uiFactory/types.ts
src/uiFactory/uiFactory.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2812/)
| 378 | 372 | 0 | 4 | 2 |
<details>
</details>
Diff: +0.58 KB (0.00%)
<details> …

feat: support use database id in links

---

src/components/PaginatedTable/PaginatedTable.tsx
src/components/PaginatedTable/TableChunksRenderer.tsx
src/components/PaginatedTable/useScrollBasedChunks.ts
src/components/PaginatedTable/utils.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2711
[Stand](https://nda.ya.ru/t/Ecz93UXo7JQNGx)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2809/)
<details>
</details>
Diff: +2.22 KB (0.00%)
<details>
- Bundle size is …

fix: rack groups disco dance

---

src/components/Fullscreen/Fullscreen.tsx
src/components/QueryResultTable/QueryResultTable.tsx
src/components/ResizeableDataTable/ResizeableDataTable.scss
src/containers/Tenant/Query/QueryResult/components/ResultSetsViewer/ResultSetsViewer.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2724
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2720
[Stand](https://nda.ya.ru/t/fQ7KJjqw7JQs8R)
- Clusters list: `/clusters`
- Single-cluster root (if singleClusterMode): `/cluster` (plus tabs via `/:activeTab`)
- Tenants list: `/tenant` (with `?clusterName=<name>` in multi-cluster mode)
- Node details: `/node/:id/:activeTab?`
- Tablets table pages:
- Tablets page: embedded within `/tenant` tabs or `/node/:id/...` tabs depending on navigation
- Individual tablet: `/tablet/:id`
- Storage entities:
- VDisk page: `/vDisk?nodeId=<id>&vDiskId=<id>&database=<db>`
- PDisk page: `/pDisk?nodeId=<id>&pDiskId=<id>`
- Storage group: `/storageGroup?groupId=<id>`
- Query pages:
- Query editor/result: under `/tenant` …

fix: query tables styles

---

src/containers/Header/breadcrumbs.tsx
src/containers/Node/Node.tsx
src/containers/StorageGroupPage/StorageGroupPage.tsx
src/containers/Tablet/Tablet.tsx
src/containers/Tenant/Tenant.tsx
src/containers/VDiskPage/VDiskPage.tsx
src/store/reducers/header/types.ts
src/store/reducers/tenant/tenant.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2823/)
<details>
</details>
Diff: +0.15 KB (0.00%)
<details> …

fix(breadcrumbs): use database param for links

---

src/containers/Tenant/ObjectSummary/__test__/transformPath.test.ts
src/containers/Tenant/ObjectSummary/transformPath.ts
src/containers/Tenant/utils/schemaActions.tsx

closes #2827
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2828/)
<details>
</details>
Diff: 0.05 KB (-0.00%)
<details>
- 🔺 indicates …

fix(transformPath): use fair relative path

---

src/containers/Tenant/ObjectSummary/__test__/transformPath.test.ts
src/containers/Tenant/ObjectSummary/transformPath.ts
src/containers/Tenant/utils/schemaActions.tsx

This reverts commit 6c94aafb0b55b0dd687053688b2cae8b662008e5.

fix(transformPath): do not use fair relative path

---

src/services/api/base.ts
src/services/api/index.ts
src/services/api/scheme.ts
src/store/configureStore.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2841/)
<details>
</details>
Current: 0.00 KB | Main: 0.00 KB
Diff: 0.00 KB (N/A)
⚠️ Unable to calculate change.
<details> …

feat: configurable use relative paths in api

---

src/components/ConnectToDB/ConnectToDBDialog.tsx
src/components/ShardsTable/columns.tsx
src/containers/Header/Header.tsx
src/containers/Tenant/Diagnostics/Diagnostics.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TenantCpu.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopShards.tsx
src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
src/containers/Tenant/Diagnostics/TopShards/TopShards.tsx
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/ObjectSummary/ObjectTree.tsx
src/containers/Tenant/ObjectSummary/SchemaTree/SchemaTree.tsx
src/containers/Tenant/ObjectSummary/transformPath.ts
src/containers/Tenant/Query/Preview/components/TablePreview.tsx
src/containers/Tenant/Tenant.tsx
src/containers/Tenant/TenantContext.tsx
src/containers/Tenant/utils/schemaActions.tsx
src/store/reducers/shardsWorkload/shardsWorkload.ts
src/store/reducers/tenantOverview/topShards/tenantOverviewTopShards.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2843/)
<details>
</details>
Current: 85.42 MB | Main: 85.41 MB
Diff: +5.01 KB (0.01%)
<details>
- 🔺 indicates …

fix: relative path usage fixes

---

src/store/reducers/tenantOverview/topShards/tenantOverviewTopShards.ts

Closes #2844
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2854/)
<details>
</details>
Current: 85.41 MB | Main: 85.41 MB
Diff: +0.02 KB (0.00%)
<details>
- 🔺 indicates …

fix(TenantOverview): show shard advice

---

src/components/InfoViewer/formatters/schema.ts
src/components/InfoViewer/schemaInfo/TableIndexInfo.tsx
src/components/InfoViewer/schemaInfo/i18n/en.json
src/components/InfoViewer/schemaInfo/i18n/index.ts
src/components/InfoViewer/schemaInfo/utils.ts
src/types/api/schema/tableIndex.ts

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2800
[Stand](https://nda.ya.ru/t/6jOXU3g97JjkCd)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2862/)
<details>
</details>
Current: 85.42 MB | Main: 85.42 MB
Diff: +6.74 KB (0.01%)
<details>
- …

feat: vector index parameters on Info tab

---

src/components/DebouncedInput/DebouncedNumerInput.tsx
src/components/DebouncedInput/DebouncedTextInput.tsx
src/components/Search/Search.tsx
src/containers/Tenant/Diagnostics/TopicData/TopicData.tsx
src/containers/Tenant/Diagnostics/TopicData/TopicDataControls/TopicDataControls.tsx
src/containers/Tenant/Diagnostics/TopicData/useTopicDataQueryParams.ts
src/utils/hooks/useDebouncedValue.ts

closes #2194
[Stand](https://nda.ya.ru/t/zrUyFkQI7JzSac)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2890/)
<details>
</details>
Current: 85.49 MB | Main: 85.45 MB
Diff: +0.04 MB (0.04%)
<details>
- Bundle size is measured for the entire 'dist' …

feat(TopicData): use number input for offset selection

---

src/containers/Tenant/Diagnostics/TenantOverview/MetricsTabs/MetricsTabs.tsx
src/containers/Tenant/Diagnostics/TenantOverview/MetricsTabs/components/NetworkTab.tsx

Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2904
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2905/)
<details>
</details>
Diff: 0.07 KB (-0.00%)
<details>
- 📊 …

fix: dont render network tab for clusters without network

---

src/containers/Tenant/Query/QueryResult/components/SimplifiedPlan/OperationCell.tsx

Before:
After:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2931/)
<details>
</details>
Diff: 0.05 KB (-0.00%)
<details>
- 🔺 indicates …

fix(OperationCell): layout

---

package-lock.json
package.json
src/containers/Tenant/Query/NewSQL/NewSQL.tsx

Closes #2906
Stand: https://nda.ya.ru/t/DYHxkQAC7Kj24Y
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2948/)
<details>
</details>
Current: 85.59 MB | Main: 85.59 MB
Diff: 3.00 KB (-0.00%)
<details>
- 📊 indicates …

fix(NewSQL): use the same icons as in schema tree

---

src/containers/Storage/Disks/Disks.tsx
src/containers/Storage/PDisk/PDisk.tsx
src/containers/Storage/VDisks/VDisks.tsx
src/containers/Storage/shared.tsx

Closes #2930
Stand (you need to turn on columns VDisks with PDisks): https://nda.ya.ru/t/kyq51ofu7Kj7fX
The problem was in different timeouts for `delayOpen` (100) and `delayClose` (200) in PDisk component, so the order of functions calls was wrong
1. `onShowPopup={() => setHighlightedVDisk(vDiskId)}`
2. `onHidePopup={() => setHighlightedVDisk(undefined)}`
So highlighted VDisk ID always was `undefined` after mouse entered another PDisk.
Introduced single constant for all disks popup in storage to fix this issue.
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2946/)
| 378 | 375 | 0 | 1 | 2 |
<details>
1. Scroll to row, get shareable link, …

fix(Disks): fix vdisk popup hiding

---

src/services/api/pdisk.ts
src/utils/developerUI/__test__/developerUI.test.ts
src/utils/developerUI/developerUI.ts
src/utils/hooks/useNodeDeveloperUIHref.ts
src/utils/prepareBackend.ts

Closes #2919
Cluster with `use_meta_proxy=true`: https://nda.ya.ru/t/_nh5uj-z7KjCKU
Cluster with `use_meta_proxy=false`: https://nda.ya.ru/t/QBZ2jrfT7KjCPq
We have developer UI links for cluster, nodes, VDisks, PDisks, tablets
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2949/)
<details>
</details>
Current: 85.59 MB | Main: 85.59 MB
Diff: +0.57 KB (0.00%)
<details> …

fix: fix developer ui links in cloud and em

---

src/components/InfoViewer/schemaInfo/TableIndexInfo.tsx
src/components/InfoViewer/schemaInfo/i18n/en.json
src/components/InfoViewer/schemaInfo/utils.ts
src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
src/containers/Tenant/ObjectSummary/ObjectSummary.tsx
src/containers/Tenant/i18n/en.json
src/containers/Tenant/utils/controls.tsx
src/containers/Tenant/utils/index.ts
src/containers/Tenant/utils/schema.ts
src/types/api/schema/schema.ts
src/types/api/schema/tableIndex.ts

📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2962/)
<details>
</details>
Current: 47.06 MB | Main: 47.05 MB
Diff: +0.01 MB (0.03%)
<details>
- 🔺 indicates …

feat(ui): support fulltext index
