ydb-platform/ydb-embedded-ui

src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.scss, src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.scss
In this PR I want to fix problems below:
Problem 1: when we view Diagnostic-details modal (in Database-Diagnostics-Overview-Healthcheck when it is something wrong with database), its height varies depends on content height, and it looks not good when modal's height jumps up and down.
Problem 2: in Database-Diagnostics-Overview-Healthcheck page title, badge and update-button should be centred.
=> fix(Diagnostics): layout

README.md
=> docs: correct a readme typo

src/containers/AsideNavigation/AsideNavigation.tsx
Aside navigation should be in compact mode by default
=> fix(AsideNavigation): aside header is compact by default

.github/workflows/ci.yml
Adds a TS check for CI.
The second commit is for demonstration, please ping me before approving so I can remove it.
=> ci: add typecheck action

.eslintrc, .github/workflows/ci.yml, .gitignore, config-overrides.js, package-lock.json, package.json, src/containers/Storage/DiskStateProgressBar/DiskStateProgressBar.tsx, src/containers/Storage/Pdisk/Pdisk.tsx, src/containers/Storage/Pdisk/__tests__/colors.tsx, src/containers/Storage/Vdisk/Vdisk.js, src/containers/Storage/Vdisk/__tests__/colors.tsx, src/index.test.js, src/setupTests.js, src/types/index.ts
This adds environment for running tests based on `jest` + `testing-library/react`, and configures it to run in CI.
This also adds two tests for PDisks and VDisks, covering the behavior I researched in #40.
=> tests with @testing-library/react

src/containers/Storage/StorageGroups/StorageGroups.scss
=> fix(Storage): shrink tooltip active area on Pool Name

src/containers/Tenant/QueryEditor/QueryEditor.scss, src/containers/Tenant/Tenant.scss, src/containers/Tenant/Tenant.tsx
This is virtually a part of #150, made a separate pull request since this is a fix that is need to be delivered. The rest of #150 is questionable and therefore will not be merged for some time.
=> fix(Tenant): fix layout after moving tabs

package-lock.json, package.json
This applies ydb-ui-components update with new icons: https://github.com/ydb-platform/ydb-ui-components/pull/40
=> chore: ydb-ui-components -> 3.0.1 - new icons

.eslintrc, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/utils/hooks/index.ts, src/utils/hooks/useAutofetcher.ts
the autofetcher code snippet repeats in modules
created a hook to reuse it
will use it in #182 
replaced it in Overview, but kept the other usages as is for now, as they require more careful refactoring
=> refactor: useAutofetcher hook

src/containers/Tenant/Diagnostics/Healthcheck/Details/Details.tsx, src/containers/Tenant/Diagnostics/Healthcheck/Details/index.ts, src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.scss, src/containers/Tenant/Diagnostics/Healthcheck/Healthcheck.tsx, src/containers/Tenant/Diagnostics/Healthcheck/IssuePreview/IssuePreview.tsx, src/containers/Tenant/Diagnostics/Healthcheck/IssuePreview/index.ts, src/containers/Tenant/Diagnostics/Healthcheck/IssuesList/IssuesList.tsx, src/containers/Tenant/Diagnostics/Healthcheck/IssuesList/index.ts, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssueTree.scss, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssueTree.tsx, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssueTreeItem/IssueTreeItem.scss, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssueTreeItem/IssueTreeItem.tsx, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssueTreeItem/index.ts, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssuesViewer.js, src/containers/Tenant/Diagnostics/Healthcheck/IssuesViewer/IssuesViewer.tsx, src/containers/Tenant/Diagnostics/Healthcheck/Preview/Preview.tsx, src/containers/Tenant/Diagnostics/Healthcheck/Preview/PreviewItem/PreviewItem.tsx, src/containers/Tenant/Diagnostics/Healthcheck/Preview/PreviewItem/index.ts, src/store/reducers/healthcheckInfo.js, src/store/reducers/healthcheckInfo.ts, src/store/utils.ts, src/types/api/healthcheck.ts, src/types/store/healthcheck.ts
Refactor some of the Healthcheck components and healthcheckInfo reducer moving issues tree creation logic to reducer and rewriting them to TS.
Inspired by @ariser comment https://github.com/ydb-platform/ydb-embedded-ui/pull/192#discussion_r994013742
=> refactor: Healthcheck issues

src/utils/prepareQueryExplain.ts
The current plan parsing was incomplete. This adds support for all paranoid node types.
=> fix(QueryExplain): apply all node types

package-lock.json, package.json
This fixes the bag of slow explain visualisation
=> chore: update @yandex-cloud/paranoid to 1.3.0

src/types/api/schema.ts
This fixes schema types from https://github.com/ydb-platform/ydb-embedded-ui/pull/218
=> chore: make some schema types optional

src/containers/Tablets/Tablets.tsx
Tablets component infinitely rerenders on empty tablets data as new array is set on every new render
=> fix(Tablets): fix infinite rerender

src/containers/Storage/DiskStateProgressBar/DiskStateProgressBar.scss, src/containers/Storage/DiskStateProgressBar/DiskStateProgressBar.tsx, src/containers/Storage/PDisk/PDisk.scss, src/containers/Storage/PDisk/PDisk.tsx, src/containers/Storage/StorageNodes/StorageNodes.scss, src/containers/Storage/StorageNodes/StorageNodes.tsx, src/containers/Storage/VDisk/VDisk.tsx, src/containers/Storage/VDiskPopup/VDiskPopup.tsx, src/store/reducers/storage.js, src/types/api/nodes.ts, src/types/api/vdisk.ts
based on #285
if reviewing before its merge, look only at the last commit
=> feat(Storage): display vdisks over pdisks

src/types/api/query.ts, src/utils/prepareQueryExplain.ts
=> chore: add query types

src/containers/Tenant/Schema/SchemaViewer/SchemaViewer.js
Add check marks for NotNull columns
=> fix(Schema): display NotNull columns

src/utils/tablet.ts
Frontend mapping should correspond to backend mapping
https://github.com/ydb-platform/ydb/blob/main/ydb/core/viewer/viewer.cpp#L490-L515
=> fix(Tablet): update state to color mapping

src/containers/Cluster/Cluster.tsx, src/containers/ClusterInfo/ClusterInfo.scss, src/containers/ClusterInfo/ClusterInfo.tsx, src/containers/Versions/GroupedNodesTree/GroupedNodesTree.scss, src/containers/Versions/GroupedNodesTree/GroupedNodesTree.tsx, src/containers/Versions/NodesTable/NodesTable.tsx, src/containers/Versions/NodesTreeTitle/NodesTreeTitle.scss, src/containers/Versions/NodesTreeTitle/NodesTreeTitle.tsx, src/containers/Versions/Versions.scss, src/containers/Versions/Versions.tsx, src/containers/Versions/groupNodes.ts, src/containers/Versions/types.ts, src/services/api.ts, src/store/reducers/clusterNodes/clusterNodes.tsx, src/store/reducers/clusterNodes/types.ts, src/store/reducers/index.ts, src/types/additionalProps.ts, src/types/versions.ts, src/utils/versions/getVersionsColors.ts, src/utils/versions/index.ts, src/utils/versions/parseNodesToVersionsValues.ts, src/utils/versions/parseVersion.ts
Add versions info to Cluster page
Versions previously was present only internally, so I highlighted changes, that I made to fit open-source ui
=> feat: add Versions

src/containers/Tenant/Diagnostics/Describe/Describe.tsx, src/containers/Tenant/Diagnostics/Diagnostics.tsx, src/containers/Tenant/Diagnostics/Overview/ChangefeedInfo/ChangefeedInfo.tsx, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/containers/Tenant/Diagnostics/TopShards/TopShards.tsx, src/containers/Tenant/ObjectSummary/ObjectSummary.tsx, src/containers/Tenant/Preview/Preview.js, src/containers/Tenant/QueryEditor/QueryEditor.js, src/containers/Tenant/Schema/SchemaTree/SchemaTree.tsx, src/containers/Tenant/Tenant.tsx, src/containers/Tenant/utils/schemaActions.ts, src/store/reducers/index.ts, src/store/reducers/schema/schema.ts, src/store/reducers/schema/types.ts
Just moved schema reducer and its types into schema sub folder and renamed types
=> refactor: move schema reducer, rename types

src/components/NodeHostWrapper/NodeHostWrapper.tsx, src/containers/App/Content.js, src/containers/AsideNavigation/AsideNavigation.tsx, src/containers/Cluster/Cluster.scss, src/containers/Cluster/Cluster.tsx, src/containers/Cluster/ClusterInfo/ClusterInfo.scss, src/containers/Cluster/ClusterInfo/ClusterInfo.tsx, src/containers/Cluster/ClusterInfoSkeleton/ClusterInfoSkeleton.scss, src/containers/Cluster/ClusterInfoSkeleton/ClusterInfoSkeleton.tsx, src/containers/Cluster/utils.ts, src/containers/Header/Header.scss, src/containers/Header/Header.tsx, src/containers/Node/Node.tsx, src/containers/Nodes/Nodes.tsx, src/containers/Nodes/getNodesColumns.tsx, src/containers/Storage/Storage.js, src/containers/Tablet/Tablet.tsx, src/containers/TabletsFilters/TabletsFilters.js, src/containers/Tenant/Tenant.tsx, src/containers/Tenants/Tenants.js, src/containers/Tenants/Tenants.scss, src/containers/Versions/Versions.scss, src/containers/Versions/Versions.tsx, src/routes.ts, src/services/api.ts, src/store/reducers/clusterNodes/clusterNodes.tsx, src/store/reducers/settings/settings.ts, src/utils/constants.ts, src/utils/nodes.ts
Breadcrumbs are not ready yet, it's an intermediary version
=> feat: rework navigation, update breadcrumbs

src/containers/Tenant/Diagnostics/DetailedOverview/DetailedOverview.scss, src/containers/Tenant/Diagnostics/Diagnostics.tsx, src/containers/Tenant/Diagnostics/Overview/ChangefeedInfo/ChangefeedInfo.tsx, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/containers/Tenant/Tenant.tsx, src/store/reducers/index.ts, src/store/reducers/overview/overview.ts, src/store/reducers/overview/types.ts, src/store/reducers/schema/schema.ts
After https://github.com/ydb-platform/ydb-embedded-ui/pull/419
=> fix(Diagnostics): remove unnneded tenantInfo fetch

src/containers/Cluster/Cluster.tsx
=> fix(Cluster): use counter from uikit for tabs

src/store/reducers/storage/storage.js
=> fix(Storage): remove visible entities filter

src/containers/Storage/StorageNodes/StorageNodes.tsx
=> fix(StorageNodes): sort by uptime

src/containers/Storage/UsageFilter/UsageFilter.scss, src/containers/Storage/UsageFilter/UsageFilter.tsx
Added `z-index`. Other changes - prettier or variables renaming
=> fix(UsageFilter): fix bar flashes

src/components/EntityStatus/EntityStatus.js, src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.js, src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.scss
=> fix(TenantOverview): add copy button to tenant name

src/containers/AsideNavigation/AsideNavigation.tsx
=> fix(AsideNavigation): replace query icon

src/containers/Cluster/ClusterInfo/ClusterInfo.tsx, src/containers/Cluster/ClusterInfoSkeleton/ClusterInfoSkeleton.tsx
=> fix(ClusterInfo): add Databases field

src/components/Tablet/Tablet.scss, src/utils/constants.ts
=> fix: fix tablet size

src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.scss, src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx, src/containers/Tenant/Query/i18n/en.json, src/containers/Tenant/Query/i18n/ru.json
=> feat(Query): add explanation to the query method selector

src/components/InfoViewer/formatters/common.ts, src/components/InfoViewer/i18n/en.json, src/components/InfoViewer/i18n/index.ts, src/components/InfoViewer/i18n/ru.json, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/containers/Tenant/Info/ExternalDataSource/ExternalDataSource.scss, src/containers/Tenant/Info/ExternalDataSource/ExternalDataSource.tsx, src/containers/Tenant/Info/ExternalTable/ExternalTable.scss, src/containers/Tenant/Info/ExternalTable/ExternalTable.tsx, src/containers/Tenant/Info/i18n/en.json, src/containers/Tenant/Info/i18n/index.ts, src/containers/Tenant/Info/i18n/ru.json, src/containers/Tenant/ObjectSummary/ObjectSummary.scss, src/containers/Tenant/ObjectSummary/ObjectSummary.tsx, src/index.js, src/styles/constants.scss
**External Table Info**
**External Table Overview (Summary)**
**External Data Source Info**
**External Data Source Overview (Summary)**
=> feat: info and summary tabs for external objects

src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.scss, src/containers/Tenant/Query/i18n/en.json, src/containers/Tenant/Query/i18n/ru.json
=> fix(Query): transfer API calls to a new line

src/containers/Tenant/Query/QueryDuration/QueryDuration.scss, src/containers/Tenant/Query/QueryDuration/QueryDuration.tsx, src/containers/Tenant/Query/i18n/en.json, src/containers/Tenant/Query/i18n/ru.json
=> feat(Query): add explanation to query duration

src/containers/Tenant/Query/i18n/en.json
=> fix(Query): fix query method selector help text

src/containers/Nodes/Nodes.tsx, src/containers/Nodes/getNodesColumns.tsx, src/containers/UserSettings/i18n/en.json, src/containers/UserSettings/i18n/ru.json, src/containers/UserSettings/settings.ts, src/services/api.ts, src/store/reducers/nodes/nodes.ts, src/store/reducers/nodes/selectors.ts, src/store/reducers/nodes/types.ts, src/store/reducers/settings/settings.ts, src/types/api/compute.ts, src/types/api/nodes.ts, src/utils/constants.ts, src/utils/filters.ts, src/utils/hooks/index.ts, src/utils/hooks/useNodesRequestParams.ts, src/utils/hooks/useTableSort.ts, src/utils/nodes.ts
=> feat(Nodes): filter and sort on backend

src/components/Tablet/Tablet.scss, src/components/Tablet/Tablet.tsx, src/components/TabletIcon/TabletIcon.scss, src/components/TabletIcon/TabletIcon.tsx, src/components/TabletIcon/index.ts, src/containers/Header/Header.scss, src/containers/Header/Header.tsx, src/containers/Header/breadcrumbs.tsx, src/containers/Tablet/Tablet.tsx, src/store/reducers/header/types.ts
=> fix(Header): add icons for nodes and tablets

src/store/reducers/settings/settings.ts
=> fix(Nodes): use nodes endpoint by default

src/containers/Tenant/Diagnostics/DetailedOverview/DetailedOverview.tsx, src/containers/UserSettings/i18n/en.json, src/containers/UserSettings/i18n/ru.json, src/containers/UserSettings/settings.ts, src/store/reducers/settings/settings.ts, src/utils/constants.ts
=> fix: rename flag for display metrics cards for database diagnostics

src/containers/AsideNavigation/AsideNavigation.tsx, src/containers/Authentication/Authentication.tsx
Fix the bug with `Authentication`. When user logins manually, after login click page doesn't redirect to the initial url
=> fix(Authentication): enable page redirect

src/components/FullNodeViewer/FullNodeViewer.scss, src/components/FullNodeViewer/FullNodeViewer.tsx
=> fix: display database name in node info

src/containers/AsideNavigation/AsideNavigation.tsx, src/containers/AsideNavigation/i18n/en.json, src/containers/AsideNavigation/i18n/index.ts, src/containers/AsideNavigation/i18n/ru.json
=> chore(AsideNavigation): add i18n

src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByCpu.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopNodesByLoad.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopQueries.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/TopShards.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantMemory/TopNodesByMemory.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantOverviewTableLayout.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopGroups.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopTables.tsx, src/containers/Tenant/Diagnostics/TenantOverview/getSectionTitle.tsx, src/containers/Tenant/Diagnostics/TenantOverview/i18n/en.json, src/containers/Tenant/Diagnostics/TenantOverview/i18n/ru.json, src/utils/hooks/index.ts, src/utils/hooks/useSearchQuery.ts
Add links to other tabs to table titles in DB diagnostics
=> feat(TenantOverview): add links to sections titles

README.md, ROADMAP.md
Would like to add public roadmap in a separate file
Currently embedded ui roadmap is in ydb/ROADMAP.md
=> docs: added initial roadmap version

CHANGELOG.md, package-lock.json, package.json
Reverts ydb-platform/ydb-embedded-ui#670
=> Revert "chore(main): release 4.31.0"

.github/workflows/release.yml
Based on https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md.
=> chore: add last release SHA

src/containers/Tenant/Diagnostics/TopQueries/getTopQueriesColumns.tsx
=> chore(TopQueries): convert duration to milliseconds

src/components/EntityStatus/EntityStatus.scss, src/components/LagImages/LagImages.tsx, src/components/TabletsOverall/TabletsOverall.tsx, src/containers/AppIcons/AppIcons.js, src/containers/Versions/NodesTreeTitle/NodesTreeTitle.scss, src/utils/versions/getVersionsColors.ts
Somehow some of the colors weren't updated on uikit5 update
=> chore: update colors vars

src/components/FullNodeViewer/FullNodeViewer.tsx, src/store/reducers/node/types.ts, src/store/reducers/node/utils.ts, src/store/reducers/nodes/utils.ts, src/store/reducers/storage/utils.ts, src/utils/nodes.ts
Din nodes don't have Rack in Location filed, but may have separate Rack field
=> fix: display rack for din nodes

src/components/MetricChart/getDefaultDataFormatter.ts, src/components/MetricChart/types.ts, src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/cpuDashboardConfig.ts, src/containers/Tenant/Diagnostics/TenantOverview/i18n/en.json
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/751
=> feat(TenantOverview): display per pool cpu usage on chart

package-lock.json, package.json, src/components/MetricChart/MetricChart.tsx, src/components/MetricChart/colors.ts
Make Grafana-styled area charts
Before:
After:
=> fix(MetricChart): draw area charts

src/components/MetricChart/MetricChart.tsx, src/components/MetricChart/types.ts, src/containers/Tenant/Diagnostics/TenantOverview/TenantCpu/cpuDashboardConfig.ts
=> fix(MetricChart): zero min value

package-lock.json, package.json, src/components/MetricChart/MetricChart.tsx
=> fix(MetricChart): spanGaps

src/components/DiskPageTitle/DiskPageTitle.scss, src/components/DiskPageTitle/DiskPageTitle.tsx, src/components/EntityStatus/EntityStatus.scss, src/components/EntityStatus/EntityStatus.tsx, src/components/ProgressViewer/ProgressViewer.tsx, src/components/StatusIcon/StatusIcon.scss, src/components/StatusIcon/StatusIcon.tsx, src/containers/Tenant/Diagnostics/TenantOverview/Healthcheck/Healthcheck.scss, src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricCard/MetricCard.scss, src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricCard/MetricCard.tsx, src/containers/Tenant/Diagnostics/TenantOverview/MetricsCards/MetricsCards.tsx, src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx, src/containers/Tenant/Diagnostics/TenantOverview/i18n/en.json, src/store/reducers/tenants/contants.ts, src/store/reducers/tenants/utils.ts, src/types/api/tenant.ts
=> feat(TenantOverview): bars instead of circles

src/components/EntityStatus/EntityStatus.scss, src/components/EntityStatus/EntityStatus.tsx, src/components/NodeHostWrapper/NodeHostWrapper.scss, src/components/NodeHostWrapper/NodeHostWrapper.tsx, src/containers/Tenants/Tenants.scss, src/containers/Tenants/Tenants.tsx
=> fix: fix buttons incorrect align in Nodes and Tenants tables

.github/workflows/ci.yml
=> chore: check build on PR

src/store/reducers/tenants/utils.ts
=> fix: use soft quota for tenant storage

src/containers/Tenant/Query/ExplainResult/ExplainResult.js
=> fix: fix ast always light theme

README.md
Destination folder for embedded-ui build is changed. Updated it in readme
=> docs: update monitoring folder

src/components/BasicNodeViewer/BasicNodeViewer.tsx
Closes #664 
Test stand: https://nda.ya.ru/t/ogVO_pdV76BqhE
=> feat(Node): add developer ui link for embedded version

src/containers/UserSettings/Setting.tsx, src/containers/UserSettings/UserSettings.tsx, src/containers/UserSettings/i18n/en.json, src/containers/UserSettings/settings.tsx
Closes #881 
Test stand: https://nda.ya.ru/t/HLJ7cYQE76JeUa
=> feat(UserSettings): display app version

src/containers/Tenant/Diagnostics/DiagnosticsPages.ts
=> feat(Diagnostics): add tablets tab to all entities with tablets

package-lock.json, package.json, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/containers/Tenant/Info/View/View.scss, src/containers/Tenant/Info/View/View.tsx, src/containers/Tenant/Info/i18n/en.json, src/containers/Tenant/Info/i18n/index.ts, src/containers/Tenant/Info/i18n/ru.json
Closes #785 
Test stand: https://nda.ya.ru/t/pL9f8HBJ76Pn3m
=> feat(Overview): add view info

CHANGELOG.md, package-lock.json, package.json, src/containers/App/App.scss, src/containers/AppWithClusters/ExtendedTenant/ExtendedTenant.tsx, src/containers/Tenant/utils/schema.ts, src/index.tsx, src/lib.ts, src/styles/constants.scss, src/types/api/tenant.ts, src/utils/__test__/monitoring.test.ts, src/utils/monitoring.ts, tsconfig.package.json
It should fix ydb-embedded-ui npm package
=> fix: revert release, fix package

src/containers/Storage/StorageGroups/getStorageGroupsColumns.tsx
=> fix: expand the column 'degraded' width

src/containers/Tenant/i18n/en.json, src/containers/Tenant/utils/queryTemplates.ts, src/containers/Tenant/utils/schemaActions.ts
=> feat: add action "Create async replication"

src/components/InfoViewer/InfoViewer.tsx, src/components/InfoViewer/i18n/en.json, src/components/InfoViewer/i18n/index.ts, src/components/InfoViewer/i18n/ru.json, src/containers/Tenant/Diagnostics/Overview/TableInfo/TableInfo.tsx, src/containers/Tenant/EntityTitle/EntityTitle.tsx, src/containers/Tenant/ObjectSummary/ObjectSummary.tsx, src/containers/Tenant/i18n/en.json, src/containers/Tenant/utils/index.ts, src/types/api/schema/schema.ts
=> feat: add ReadOnly label to replicated tables

src/components/VDisk/VDisk.tsx, src/containers/Storage/PDisk/PDisk.tsx, src/containers/UserSettings/i18n/en.json, src/containers/UserSettings/settings.tsx, src/services/settings.ts, src/utils/constants.ts, src/utils/disks/prepareDisks.ts
=> feat(UserSettings): add setting for separate disks pages

src/containers/Heatmap/Histogram/Histogram.js, src/containers/Heatmap/util.js
=> fix(Graph): fix broken tab for column tables

src/components/DeveloperUiLink/DeveloperUiLink.scss, src/components/DeveloperUiLink/DeveloperUiLink.tsx, src/components/NodeHostWrapper/NodeHostWrapper.tsx, src/containers/Tablets/Tablets.tsx, src/containers/Tenant/Diagnostics/TopShards/getTopShardsColumns.tsx
For hosts:
For tablets:
For top shards:
=> feat: show developer ui links for hosts and tablets

public/index.html, src/containers/Tenant/Diagnostics/TopQueries/getTopQueriesColumns.tsx, src/containers/Tenant/Diagnostics/TopShards/TopShards.tsx, src/store/reducers/executeTopQueries/executeTopQueries.ts, src/utils/diagnostics.ts
=> feat: add data sorting to TopQueries table

src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx, src/types/api/schema/schema.ts
=> fix(TenantOverview): add correct tablet storage value

src/components/DateRange/i18n/index.ts, src/components/DateRange/i18n/ru.json
I suppose we may need it some time
=> fix: ru.json for datepicker

src/containers/PDiskPage/PDiskPage.scss, src/containers/PDiskPage/PDiskPage.tsx
=> fix(PDiskPage): move autorefresh to meta level

package-lock.json, package.json, src/containers/Tenant/Query/QueryEditor/QueryEditor.tsx, src/containers/Tenant/Query/QueryEditorControls/QueryEditorControls.tsx, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.scss, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.tsx, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsSelect.scss, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsSelect.tsx, src/containers/Tenant/Query/QuerySettingsDialog/constants.ts, src/containers/Tenant/Query/QuerySettingsDialog/i18n/en.json, src/containers/Tenant/Query/QuerySettingsDialog/i18n/index.ts, src/containers/Tenant/Query/QuerySettingsDialog/i18n/ru.json, src/containers/Tenant/Query/i18n/en.json, src/containers/UserSettings/i18n/en.json, src/containers/UserSettings/settings.tsx, src/services/settings.ts, src/store/reducers/queryActions/types.ts, src/types/store/query.ts, src/utils/constants.ts, src/utils/query.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1051
Please Turn Experiment ON via browser console before testing!
[Stand](https://nda.ya.ru/t/nVj9fVHT779HGk)
Please Turn Experiment OFF via browser console after testing!
to turn experiment ON use
```
localStorage.setItem('query_settings', true);
window.location.reload()
```
to turn experiment OFF use
```
localStorage.setItem('query_settings', false);
window.location.reload()
```
=> Query settings dialog and settings usage in requests

.github/workflows/ci.yml, .github/workflows/pr-title.yml
=> chore: check PR title instead of commits

src/components/ButtonWithConfirmDialog/ButtonWithConfirmDialog.tsx, src/components/CriticalActionDialog/CriticalActionDialog.scss, src/components/CriticalActionDialog/CriticalActionDialog.tsx, src/components/CriticalActionDialog/i18n/en.json, src/containers/PDiskPage/PDiskPage.tsx, src/containers/PDiskPage/i18n/en.json, src/services/api.ts, src/types/api/restartPDisk.ts
Closes #862 
Stand: https://nda.ya.ru/t/hIN2BpU977Fib5
How to check:
1) Turn on experiment "Use separate PDisk and VDisk pages"
2) Go to cluster storage tab, select nodes
3) Open PDisks with the same id (e.g. 1002) on different nodes
4) Try to restart two or more disks at once, on the second or third there will be an error
=> feat(PDiskPage): add force restart

.github/workflows/ci.yml
**Status**: <span style="color: green; font-weight: bold;">✅ PASSED</span>
| Total | Passed | Failed | Skipped |
|-------|--------|--------|---------|
| 38 | 38 | 0 | 0 |
For detailed results, please check the [Playwright Report](https://ydb-platform.github.io/ydb-embedded-ui/1106/)
Video recordings of failed tests (if any) are available in the report.
---
<details>
<summary>ℹ️ How to use this report</summary>
1. Click on the "Playwright Report" link above to view the full test results.
2. In the report, you can see a breakdown of all tests, including any failures.
3. For failed tests, you can view screenshots and video recordings to help debug the issues.
4. Use the filters in the report to focus on specific test statuses or suites.
</details>
=> feat: move test reports

.github/workflows/ci.yml, playwright.config.ts
**Status**: <span style="color: green; font-weight: bold;">✅ PASSED</span>
| Total | Passed | Failed | Skipped |
|-------|--------|--------|---------|
| 38 | 38 | 0 | 0 |
For detailed results, please check the [Playwright Report](https://ydb-platform.github.io/ydb-embedded-ui/1108/)
Video recordings of failed tests (if any) are available in the report.
---
<details>
<summary>ℹ️ How to use this report</summary>
1. Click on the "Playwright Report" link above to view the full test results.
2. In the report, you can see a breakdown of all tests, including any failures.
3. For failed tests, you can view screenshots and video recordings to help debug the issues.
4. Use the filters in the report to focus on specific test statuses or suites.
</details>
=> fix: tests not running

.github/workflows/ci.yml
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1109/)
| 38 | 38 | 0 | 0 | 0 |
Current: 78.91 MB | Main: 78.91 MB
<details>
</details>
=> feat: add flaky tests and bundle size

src/containers/Tenant/Query/ExecuteResult/ExecuteResult.tsx, src/containers/Tenant/Query/ExecuteResult/i18n/en.json, src/containers/Tenant/Query/ExecuteResult/utils.ts, src/containers/Tenant/Query/ExplainResult/ExplainResult.tsx, src/containers/Tenant/Query/ExplainResult/components/SimplifiedPlan/OperationParams.tsx, src/containers/Tenant/Query/ExplainResult/i18n/en.json, src/containers/Tenant/Query/utils/getPreparedResult.ts, src/store/reducers/explainQuery/types.ts, src/store/reducers/explainQuery/utils.ts, src/utils/dataFormatters/dataFormatters.ts
closes #888
Stand https://nda.ya.ru/t/K3fT0HvW77PLof
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1113/)
| 44 | 41 | 0 | 3 | 0 |
Current: 78.86 MB | Main: 78.85 MB
<details>
</details>
=> feat: copy json query stats

src/containers/Tenants/Tenants.tsx, src/services/api.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1121/)
<details>
</details>
=> feat: remove tablets column from databases table

src/containers/Tenant/Diagnostics/Consumers/Consumers.tsx, src/containers/Tenant/Diagnostics/Diagnostics.tsx, src/containers/Tenant/Diagnostics/Overview/ChangefeedInfo/ChangefeedInfo.tsx, src/containers/Tenant/Diagnostics/Overview/Overview.tsx, src/containers/Tenant/Diagnostics/Overview/TopicInfo/TopicInfo.tsx, src/containers/Tenant/Diagnostics/Overview/TopicStats/TopicStats.tsx, src/containers/Tenant/Diagnostics/Partitions/Partitions.tsx, src/services/api.ts, src/store/reducers/partitions/partitions.ts, src/store/reducers/topic.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1128/)
| 62 | 62 | 0 | 0 | 0 |
Current: 78.88 MB | Main: 78.88 MB
<details>
</details>
=> fix: pass database to topic api handlers

.github/workflows/ci.yml, playwright.config.ts, tests/playwrightSetup.ts, tsconfig.package.json
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1129/)
| 62 | 60 | 0 | 2 | 0 |
Current: 78.88 MB | Main: 78.88 MB
<details>
</details>
=> fix: package build

src/store/reducers/authentication/authentication.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1139/)
| 70 | 68 | 0 | 2 | 0 |
Current: 78.89 MB | Main: 78.89 MB
Diff: +0.15 KB (0.00%)
<details>
</details>
=> fix: do not show Authentication page before redirect

src/containers/Tenant/Query/Preview/Preview.scss
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1162/)
| 70 | 68 | 0 | 2 | 0 |
Diff: 0.33 KB (-0.00%)
<details>
</details>
=> fix(Preview): remove wrong and stale styles

src/store/reducers/overview/overview.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1161
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1163/)
| 70 | 70 | 0 | 0 | 0 |
Diff: +0.07 KB (0.00%)
<details>
</details>
=> fix: autorefresh control doesnt update info tab in diagnostics

README.md, src/containers/Tenant/Tenant.tsx, tests/suites/tenant/initialLoad.test.ts, tests/utils/constants.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1167/)
| 78 | 75 | 0 | 3 | 0 |
Diff: +0.31 KB (0.00%)
<details>
</details>
=> fix(Tenant): fix infinite load if describe returns empty data

src/containers/Tenant/Diagnostics/Describe/Describe.scss, src/containers/Tenant/Diagnostics/Describe/Describe.tsx
[Stand](https://nda.ya.ru/t/BNeQFKTt77h3Ei)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1192/)
| 114 | 113 | 0 | 1 | 0 |
Diff: +0.81 KB (0.00%)
<details>
</details>
=> feat(Describe): add button to copy content to clipboard

src/containers/Nodes/Nodes.tsx, src/containers/Nodes/NodesWrapper.tsx, src/containers/Nodes/PaginatedNodes.tsx, src/containers/Nodes/getNodes.ts, src/containers/Storage/PaginatedStorage.tsx, src/containers/Storage/Storage.tsx, src/containers/Storage/StorageGroups/PaginatedStorageGroups.tsx, src/containers/Storage/StorageGroups/getGroups.ts, src/containers/Storage/StorageNodes/PaginatedStorageNodes.tsx, src/containers/Storage/StorageNodes/getNodes.ts, src/containers/Storage/StorageWrapper.tsx, src/containers/Tenant/Diagnostics/Diagnostics.tsx, src/services/api.ts, src/store/reducers/nodes/types.ts, src/store/reducers/storage/types.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1197/)
| 114 | 111 | 0 | 3 | 0 |
Diff: +1.00 KB (0.00%)
<details>
</details>
=> fix(Nodes): pass database param to nodes api handler

src/containers/Tablet/Tablet.tsx, src/containers/Tablet/components/TabletControls/TabletControls.tsx, src/containers/Tablets/Tablets.tsx, src/services/api.ts, src/store/reducers/api.ts, src/store/reducers/header/types.ts, src/store/reducers/index.ts, src/store/reducers/tablet.ts, src/store/reducers/tablets.ts, tsconfig.json
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1195/)
| 114 | 111 | 0 | 3 | 0 |
Current: 79.03 MB | Main: 79.00 MB
Diff: +0.03 MB (0.03%)
<details>
</details>
=> refactor: tablet page

src/containers/Tenants/Tenants.tsx, src/store/reducers/tenants/selectors.ts
There is only one database in our test base so for now there is no possibility to write test for this bug
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1206/)
| 120 | 115 | 0 | 5 | 0 |
Current: 79.04 MB | Main: 79.04 MB
Diff: +0.05 KB (0.00%)
<details>
</details>
=> fix: incorrect database count with hidden root

src/services/api.ts, src/utils/constants.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1218/)
| 120 | 115 | 0 | 5 | 0 |
Current: 78.83 MB | Main: 78.83 MB
Diff: +0.99 KB (0.00%)
<details>
</details>
=> feat: add setting to add tracing to all requests

src/store/state-url-mapping.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1227/)
| 124 | 119 | 0 | 5 | 0 |
Current: 78.83 MB | Main: 78.83 MB
Diff: 0.43 KB (-0.00%)
<details>
</details>
=> fix(store): remove unused params from url mapping

src/containers/Tenant/Query/QueryEditorControls/utils/getChangedQueryExecutionSettings.test.ts, src/containers/Tenant/Query/QueryEditorControls/utils/getChangedQueryExecutionSettingsDescription.test.ts, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsDialog.tsx, src/containers/Tenant/Query/QuerySettingsDialog/QuerySettingsSelect.tsx, src/containers/Tenant/Query/QuerySettingsDialog/constants.ts, src/containers/Tenant/Query/QuerySettingsDialog/i18n/en.json, src/containers/Tenant/Query/QuerySettingsDialog/i18n/ru.json, src/containers/Tenant/Query/i18n/en.json, src/services/api.ts, src/store/reducers/executeQuery.ts, src/store/reducers/explainQuery/explainQuery.ts, src/types/api/query.ts, src/types/store/query.ts, src/utils/constants.ts, src/utils/hooks/useLastQueryExecutionSettings.ts, src/utils/hooks/useQueryExecutionSettings.ts, src/utils/query.ts, tests/suites/tenant/queryEditor/QueryEditor.ts, tests/suites/tenant/queryEditor/queryEditor.test.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1239
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1240/)
| 124 | 119 | 0 | 5 | 0 |
Current: 78.84 MB | Main: 78.84 MB
<details>
</details>
=> fix: add implicit transaction_mode to query settings

src/containers/Tenant/Diagnostics/TopShards/TopShards.tsx
Closes #1244
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1245/)
Current: 78.84 MB | Main: 78.84 MB
<details>
</details>
=> fix(TopShards): fix data update on schema object change

src/components/PaginatedTable/PaginatedTable.scss, src/components/PaginatedTable/PaginatedTable.tsx, src/components/PaginatedTable/ResizeablePaginatedTable.tsx, src/components/PaginatedTable/TableChunk.tsx, src/components/PaginatedTable/TableHead.tsx, src/components/PaginatedTable/TableRow.tsx, src/components/PaginatedTable/types.ts, src/components/TableWithControlsLayout/TableWithControlsLayout.scss
Closes #729 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1234/)
Current: 78.84 MB | Main: 78.84 MB
<details>
</details>
=> fix(PaginatedTable): fix table overflow, make column width optional

src/containers/Tablet/Tablet.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1254/)
Current: 78.87 MB | Main: 78.88 MB
Diff: 0.01 MB (-0.02%)
<details>
</details>
=> fix(Tablet): preserve query params when switch tabs

src/services/api.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1263/)
| 124 | 121 | 1 | 2 | 0 |
Current: 78.92 MB | Main: 78.92 MB
Diff: +0.89 KB (0.00%)
<details>
</details>
=> fix: better retry timeout for traces

src/containers/AsideNavigation/AsideNavigation.tsx, src/containers/AsideNavigation/Navigation.tsx, src/containers/AsideNavigation/YdbInternalUser/YdbInternalUser.tsx, src/lib.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1262/)
Current: 78.92 MB | Main: 78.92 MB
<details>
</details>
=> feat(package): export AsideNavigation

src/components/GroupInfo/GroupInfo.tsx, src/containers/Storage/Storage.tsx, src/containers/Storage/StorageGroups/columns/getStorageGroupsColumns.tsx, src/containers/Storage/StorageGroups/getGroups.ts, src/containers/Storage/utils/index.ts, src/services/api.ts, src/store/reducers/nodes/nodes.ts, src/store/reducers/pdisk/pdisk.ts, src/store/reducers/storage/selectors.ts, src/store/reducers/storage/storage.ts, src/store/reducers/storage/types.ts, src/store/reducers/storage/utils.ts, src/store/reducers/tenantOverview/topStorageGroups/topStorageGroups.ts, src/store/reducers/vdisk/vdisk.ts, src/types/api/capabilities.ts, src/types/api/compute.ts, src/types/api/pdisk.ts, src/types/api/storage.ts, src/types/api/vdisk.ts, src/utils/disks/helpers.ts, src/utils/storage.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1273/)
| 124 | 117 | 1 | 6 | 0 |
Current: 78.93 MB | Main: 78.94 MB
<details>
</details>
=> feat: add storage/groups endpoint

src/containers/Tenant/utils/queryTemplates.ts
Closes #866
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1284/)
<details>
</details>
=> fix: update alter table query template

src/containers/Tenant/Diagnostics/Diagnostics.tsx, src/containers/Tenant/Diagnostics/DiagnosticsPages.ts, src/store/reducers/capabilities/hooks.ts, src/types/api/capabilities.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1308/)
Current: 78.96 MB | Main: 78.96 MB
Diff: +0.98 KB (0.00%)
<details>
</details>
=> fix: check feature flag api is available

src/containers/PDiskPage/PDiskGroups/PDiskGroups.tsx, src/containers/Storage/PaginatedStorage.tsx, src/containers/Storage/StorageGroups/PaginatedStorageGroups.tsx, src/containers/Storage/StorageGroups/StorageGroups.tsx, src/containers/Storage/StorageGroups/columns/columns.tsx, src/containers/Storage/StorageGroups/columns/constants.ts, src/containers/Storage/StorageGroups/columns/hooks.ts, src/containers/Storage/StorageGroups/columns/i18n/en.json, src/containers/Storage/StorageGroups/columns/i18n/index.ts, src/containers/Storage/StorageNodes/PaginatedStorageNodes.tsx, src/containers/Storage/StorageNodes/StorageNodes.scss, src/containers/Storage/StorageNodes/StorageNodes.tsx, src/containers/Storage/StorageNodes/columns/StorageNodesColumns.scss, src/containers/Storage/StorageNodes/columns/columns.tsx, src/containers/Storage/StorageNodes/columns/constants.ts, src/containers/Storage/StorageNodes/columns/hooks.ts, src/containers/Storage/StorageNodes/columns/i18n/en.json, src/containers/Storage/StorageNodes/columns/i18n/index.ts, src/containers/Storage/StorageNodes/columns/types.ts, src/containers/Storage/StorageNodes/shared.ts, src/containers/Tenant/Diagnostics/TenantOverview/TenantStorage/TopGroups.tsx, src/containers/VDiskPage/VDiskPage.tsx, src/types/api/storage.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1317/)
| 124 | 118 | 2 | 4 | 0 |
Current: 78.97 MB | Main: 78.96 MB
<details>
</details>
=> refactor: split storage columns files, update types

src/containers/Nodes/Nodes.tsx, src/containers/Nodes/PaginatedNodes.tsx, src/containers/Nodes/columns/columns.tsx, src/containers/Nodes/columns/constants.ts, src/containers/Nodes/columns/hooks.ts
Closes: #1319
Stand: https://nda.ya.ru/t/0fhk33st78MARt
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1320/)
| 124 | 114 | 0 | 10 | 0 |
Current: 78.99 MB | Main: 78.98 MB
Diff: +0.01 MB (0.02%)
<details>
</details>
=> feat(Nodes): add columns setup

src/containers/App/App.scss, src/styles/mixins.scss
=> style: tune orange color

src/components/QueryResultTable/Cell/Cell.tsx, src/containers/ReduxTooltip/ReduxTooltip.js
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1315
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1354/)
Diff: 0.15 KB (-0.00%)
<details>
</details>
=> feat: big query results freeze interface

src/containers/Storage/PaginatedStorage.tsx, src/containers/Storage/Storage.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1350/)
| 124 | 121 | 1 | 2 | 0 |
Diff: +0.06 KB (0.00%)
<details>
</details>
=> fix(Storage): fix additional props not passed

src/containers/Storage/PDisk/PDisk.tsx, src/containers/Storage/StorageNodes/columns/columns.tsx
Closes #1348 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1352/)
| 124 | 123 | 0 | 1 | 0 |
Current: 79.06 MB | Main: 79.06 MB
Diff: +0.08 KB (0.00%)
<details>
</details>
=> fix(PDisk): show node host name in popup

src/containers/Storage/PDisk/PDisk.scss, src/containers/Storage/Storage.tsx, src/containers/Storage/StorageGroups/StorageGroupsTable.tsx, src/containers/Storage/StorageNodes/StorageNodesTable.tsx, src/containers/Storage/StorageNodes/columns/StorageNodesColumns.scss
=> fix(StorageNodes): uniform render type

src/utils/hooks/useSelectedColumns.ts
Closes #1371 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1374/)
Diff: +0.75 KB (0.00%)
<details>
</details>
=> fix: always show required columns

src/components/PDiskPopup/PDiskPopup.tsx, src/components/VDisk/VDisk.tsx, src/components/VDiskPopup/VDiskPopup.tsx, src/containers/Storage/Disks/Disks.tsx, src/containers/Storage/PDisk/PDisk.tsx, src/containers/Storage/PaginatedStorageGroups.tsx, src/containers/Storage/Storage.tsx, src/containers/Storage/StorageGroups/columns/columns.tsx, src/containers/Storage/StorageGroups/columns/hooks.ts, src/containers/Storage/StorageGroups/columns/types.ts, src/containers/Storage/StorageNodes/columns/columns.tsx, src/containers/Storage/utils/index.ts, src/containers/Tenant/Diagnostics/Partitions/Partitions.tsx, src/containers/Tenant/Diagnostics/Partitions/utils/index.ts, src/store/reducers/nodesList.ts, src/store/reducers/tablet.ts, src/store/reducers/tablets.ts, src/types/store/nodesList.ts, src/utils/nodes.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1361
[Stand](http://ydb-vla-dev02-005.search.yandex.net:8765/monitoring/tenant?tenantPage=diagnostics&diagnosticsTab=topQueries&topQueriesDateFrom=1721228339103&topQueriesDateTo=1721314739103&selectedConsumer=&name=%2Fdev02&clckid=5cd66065)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1369/)
<details>
- 🔺 …
=> feat: dim vdisks on the node page that are not on the selected node

src/utils/utils.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1377
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1381/)
Diff: +0.07 KB (0.00%)
<details>
</details>
=> fix: different measurements look confusing

src/containers/Nodes/columns/columns.tsx, src/containers/Nodes/columns/constants.ts, src/containers/Nodes/columns/i18n/en.json, src/store/reducers/nodes/types.ts, src/types/api/nodes.ts
Closes #1205 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1385/)
| 124 | 123 | 0 | 1 | 0 |
Diff: +0.81 KB (0.00%)
<details>
</details>
=> feat(Nodes): add node name column

src/containers/Tablet/components/TabletStorageInfo/TabletStorageInfo.scss
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1400/)
Diff: 0.39 KB (-0.00%)
<details>
</details>
=> style(TabletStorageInfo): fix cell align

src/components/VDisk/VDisk.tsx, src/components/VDiskInfo/VDiskInfo.tsx, src/components/VDiskPopup/VDiskPopup.tsx, src/containers/Storage/Disks/Disks.tsx, src/containers/Storage/PDisk/PDisk.tsx, src/containers/Storage/StorageGroups/columns/columns.tsx, src/containers/VDiskPage/VDiskPage.tsx, src/store/reducers/storage/utils.ts, src/utils/disks/prepareDisks.ts, src/utils/disks/types.ts
Closes #1362 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1420/)
| 128 | 121 | 1 | 6 | 0 |
Diff: +0.20 KB (0.00%)
<details>
</details>
=> fix(Storage): prevent duplicating vdisks when no whiteboard

src/containers/Tenant/Query/QuerySettingsDialog/constants.ts, src/utils/query.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1431
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1432/)
| 128 | 126 | 0 | 2 | 0 |
Diff: 0.01 KB (-0.00%)
<details>
</details>
=> fix: tracelevel none by default

src/containers/Tenant/Query/ExplainResult/components/SimplifiedPlan/SimplifiedPlan.scss
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1441/)
| 128 | 126 | 0 | 2 | 0 |
<details>
</details>
=> style(SimplidiedPlan): fix padding

src/containers/Storage/PaginatedStorageGroups.tsx, src/containers/Storage/PaginatedStorageNodes.tsx
Do not display control on ydb versions without grouping
=> fix(Storage): do not display group control if not available

package-lock.json, package.json
=> chore: use browserslist config from gravity-ui

src/containers/Tenant/Schema/SchemaViewer/columns.tsx, src/containers/Tenant/Schema/SchemaViewer/prepareData.ts, src/containers/Tenant/Schema/SchemaViewer/types.ts, src/containers/Tenant/Schema/SchemaViewer/utils.ts, src/types/api/schema/columnEntity.ts, src/types/api/schema/tableIndex.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1477
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1478/)
Current: 78.96 MB | Main: 78.95 MB
Diff: +0.00 MB (0.01%)
<details>
</details>
=> fix: correct key columns order

src/containers/Cluster/ClusterInfo/utils.tsx, src/containers/Versions/Versions.tsx, src/containers/Versions/utils.ts, src/services/api.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1481/)
Current: 78.94 MB | Main: 78.94 MB
Diff: +0.26 KB (0.00%)
<details>
</details>
=> fix(Versions): request only SystemState

src/store/reducers/executeTopQueries/executeTopQueries.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1487/)
Current: 78.94 MB | Main: 78.94 MB
Diff: 0.07 KB (-0.00%)
<details>
</details>
=> fix: exclude top and running queries itself

src/components/EntityStatus/EntityStatus.scss, src/components/MonitoringButton/MonitoringButton.tsx, src/containers/AppWithClusters/ExtendedTenant/ExtendedTenant.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1494/)
Current: 78.94 MB | Main: 78.94 MB
Diff: +0.08 KB (0.00%)
<details>
</details>
=> fix(EntityStatus): set minimum container width

src/containers/Operations/Operations.scss, src/containers/Operations/OperationsControls.tsx
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1519
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1521/)
Diff: +0.23 KB (0.00%)
<details>
</details>
=> fix: operations kind button width

LICENSE
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1516/)
<details>
</details>
=> fix: update license

src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
Closes #1527 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1528/)
| 134 | 130 | 0 | 4 | 0 |
Diff: 0.41 KB (-0.00%)
<details>
</details>
=> fix(TenantOverview): fix used tablet storage calculation

src/containers/Cluster/ClusterDashboard/ClusterDashboard.tsx, src/containers/Cluster/ClusterInfo/utils.tsx, src/types/api/cluster.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1535/)
Diff: +0.71 KB (0.00%)
<details>
</details>
=> fix(ClusterDashboard): hide dashboard if /cluster handler version less 5

src/containers/Nodes/columns/constants.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1598/)
Current: 79.23 MB | Main: 79.23 MB
Diff: 0.08 KB (-0.00%)
<details>
</details>
=> fix(Nodes): remove redundant group by params

src/components/EntityStatus/EntityStatus.tsx
=> fix(EntityStatus): show title for text part only

src/containers/Tenant/utils/schemaQueryTemplates.ts
closes #1467 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1616/)
Current: 66.02 MB | Main: 66.02 MB
<details>
</details>
=> fix(schemaQueryTemplates): doc link for topic creation

.github/workflows/ci.yml
=> fix: remove push trigger

.github/workflows/ci.yml
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1671/)
| 186 | 186 | 0 | 0 | 0 | ➖ 0 |
<details>
- ➖ indicates 0 new test cases added in this PR.
</details>
=> fix: deploy report condition

src/containers/Tenant/Diagnostics/TopQueries/getTopQueriesColumns.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1701/)
Diff: +0.03 KB (0.00%)
<details>
</details>
=> fix(TopQueries): add queryHashColumns

package-lock.json, package.json
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1720/)
Current: 65.95 MB | Main: 66.09 MB
Diff: 0.13 MB (-0.20%)
<details>
</details>
=> fix: dependabot found vulnerabilities

package-lock.json, package.json, src/utils/monaco/yql/generateSuggestions.ts, src/utils/monaco/yql/yqlSuggestions.ts
closes #897 
[Stand](https://nda.ya.ru/t/ET_ZC0sm7ANdPG)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1752/)
Current: 65.88 MB | Main: 65.84 MB
Diff: +0.04 MB (0.06%)
<details>
</details>
=> feat(autocomplete): suggest variables

playwright.config.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1762
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1763/)
| 222 | 221 | 0 | 1 | 0 |
<details>
</details>
=> chore: take shots and video for main branch

src/components/Table/Table.scss
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1764/)
| 222 | 220 | 0 | 2 | 0 |
Diff: +0.02 KB (0.00%)
<details>
</details>
=> fix(Table): cell aligning should be maximum specific

src/containers/Tenant/Schema/SchemaViewer/columns.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1765/)
| 222 | 221 | 0 | 1 | 0 |
<details>
</details>
=> fix(Schema): increase default columns width

src/containers/Tenant/utils/schemaQueryTemplates.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1772/)
Current: 65.89 MB | Main: 65.89 MB
<details>
</details>
=> fix: create view template text

src/containers/App/Content.tsx, src/store/reducers/capabilities/hooks.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1785/)
Current: 66.16 MB | Main: 66.16 MB
Diff: +0.41 KB (0.00%)
<details>
</details>
=> fix(Cluster): show loader if capabilities not loaded

package-lock.json, package.json
Closes #1808 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1809/)
| 240 | 239 | 0 | 1 | 0 |
Current: 66.13 MB | Main: 66.13 MB
<details>
</details>
=> ci: update playwright

src/services/api/base.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/1828
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1829/)
| 262 | 259 | 2 | 1 | 0 |
<details>
</details>
=> fix: remove retries

.github/workflows/quality.yml
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1834/)
<details>
</details>
=> fix: update actions

src/containers/App/Content.tsx, src/services/api/viewer.ts, src/store/reducers/authentication/authentication.ts, src/store/reducers/capabilities/hooks.ts, src/utils/hooks/useDatabaseFromQuery.ts
Closes #1856 
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1860/)
Diff: +0.59 KB (0.00%)
<details>
</details>
=> feat: pass database to whoami

src/containers/Tenant/Query/i18n/en.json
@kunga
сообщение дурацкое
Query results are displayed for Timeout: 86400
@alexv-smirnov
А что оно значит? Я в недоумении…)
@hor911
А меня сильно смущает надпись "Query results" в отсутствие результата как такового. Прямо кажется что кто-то что-то продолбал
=> fix: avoid confusion with information interpretation

src/containers/Operations/Operations.tsx, src/containers/Tenant/Diagnostics/Configs/Configs.tsx
Closes #1904, closes #1905
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1908/)
Current: 80.19 MB | Main: 80.19 MB
<details>
</details>
=> fix(Configs,Operations): fix blicks on autorefresh

src/index.tsx, src/styles/index.scss
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1965/)
Current: 80.46 MB | Main: 80.46 MB
Diff: 0.05 KB (-0.00%)
<details>
</details>
=> refactor: all general styles files in styles/index.scss

tests/suites/tenant/queryEditor/models/QueryEditor.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1988/)
Current: 80.78 MB | Main: 80.78 MB
<details>
</details>
=> fix: tests

src/types/api/healthcheck.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2000/)
<details>
</details>
<details>
</details>
=> chore: update healthcheck types

src/containers/Cluster/ClusterInfo/utils/utils.tsx, src/containers/Clusters/columns.tsx, src/store/reducers/clusters/selectors.ts, src/types/api/cluster.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2094
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2095/)
| 286 | 286 | 0 | 0 | 0 |
Current: 83.25 MB | Main: 83.25 MB
Diff: +0.97 KB (0.00%)
<details>
</details>
=> fix: add RealNumberOfCpus to aggregates

src/store/reducers/overview/overview.ts, src/store/reducers/viewSchema/viewSchema.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2126
[Stand](https://nda.ya.ru/t/2bGsKp4l7DUQjG)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2127/)
Diff: +0.70 KB (0.00%)
<details>
</details>
=> fix: reuse table schema for select template for current table

src/containers/Storage/TableGroup/TableGroup.scss
=> fix(TableGroup): prevent content border overflow

src/containers/Tenant/Diagnostics/TopQueries/utils.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2182
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2183/)
Diff: +0.05 KB (0.00%)
<details>
</details>
=> fix: table in queries sorts by string values after backend sort

src/components/ShardsTable/ShardsTable.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2187/)
Diff: +0.23 KB (0.00%)
<details>
</details>
=> feat: add possibility to pass external columns

src/containers/Tenant/Diagnostics/TopQueries/RunningQueriesData.tsx, src/containers/Tenant/Diagnostics/TopQueries/TopQueriesData.tsx, src/containers/Tenant/Diagnostics/TopQueries/hooks/useRunningQueriesSort.ts, src/containers/Tenant/Diagnostics/TopQueries/hooks/useSortParam.ts, src/containers/Tenant/Diagnostics/TopQueries/hooks/useTopQueriesSort.ts, src/containers/Tenant/Diagnostics/TopQueries/utils.ts
Closes https://github.com/ydb-platform/ydb-embedded-ui/issues/2230
[Stand](https://nda.ya.ru/t/q1Xo7DIg7E5cZj)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2234/)
Current: 83.38 MB | Main: 83.38 MB
Diff: +7.25 KB (0.01%)
<details>
</details>
=> feat: save sorting columns in queries

src/containers/Cluster/ClusterOverview/ClusterOverview.scss, src/containers/Cluster/ClusterOverview/ClusterOverview.tsx, src/containers/Cluster/ClusterOverview/components/ClusterMetricsCard.tsx
=> fix(ClusterOverview): loading state

src/containers/Operations/useOperationsQueryParams.ts
Built stand with these changes but forgot to commit them....
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2259/)
Diff: +0.03 KB (0.00%)
<details>
</details>
=> fix: missed schema value

src/containers/Tenants/Tenants.tsx
Part of #2272 
Before:
After:
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2276/)
Diff: +0.00 KB (0.00%)
<details>
</details>
=> fix(Tenants): make state column wider

src/containers/Tenant/Diagnostics/TopicData/TopicData.tsx
closes #2313
[stand](https://nda.ya.ru/t/-fJ_0WuQ7Egy8g)
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2314/)
Current: 83.59 MB | Main: 83.59 MB
Diff: +0.51 KB (0.00%)
<details>
</details>
=> fix: reset base offsets on selected partition change

src/containers/Tenants/Tenants.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2336/)
Current: 83.62 MB | Main: 83.62 MB
Diff: +0.19 KB (0.00%)
<details>
</details>
=> fix(Tenants): do not show actions for domain

src/containers/Tenant/Healthcheck/Healthcheck.tsx, src/containers/Tenant/Healthcheck/components/HealthcheckView.tsx, src/uiFactory/types.ts, src/uiFactory/uiFactory.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2402/)
| 322 | 317 | 0 | 4 | 1 |
<details>
</details>
Current: 83.77 MB | Main: 83.77 MB
Diff: +0.11 KB (0.00%)
<details>
</details>
=> fix(Healthcheck): types

src/store/reducers/capabilities/hooks.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2529/)
| 354 | 351 | 0 | 2 | 1 |
<details>
</details>
Current: 84.00 MB | Main: 84.00 MB
<details>
</details>
=> fix(capabilities): show topic data from 1 handler version

src/types/api/systemState.ts
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2677/)
| 358 | 353 | 0 | 3 | 2 |
<details>
</details>
Current: 85.35 MB | Main: 85.35 MB
<details> …
=> chore: fix types

src/components/SpeedMultiMeter/SpeedMultiMeter.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2700/)
| 358 | 351 | 0 | 5 | 2 |
<details>
</details>
Current: 85.33 MB | Main: 85.33 MB
Diff: 0.02 KB (-0.00%)
<details> …
=> fix(SpeedMultiMeter): update title it new props

src/containers/Cluster/ClusterOverview/components/BridgeInfoTable.tsx, src/types/api/cluster.ts, tests/suites/bridge/mocks.ts
according to https://github.com/ydb-platform/ydb/pull/23223
=> fix: rename PROMOTE to PROMOTED

src/containers/Tenant/utils/schemaActions.tsx
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2851/)
<details>
</details>
Current: 85.42 MB | Main: 85.42 MB
Diff: 0.01 KB (-0.00%)
<details> …
=> fix(schemaActions): pass database to getConnectToDBDialog

src/containers/Header/Header.tsx
Closes #2872
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2873/)
| 378 | 372 | 0 | 4 | 2 |
<details>
</details>
Current: 85.43 MB | Main: 85.43 MB
<details>
- 🔺 indicates …
=> fix(Header): fix add cluster button blinking on refresh

src/containers/Tenant/Diagnostics/TenantOverview/TenantOverview.tsx
closes #2922
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2925/)
<details>
</details>
<details>
- 🔺 indicates …
=> fix(TenantOverview): use database path in request

src/containers/Cluster/i18n/en.json
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/2963/)
<details>
</details>
Current: 47.05 MB | Main: 47.05 MB
<details> …
=> fix: keysets
